// VerbSpec surface for hooksmith's contract-validator WASM component.
//
// One source of truth → CLI + MCP projection, same model as string-audit.
//
// Build the WASM and its JS bindings first:
//   npm run build          (cargo → wasm32-wasip2 → jco transpile)
//
// Then the verbs here import from dist/contract-validator/ which is the
// jco-generated JS module that wraps the WASM. No Rust toolchain needed at
// runtime — just a compiled .wasm and Node 18+.
//
// Two verbs:
//   validate  — read git tree entries, run validate-names in WASM, report findings
//   drift     — check a prose string against a verbspec registry vocab
import { defineVerb } from "@bounded-systems/verbspec";
import { execFileSync } from "node:child_process";
import { z } from "zod";

// ── WASM loader ───────────────────────────────────────────────────────────────
//
// Lazily import the jco-transpiled JS bindings on first use. The file is
// generated by `npm run build:jco` from the contract_validator.wasm binary.
// We use a lazy singleton so `import contract-verbs.mjs` doesn't throw if
// the dist/ folder hasn't been built yet (the verbs just fail at run-time
// with a clear message).

let _wasm = null;

async function wasm() {
  if (_wasm) return _wasm;
  try {
    _wasm = await import("./dist/contract-validator/contract_validator.js");
  } catch {
    throw new Error(
      "contract-validator WASM not built — run `npm run build` in js/ first"
    );
  }
  return _wasm;
}

// ── Shared output types ───────────────────────────────────────────────────────

const Finding = z.object({
  level: z.enum(["error", "warn", "info"]),
  rule: z.string(),
  message: z.string(),
  path: z.string().nullable(),
});

const DriftFinding = z.object({
  level: z.enum(["error", "warn", "info"]),
  message: z.string(),
});

// ── validate verb ─────────────────────────────────────────────────────────────
//
// The host reads the git tree (via `git ls-tree`), passes the entries to the
// WASM component, and returns structured findings. No git2 in the component —
// just pure rule matching.

export const validateVerb = defineVerb({
  id: "validate",
  summary:
    "Validate a git tree's entry names against a hooksmith naming contract.",
  actor: "validate",
  input: z.object({
    repo: z
      .string()
      .optional()
      .describe("Path to the git repository (default: cwd)."),
    ref: z
      .string()
      .optional()
      .describe("Git ref to read the tree from (default: HEAD)."),
    required: z
      .array(z.string())
      .optional()
      .describe("Entry names (or globs) that must be present."),
    allowed: z
      .array(z.string())
      .optional()
      .describe("Entry names (or globs) that are permitted."),
    rejected: z
      .array(z.string())
      .optional()
      .describe("Entry names (or globs) that are forbidden."),
  }),
  output: z.object({
    ref: z.string(),
    passed: z.boolean(),
    score: z.number(),
    findings: z.array(Finding),
    entry_count: z.number(),
  }),
  run: async (input) => {
    const repo = input.repo ?? ".";
    const ref = input.ref ?? "HEAD";

    // Host side: read git tree entries (no git2 needed — plain CLI).
    const raw = execFileSync("git", ["-C", repo, "ls-tree", ref], {
      encoding: "utf8",
    });

    // git ls-tree format: `<mode> <type> <sha>\t<name>`
    const entries = raw
      .trim()
      .split("\n")
      .filter(Boolean)
      .map((line) => {
        const [meta, name] = line.split("\t");
        const kind = meta.split(" ")[1]; // "blob" | "tree"
        return { name, kind };
      });

    // Call into the WASM component (pure logic — no git).
    const { validateNames } = await wasm();
    const result = validateNames(entries, {
      required: input.required ?? [],
      allowed: input.allowed ?? [],
      rejected: input.rejected ?? [],
    });

    return {
      ref,
      passed: result.passed,
      score: result.score,
      findings: result.findings.map((f) => ({ ...f, path: f.path ?? null })),
      entry_count: entries.length,
    };
  },
  render: (out) => {
    const glyph = { error: "✗", warn: "⚠", info: "·" };
    const lines = [
      `\n  VALIDATE — ${out.ref}  ${out.passed ? "✓ passed" : "✗ failed"}  score ${out.score}/10  (${out.entry_count} entries)\n  ${"─".repeat(54)}`,
    ];
    for (const f of out.findings) {
      const loc = f.path ? ` [${f.path}]` : "";
      lines.push(`  ${glyph[f.level] ?? "·"} ${f.rule}${loc}: ${f.message}`);
    }
    if (out.findings.length === 0) lines.push("  (no findings)");
    lines.push("");
    return lines.map((l) => l + "\n").join("");
  },
});

// ── drift verb ────────────────────────────────────────────────────────────────
//
// Check a prose string against the verbspec registry vocab. Mirrors
// string-audit's registryDrift but runs inside the WASM component so it
// can be called without importing verbspec or Zod into the validator.
//
// The caller passes the vocab directly (flags, enums, bins, verbIds) — the
// WASM component does the pattern matching.

export const driftVerb = defineVerb({
  id: "drift",
  summary:
    "Check a prose string for --flags, ENUM=values, or `bin verb` tokens that have drifted from the verbspec registry.",
  actor: "validate",
  input: z.object({
    value: z.string().describe("The prose string to check."),
    type: z
      .enum(["headline", "body", "subhead", "title"])
      .describe("Copy type — determines whether the check applies."),
    flags: z
      .array(z.string())
      .optional()
      .describe("Known flag names from the registry (e.g. [\"catalog\", \"store\"])."),
    enums: z
      .array(
        z.object({
          flag: z.string(),
          values: z.array(z.string()),
        })
      )
      .optional()
      .describe("Enum-valued flags and their allowed values."),
    bins: z
      .array(z.string())
      .optional()
      .describe("Known binary names (e.g. [\"hooksmith\", \"hooksmith-validate\"])."),
    verbIds: z
      .array(z.string())
      .optional()
      .describe("Known verb IDs from the registry (e.g. [\"validate\", \"check\"])."),
  }),
  output: z.object({
    findings: z.array(DriftFinding),
    clean: z.boolean(),
  }),
  run: async (input) => {
    const { checkCopyDrift } = await wasm();
    const findings = checkCopyDrift(input.value, input.type, {
      flags: input.flags ?? [],
      enums: input.enums ?? [],
      bins: input.bins ?? [],
      verbIds: input.verbIds ?? [],
    });
    return { findings, clean: findings.length === 0 };
  },
  render: (out) => {
    if (out.clean) return "  ✓ no drift\n";
    const glyph = { error: "✗", warn: "⚠", info: "·" };
    return (
      out.findings
        .map((f) => `  ${glyph[f.level] ?? "·"} ${f.message}`)
        .join("\n") + "\n"
    );
  },
});

// One typed registry → CLI + MCP projection (same pattern as string-audit).
export const registry = { validate: validateVerb, drift: driftVerb };
