# @generated by xtask gen-config
# @checksum: 9b1041e0

# Hooksmith Makefile - Optimized Build Tasks

.PHONY: help build test clean dev fast-test setup

help: ## Show this help message
	@echo "Hooksmith - Optimized Build Tasks"
	@echo "=================================="
	@echo ""
	@echo "Available commands:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'

setup: ## Install and configure optimization tools
	./scripts/optimize-build.sh
	source scripts/setup-env.sh

build: ## Build the project with optimizations
	cargo dev-fast

test: ## Run tests with parallel execution
	cargo test-parallel

fast-test: ## Run tests quickly (no capture)
	cargo test-fast

dev: ## Run development cycle
	./scripts/dev-cycle.sh

clean: ## Clean all build artifacts
	cargo clean-all

check: ## Run fast check
	cargo check-fast

docs: ## Generate and open documentation
	cargo docs

stats: ## Show build performance statistics
	./scripts/build-stats.sh

validate: ## Validate project configuration
	cargo validate

ci: ## Run CI build locally
	./scripts/ci-build.sh

# Default target
.DEFAULT_GOAL := help 