use anyhow::{Context, Result};
use sha2::{Digest, Sha256};
use std::fs;
use std::path::Path;

/// Compute a deterministic checksum for file content
/// The checksum is computed over the content excluding the header lines
pub fn compute_file_checksum(content: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(content.as_bytes());
    let result = hasher.finalize();

    // Return first 8 characters of hex string
    format!("{:x}", result)[..8].to_string()
}

/// Extract content without header lines for checksum computation
pub fn extract_content_without_header(content: &str, header_lines: &[String]) -> String {
    let lines: Vec<&str> = content.lines().collect();
    let header_count = header_lines.len();

    if lines.len() <= header_count {
        return String::new();
    }

    // Skip header lines and return the rest
    lines[header_count..].join("\n")
}

/// Generate a complete header with checksum
pub fn generate_header_with_checksum(file_type: &str, content_without_header: &str) -> String {
    let checksum = compute_file_checksum(content_without_header);

    match file_type {
        "md" => format!(
            "<!-- @generated by xtask gen-files --file-type=md -->\n<!-- @checksum: {} -->\n",
            checksum
        ),
        "toml" => format!(
            "# @generated by xtask gen-files --file-type=toml\n# @checksum: {}\n",
            checksum
        ),
        "yml" => format!(
            "# @generated by xtask gen-files --file-type=yml\n# @checksum: {}\n",
            checksum
        ),
        "yaml" => format!(
            "# @generated by xtask gen-files --file-type=yaml\n# @checksum: {}\n",
            checksum
        ),
        "gitignore" => format!(
            "# @generated by xtask gen-files --file-type=gitignore\n# @checksum: {}\n",
            checksum
        ),
        "gitattributes" => format!(
            "# @generated by xtask gen-files --file-type=gitattributes\n# @checksum: {}\n",
            checksum
        ),
        "CODEOWNERS" => format!(
            "# @generated by xtask gen-files --file-type=CODEOWNERS\n# @checksum: {}\n",
            checksum
        ),
        "json" => format!(
            "// @generated by xtask gen-files --file-type=json\n// @checksum: {}\n",
            checksum
        ),
        "jsonl" => format!(
            "// @generated by xtask gen-files --file-type=jsonl\n// @checksum: {}\n",
            checksum
        ),
        "jql" => format!(
            "// @generated by xtask gen-files --file-type=jql\n// @checksum: {}\n",
            checksum
        ),
        "wit" => format!(
            ";; @generated by xtask gen-files --file-type=wit\n;; @checksum: {}\n",
            checksum
        ),
        "makefile" => format!(
            "# @generated by xtask gen-files --file-type=makefile\n# @checksum: {}\n",
            checksum
        ),
        "editorconfig" => format!(
            "# @generated by xtask gen-files --file-type=editorconfig\n# @checksum: {}\n",
            checksum
        ),
        "envrc" => format!(
            "# @generated by xtask gen-files --file-type=envrc\n# @checksum: {}\n",
            checksum
        ),
        _ => format!(
            "# @generated by xtask gen-files --file-type={}\n# @checksum: {}\n",
            file_type, checksum
        ),
    }
}

/// Validate a file's checksum against its content
pub fn validate_file_checksum(file_path: &Path, file_type: &str) -> Result<bool> {
    let content = fs::read_to_string(file_path)
        .context(format!("Failed to read file: {}", file_path.display()))?;

    // Extract the expected checksum from the header
    let expected_checksum = extract_checksum_from_header(&content, file_type)?;

    // Compute checksum of content without header
    let content_without_header =
        extract_content_without_header(&content, &get_header_template(file_type));
    let actual_checksum = compute_file_checksum(&content_without_header);

    Ok(expected_checksum == actual_checksum)
}

/// Extract checksum from file header
fn extract_checksum_from_header(content: &str, file_type: &str) -> Result<String> {
    let lines: Vec<&str> = content.lines().collect();

    if lines.len() < 2 {
        return Err(anyhow::anyhow!("File too short to contain checksum header"));
    }

    // Look for checksum line based on file type
    let checksum_prefix = match file_type {
        "md" => "<!-- @checksum:",
        "toml" | "yml" | "yaml" | "gitignore" | "gitattributes" | "CODEOWNERS" | "makefile"
        | "editorconfig" | "envrc" => "# @checksum:",
        "json" | "jsonl" | "jql" => "// @checksum:",
        "wit" => ";; @checksum:",
        _ => "# @checksum:",
    };

    for line in lines.iter().take(3) {
        if line.trim().starts_with(checksum_prefix) {
            let checksum = line
                .trim()
                .strip_prefix(checksum_prefix)
                .ok_or_else(|| anyhow::anyhow!("Invalid checksum line format"))?
                .trim();
            return Ok(checksum.to_string());
        }
    }

    Err(anyhow::anyhow!("No checksum found in header"))
}

/// Get header template for a file type
fn get_header_template(file_type: &str) -> Vec<String> {
    match file_type {
        "md" => vec![
            "<!-- @generated by xtask gen-files --file-type=md -->".to_string(),
            "<!-- @checksum:".to_string(),
        ],
        "toml" => vec![
            "# @generated by xtask gen-files --file-type=toml".to_string(),
            "# @checksum:".to_string(),
        ],
        "yml" => vec![
            "# @generated by xtask gen-files --file-type=yml".to_string(),
            "# @checksum:".to_string(),
        ],
        "yaml" => vec![
            "# @generated by xtask gen-files --file-type=yaml".to_string(),
            "# @checksum:".to_string(),
        ],
        "gitignore" => vec![
            "# @generated by xtask gen-files --file-type=gitignore".to_string(),
            "# @checksum:".to_string(),
        ],
        "gitattributes" => vec![
            "# @generated by xtask gen-files --file-type=gitattributes".to_string(),
            "# @checksum:".to_string(),
        ],
        "CODEOWNERS" => vec![
            "# @generated by xtask gen-files --file-type=CODEOWNERS".to_string(),
            "# @checksum:".to_string(),
        ],
        "json" => vec![
            "// @generated by xtask gen-files --file-type=json".to_string(),
            "// @checksum:".to_string(),
        ],
        "jsonl" => vec![
            "// @generated by xtask gen-files --file-type=jsonl".to_string(),
            "// @checksum:".to_string(),
        ],
        "jql" => vec![
            "// @generated by xtask gen-files --file-type=jql".to_string(),
            "// @checksum:".to_string(),
        ],
        "wit" => vec![
            ";; @generated by xtask gen-files --file-type=wit".to_string(),
            ";; @checksum:".to_string(),
        ],
        "makefile" => vec![
            "# @generated by xtask gen-files --file-type=makefile".to_string(),
            "# @checksum:".to_string(),
        ],
        "editorconfig" => vec![
            "# @generated by xtask gen-files --file-type=editorconfig".to_string(),
            "# @checksum:".to_string(),
        ],
        "envrc" => vec![
            "# @generated by xtask gen-files --file-type=envrc".to_string(),
            "# @checksum:".to_string(),
        ],
        _ => vec![
            format!("# @generated by xtask gen-files --file-type={}", file_type),
            "# @checksum:".to_string(),
        ],
    }
}

/// Write a file with generated header and checksum
pub fn write_file_with_checksum(file_path: &Path, file_type: &str, content: &str) -> Result<()> {
    let header = generate_header_with_checksum(file_type, content);
    let full_content = format!("{}{}", header, content);

    fs::write(file_path, full_content)
        .context(format!("Failed to write file: {}", file_path.display()))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::NamedTempFile;

    #[test]
    fn test_compute_file_checksum() {
        let content = "test content\nwith multiple lines";
        let checksum = compute_file_checksum(content);
        assert_eq!(checksum.len(), 8);
        assert!(checksum.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn test_extract_content_without_header() {
        let content = "# @generated by xtask gen-files --file-type=toml\n# @checksum: abc12345\nactual content\nmore content";
        let header = vec![
            "# @generated by xtask gen-files --file-type=toml".to_string(),
            "# @checksum:".to_string(),
        ];

        let extracted = extract_content_without_header(content, &header);
        assert_eq!(extracted, "actual content\nmore content");
    }

    #[test]
    fn test_generate_header_with_checksum() {
        let content = "test content";
        let header = generate_header_with_checksum("toml", content);

        assert!(header.contains("# @generated by xtask gen-files --file-type=toml"));
        assert!(header.contains("# @checksum:"));
        assert!(header.ends_with("\n"));
    }

    #[test]
    fn test_write_and_validate_file() -> Result<()> {
        let temp_file = NamedTempFile::new()?;
        let file_path = temp_file.path();
        let content = "test content\nwith multiple lines";

        // Write file with checksum
        write_file_with_checksum(file_path, "toml", content)?;

        // Validate checksum
        let is_valid = validate_file_checksum(file_path, "toml")?;
        assert!(is_valid);

        Ok(())
    }
}
