// This file is auto-generated by `cargo xtask`
// Generated file: xtask/src/event_stream.rs
// Do not edit this file manually - changes will be overwritten

use anyhow::Result;
use chrono::{DateTime, Utc};
use once_cell::sync::Lazy;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs::{File, OpenOptions};
use std::io::{BufWriter, Write};
use std::path::PathBuf;
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};
use tokio::sync::broadcast;
use uuid::Uuid;

/// Event severity levels
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum EventSeverity {
    /// Trace level events
    Trace,
    /// Debug level events
    Debug,
    /// Info level events
    Info,
    /// Warning level events
    Warn,
    /// Error level events
    Error,
    /// Critical level events
    Critical,
}

/// Event categories for filtering and routing
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum EventCategory {
    /// Hook state machine events
    HookStateMachine,
    /// Git operations
    Git,
    /// Validation events
    Validation,
    /// Build events
    Build,
    /// Contract validation
    Contract,
    /// File operations
    File,
    /// System events
    System,
    /// User actions
    User,
    /// Performance metrics
    Performance,
    /// Security events
    Security,
    /// Custom category
    Custom(String),
}

/// Base event structure
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Event {
    /// Unique event ID
    pub id: String,
    /// Event timestamp
    pub timestamp: DateTime<Utc>,
    /// Event severity
    pub severity: EventSeverity,
    /// Event category
    pub category: EventCategory,
    /// Event type/name
    pub event_type: String,
    /// Event message
    pub message: String,
    /// Event source (component/module)
    pub source: String,
    /// Event duration (if applicable)
    pub duration_ms: Option<u64>,
    /// Event metadata
    pub metadata: HashMap<String, serde_json::Value>,
    /// Related event IDs (for event chains)
    pub related_events: Vec<String>,
    /// User context (if available)
    pub user_context: Option<String>,
    /// Session ID for grouping related events
    pub session_id: Option<String>,
}

impl Event {
    /// Create a new event
    pub fn new(
        severity: EventSeverity,
        category: EventCategory,
        event_type: String,
        message: String,
        source: String,
    ) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            timestamp: Utc::now(),
            severity,
            category,
            event_type,
            message,
            source,
            duration_ms: None,
            metadata: HashMap::new(),
            related_events: Vec::new(),
            user_context: None,
            session_id: None,
        }
    }

    /// Add metadata to the event
    pub fn with_metadata(mut self, key: String, value: serde_json::Value) -> Self {
        self.metadata.insert(key, value);
        self
    }

    /// Set event duration
    pub fn with_duration(mut self, duration: Duration) -> Self {
        self.duration_ms = Some(duration.as_millis() as u64);
        self
    }

    /// Add related event ID
    pub fn with_related_event(mut self, event_id: String) -> Self {
        self.related_events.push(event_id);
        self
    }

    /// Set user context
    pub fn with_user_context(mut self, context: String) -> Self {
        self.user_context = Some(context);
        self
    }

    /// Set session ID
    pub fn with_session_id(mut self, session_id: String) -> Self {
        self.session_id = Some(session_id);
        self
    }

    /// Convert to JSONL format
    pub fn to_jsonl(&self) -> Result<String> {
        Ok(serde_json::to_string(self)?)
    }
}

/// Event stream configuration
#[derive(Debug, Clone)]
pub struct EventStreamConfig {
    /// Output file path for JSONL events
    pub output_file: Option<PathBuf>,
    /// Whether to enable console output
    pub console_output: bool,
    /// Whether to enable real-time broadcasting
    pub enable_broadcast: bool,
    /// Maximum broadcast channel capacity
    pub broadcast_capacity: usize,
    /// Event retention period
    pub retention_period: Option<Duration>,
    /// Whether to enable event filtering
    pub enable_filtering: bool,
    /// Minimum severity level to log
    pub min_severity: EventSeverity,
}

impl Default for EventStreamConfig {
    fn default() -> Self {
        Self {
            output_file: Some(PathBuf::from("hooksmith-events.jsonl")),
            console_output: true,
            enable_broadcast: true,
            broadcast_capacity: 1000,
            retention_period: Some(Duration::from_secs(24 * 60 * 60)), // 24 hours
            enable_filtering: true,
            min_severity: EventSeverity::Info,
        }
    }
}

/// Event stream manager
pub struct EventStream {
    /// Configuration
    config: EventStreamConfig,
    /// File writer for JSONL output
    file_writer: Option<Arc<Mutex<BufWriter<File>>>>,
    /// Broadcast channel for real-time events
    broadcast_tx: Option<broadcast::Sender<Event>>,
    /// Event statistics
    stats: Arc<Mutex<EventStats>>,
    /// Session ID for current run
    session_id: String,
}

/// Event statistics
#[derive(Debug, Default, Clone)]
struct EventStats {
    total_events: u64,
    events_by_severity: HashMap<EventSeverity, u64>,
    events_by_category: HashMap<EventCategory, u64>,
    events_by_source: HashMap<String, u64>,
    start_time: Option<Instant>,
}

impl EventStream {
    /// Create a new event stream
    pub fn new(config: EventStreamConfig) -> Result<Self> {
        let file_writer = if let Some(output_file) = &config.output_file {
            let file = OpenOptions::new()
                .create(true)
                .append(true)
                .open(output_file)?;
            Some(Arc::new(Mutex::new(BufWriter::new(file))))
        } else {
            None
        };

        let broadcast_tx = if config.enable_broadcast {
            Some(broadcast::channel(config.broadcast_capacity).0)
        } else {
            None
        };

        let session_id = Uuid::new_v4().to_string();

        Ok(Self {
            config,
            file_writer,
            broadcast_tx,
            stats: Arc::new(Mutex::new(EventStats::default())),
            session_id,
        })
    }

    /// Emit an event
    pub fn emit(&self, mut event: Event) -> Result<()> {
        // Set session ID if not already set
        if event.session_id.is_none() {
            event.session_id = Some(self.session_id.clone());
        }

        // Check severity filter
        if self.config.enable_filtering && event.severity < self.config.min_severity {
            return Ok(());
        }

        // Update statistics
        self.update_stats(&event)?;

        // Write to file
        if let Some(writer) = &self.file_writer {
            let jsonl = event.to_jsonl()?;
            let mut writer = writer.lock().unwrap();
            writeln!(writer, "{jsonl}")?;
            writer.flush()?;
        }

        // Console output
        if self.config.console_output {
            self.print_console(&event)?;
        }

        // Broadcast to subscribers
        if let Some(tx) = &self.broadcast_tx {
            let _ = tx.send(event.clone());
        }

        Ok(())
    }

    /// Create a subscriber for real-time events
    pub fn subscribe(&self) -> Option<broadcast::Receiver<Event>> {
        self.broadcast_tx.as_ref().map(|tx| tx.subscribe())
    }

    /// Get event statistics
    pub fn get_stats(&self) -> Result<EventStats> {
        Ok(self.stats.lock().unwrap().clone())
    }

    /// Get current session ID
    pub fn session_id(&self) -> &str {
        &self.session_id
    }

    /// Update event statistics
    fn update_stats(&self, event: &Event) -> Result<()> {
        let mut stats = self.stats.lock().unwrap();

        if stats.start_time.is_none() {
            stats.start_time = Some(Instant::now());
        }

        stats.total_events += 1;
        *stats
            .events_by_severity
            .entry(event.severity.clone())
            .or_insert(0) += 1;
        *stats
            .events_by_category
            .entry(event.category.clone())
            .or_insert(0) += 1;
        *stats
            .events_by_source
            .entry(event.source.clone())
            .or_insert(0) += 1;

        Ok(())
    }

    /// Print event to console with formatting
    fn print_console(&self, event: &Event) -> Result<()> {
        let severity_icon = match event.severity {
            EventSeverity::Trace => "🔍",
            EventSeverity::Debug => "🐛",
            EventSeverity::Info => "ℹ️",
            EventSeverity::Warn => "⚠️",
            EventSeverity::Error => "❌",
            EventSeverity::Critical => "🚨",
        };

        let category_icon = match &event.category {
            EventCategory::HookStateMachine => "⚙️",
            EventCategory::Git => "📝",
            EventCategory::Validation => "✅",
            EventCategory::Build => "🔨",
            EventCategory::Contract => "📋",
            EventCategory::File => "📁",
            EventCategory::System => "🖥️",
            EventCategory::User => "👤",
            EventCategory::Performance => "⚡",
            EventCategory::Security => "🔒",
            EventCategory::Custom(_) => "🎯",
        };

        let duration_str = if let Some(duration) = event.duration_ms {
            format!(" ({duration}ms)")
        } else {
            String::new()
        };

        println!(
            "{} {} [{}] {}: {}{}",
            severity_icon,
            category_icon,
            event.event_type,
            event.source,
            event.message,
            duration_str
        );

        // Print metadata if present
        if !event.metadata.is_empty() {
            for (key, value) in &event.metadata {
                println!("  {key}: {value}");
            }
        }

        Ok(())
    }
}

/// Global event stream instance
static EVENT_STREAM: Lazy<Mutex<Option<Arc<EventStream>>>> = Lazy::new(|| Mutex::new(None));

/// Initialize the global event stream
pub fn init_event_stream(config: EventStreamConfig) -> Result<()> {
    let event_stream = EventStream::new(config)?;
    let mut guard = EVENT_STREAM.lock().unwrap();
    *guard = Some(Arc::new(event_stream));
    Ok(())
}

/// Get the global event stream
pub fn get_event_stream() -> Option<Arc<EventStream>> {
    EVENT_STREAM.lock().unwrap().clone()
}

/// Emit an event using the global event stream
pub fn emit_event(event: Event) -> Result<()> {
    if let Some(stream) = get_event_stream() {
        stream.emit(event)?;
    }
    Ok(())
}

/// Convenience function to emit info events
pub fn emit_info(
    category: EventCategory,
    event_type: &str,
    message: &str,
    source: &str,
) -> Result<()> {
    let event = Event::new(
        EventSeverity::Info,
        category,
        event_type.to_string(),
        message.to_string(),
        source.to_string(),
    );
    emit_event(event)
}

/// Convenience function to emit warning events
pub fn emit_warn(
    category: EventCategory,
    event_type: &str,
    message: &str,
    source: &str,
) -> Result<()> {
    let event = Event::new(
        EventSeverity::Warn,
        category,
        event_type.to_string(),
        message.to_string(),
        source.to_string(),
    );
    emit_event(event)
}

/// Convenience function to emit error events
pub fn emit_error(
    category: EventCategory,
    event_type: &str,
    message: &str,
    source: &str,
) -> Result<()> {
    let event = Event::new(
        EventSeverity::Error,
        category,
        event_type.to_string(),
        message.to_string(),
        source.to_string(),
    );
    emit_event(event)
}

/// Event monitor for real-time event processing
pub struct EventMonitor {
    /// Event receiver
    receiver: broadcast::Receiver<Event>,
    /// Event handlers
    handlers: Vec<Box<dyn EventHandler + Send + Sync>>,
    /// Whether the monitor is running
    running: bool,
}

/// Event handler trait
pub trait EventHandler {
    /// Handle an event
    fn handle_event(&mut self, event: &Event) -> Result<()>;
    /// Get handler name
    fn name(&self) -> &str;
    /// Check if handler should process this event
    fn should_handle(&self, event: &Event) -> bool {
        true
    }
}

impl EventMonitor {
    /// Create a new event monitor
    pub fn new() -> Result<Self> {
        let receiver = if let Some(stream) = get_event_stream() {
            stream
                .subscribe()
                .ok_or_else(|| anyhow::anyhow!("Event stream not configured for broadcasting"))?
        } else {
            anyhow::bail!("Event stream not initialized");
        };

        Ok(Self {
            receiver,
            handlers: Vec::new(),
            running: false,
        })
    }

    /// Add an event handler
    pub fn add_handler(&mut self, handler: Box<dyn EventHandler + Send + Sync>) {
        self.handlers.push(handler);
    }

    /// Start monitoring events
    pub async fn start(&mut self) -> Result<()> {
        self.running = true;
        println!("🎯 Event monitor started");

        while self.running {
            match self.receiver.recv().await {
                Ok(event) => {
                    for handler in &mut self.handlers {
                        if handler.should_handle(&event) {
                            if let Err(e) = handler.handle_event(&event) {
                                eprintln!("Handler {} failed: {}", handler.name(), e);
                            }
                        }
                    }
                }
                Err(broadcast::error::RecvError::Closed) => {
                    println!("📡 Event stream closed");
                    break;
                }
                Err(broadcast::error::RecvError::Lagged(n)) => {
                    eprintln!("⚠️ Event monitor lagged by {n} events");
                }
            }
        }

        Ok(())
    }

    /// Stop monitoring events
    pub fn stop(&mut self) {
        self.running = false;
    }
}

/// Default event handlers
/// Console event handler
pub struct ConsoleEventHandler {
    /// Whether to show metadata
    show_metadata: bool,
}

impl ConsoleEventHandler {
    pub fn new(show_metadata: bool) -> Self {
        Self { show_metadata }
    }
}

impl EventHandler for ConsoleEventHandler {
    fn handle_event(&mut self, event: &Event) -> Result<()> {
        let severity_icon = match event.severity {
            EventSeverity::Trace => "🔍",
            EventSeverity::Debug => "🐛",
            EventSeverity::Info => "ℹ️",
            EventSeverity::Warn => "⚠️",
            EventSeverity::Error => "❌",
            EventSeverity::Critical => "🚨",
        };

        println!(
            "{} [{}] {}: {}",
            severity_icon, event.event_type, event.source, event.message
        );

        if self.show_metadata && !event.metadata.is_empty() {
            for (key, value) in &event.metadata {
                println!("  {key}: {value}");
            }
        }

        Ok(())
    }

    fn name(&self) -> &str {
        "console"
    }

    fn should_handle(&self, event: &Event) -> bool {
        event.severity >= EventSeverity::Info
    }
}

/// Performance event handler
pub struct PerformanceEventHandler {
    /// Performance thresholds
    thresholds: HashMap<String, u64>,
}

impl PerformanceEventHandler {
    pub fn new() -> Self {
        let mut thresholds = HashMap::new();
        thresholds.insert("slow_operation".to_string(), 1000); // 1 second
        thresholds.insert("very_slow_operation".to_string(), 5000); // 5 seconds

        Self { thresholds }
    }
}

impl EventHandler for PerformanceEventHandler {
    fn handle_event(&mut self, event: &Event) -> Result<()> {
        if let Some(duration) = event.duration_ms {
            if duration > *self.thresholds.get("very_slow_operation").unwrap_or(&5000) {
                eprintln!(
                    "🚨 Very slow operation detected: {} took {}ms",
                    event.event_type, duration
                );
            } else if duration > *self.thresholds.get("slow_operation").unwrap_or(&1000) {
                eprintln!(
                    "⚠️ Slow operation detected: {} took {}ms",
                    event.event_type, duration
                );
            }
        }
        Ok(())
    }

    fn name(&self) -> &str {
        "performance"
    }

    fn should_handle(&self, event: &Event) -> bool {
        event.category == EventCategory::Performance || event.duration_ms.is_some()
    }
}

/// Error aggregation handler
pub struct ErrorAggregationHandler {
    /// Error counts by type
    error_counts: HashMap<String, u64>,
    /// Error threshold for alerts
    error_threshold: u64,
}

impl ErrorAggregationHandler {
    pub fn new(error_threshold: u64) -> Self {
        Self {
            error_counts: HashMap::new(),
            error_threshold,
        }
    }
}

impl EventHandler for ErrorAggregationHandler {
    fn handle_event(&mut self, event: &Event) -> Result<()> {
        if event.severity >= EventSeverity::Error {
            let count = self
                .error_counts
                .entry(event.event_type.clone())
                .or_insert(0);
            *count += 1;

            if *count >= self.error_threshold {
                eprintln!(
                    "🚨 Error threshold exceeded for {}: {} errors",
                    event.event_type, count
                );
            }
        }
        Ok(())
    }

    fn name(&self) -> &str {
        "error_aggregation"
    }

    fn should_handle(&self, event: &Event) -> bool {
        event.severity >= EventSeverity::Error
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_event_creation() {
        let event = Event::new(
            EventSeverity::Info,
            EventCategory::HookStateMachine,
            "test_event".to_string(),
            "Test message".to_string(),
            "test_source".to_string(),
        );

        assert_eq!(event.severity, EventSeverity::Info);
        assert_eq!(event.category, EventCategory::HookStateMachine);
        assert_eq!(event.event_type, "test_event");
        assert_eq!(event.message, "Test message");
        assert_eq!(event.source, "test_source");
    }

    #[test]
    fn test_event_jsonl_serialization() {
        let event = Event::new(
            EventSeverity::Info,
            EventCategory::HookStateMachine,
            "test_event".to_string(),
            "Test message".to_string(),
            "test_source".to_string(),
        );

        let jsonl = event.to_jsonl().unwrap();
        assert!(jsonl.contains("test_event"));
        assert!(jsonl.contains("Test message"));
    }

    #[test]
    fn test_event_with_metadata() {
        let event = Event::new(
            EventSeverity::Info,
            EventCategory::HookStateMachine,
            "test_event".to_string(),
            "Test message".to_string(),
            "test_source".to_string(),
        )
        .with_metadata("key".to_string(), serde_json::json!("value"));

        assert_eq!(event.metadata.get("key"), Some(&serde_json::json!("value")));
    }
}
