use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;

/// GitHub Actions workflow configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitHubActionsConfig {
    pub workflow: WorkflowInfo,
    pub environment: EnvironmentConfig,
    pub permissions: HashMap<String, String>,
    pub events: EventConfig,
    pub jobs: JobConfig,
    pub output: OutputConfig,
}

/// Workflow information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowInfo {
    pub name: String,
    pub description: String,
    pub version: String,
    pub generated_by: String,
}

/// Environment configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnvironmentConfig {
    pub variables: HashMap<String, EnvironmentVariable>,
}

/// Environment variable
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnvironmentVariable {
    pub value: serde_json::Value,
    pub description: String,
}

/// Event configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventConfig {
    pub core: Vec<EventDefinition>,
    pub repository: Vec<EventDefinition>,
    pub issues_and_prs: Vec<EventDefinition>,
    pub releases_and_deployments: Vec<EventDefinition>,
    pub checks_and_status: Vec<EventDefinition>,
    pub discussions: Vec<EventDefinition>,
    pub labels_and_milestones: Vec<EventDefinition>,
    pub scheduled_and_dispatch: Vec<EventDefinition>,
    pub packages_and_protection: Vec<EventDefinition>,
}

/// Event definition
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventDefinition {
    pub name: String,
    pub description: String,
    pub hooks: Vec<String>,
    pub types: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cron: Option<String>,
}

/// Job configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobConfig {
    pub run: JobDefinition,
}

/// Job definition
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobDefinition {
    pub runs_on: String,
    pub description: String,
    pub steps: Vec<StepDefinition>,
}

/// Step definition
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StepDefinition {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uses: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub run: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub with: Option<serde_json::Value>,
}

/// Output configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutputConfig {
    pub format: String,
    pub file: String,
    pub include_header: bool,
    pub include_checksum: bool,
}

/// GitHub Actions workflow generator
pub struct GitHubActionsGenerator {
    config: GitHubActionsConfig,
}

impl GitHubActionsGenerator {
    /// Create a new generator from JSONC configuration
    pub fn from_jsonc<P: AsRef<Path>>(config_path: P) -> Result<Self> {
        let content =
            fs::read_to_string(config_path).context("Failed to read GitHub Actions config file")?;

        // Strip comments and parse JSON
        let json_content = strip_jsonc_comments(&content)?;
        let config: GitHubActionsConfig =
            serde_json::from_str(&json_content).context("Failed to parse GitHub Actions config")?;

        Ok(Self { config })
    }

    /// Generate the workflow YAML
    pub fn generate_workflow(&self) -> Result<String> {
        let mut yaml = String::new();

        // Add header comment
        if self.config.output.include_header {
            yaml.push_str("# Generated GitHub Actions Workflow\n");
            yaml.push_str(&format!(
                "# Generated by: {}\n",
                self.config.workflow.generated_by
            ));
            yaml.push_str(&format!("# Version: {}\n", self.config.workflow.version));
            yaml.push_str(&format!(
                "# Description: {}\n",
                self.config.workflow.description
            ));
            yaml.push_str("\n");
        }

        // Workflow name
        yaml.push_str(&format!("name: {}\n\n", self.config.workflow.name));

        // Environment variables
        if !self.config.environment.variables.is_empty() {
            yaml.push_str("# Environment variable to control whether validation is enabled\n");
            yaml.push_str("env:\n");
            for (key, var) in &self.config.environment.variables {
                yaml.push_str(&format!("  {}: {}\n", key, var.value));
            }
            yaml.push_str("\n");
        }

        // Permissions
        if !self.config.permissions.is_empty() {
            yaml.push_str("permissions:\n");
            for (permission, level) in &self.config.permissions {
                yaml.push_str(&format!("  {}: {}\n", permission, level));
            }
            yaml.push_str("\n");
        }

        // Events
        yaml.push_str("on:\n");

        // Add all events from all categories
        let all_events = self.collect_all_events();
        for event in all_events {
            yaml.push_str(&format!("  {}:\n", event.name));

            // Add types if specified
            if !event.types.is_empty() {
                yaml.push_str("    types:\n");
                for event_type in &event.types {
                    yaml.push_str(&format!("      - {}\n", event_type));
                }
            }

            // Add cron for schedule events
            if let Some(cron) = &event.cron {
                yaml.push_str(&format!("    - cron: '{}'\n", cron));
            }
        }

        yaml.push_str("\n");

        // Jobs
        yaml.push_str("jobs:\n");
        yaml.push_str(&format!("  {}:\n", self.config.jobs.run.runs_on));
        yaml.push_str(&format!("    runs-on: {}\n", self.config.jobs.run.runs_on));
        yaml.push_str("    steps:\n");

        // Add steps
        for step in &self.config.jobs.run.steps {
            yaml.push_str(&format!("      - name: {}\n", step.name));

            if let Some(uses) = &step.uses {
                yaml.push_str(&format!("        uses: {}\n", uses));
            }

            if let Some(run) = &step.run {
                yaml.push_str(&format!("        run: {}\n", run));
            }

            if let Some(with_config) = &step.with {
                yaml.push_str("        with:\n");
                self.serialize_with_config(with_config, &mut yaml, 10);
            }
        }

        Ok(yaml)
    }

    /// Collect all events from all categories
    fn collect_all_events(&self) -> Vec<EventDefinition> {
        let mut events = Vec::new();

        events.extend(self.config.events.core.clone());
        events.extend(self.config.events.repository.clone());
        events.extend(self.config.events.issues_and_prs.clone());
        events.extend(self.config.events.releases_and_deployments.clone());
        events.extend(self.config.events.checks_and_status.clone());
        events.extend(self.config.events.discussions.clone());
        events.extend(self.config.events.labels_and_milestones.clone());
        events.extend(self.config.events.scheduled_and_dispatch.clone());
        events.extend(self.config.events.packages_and_protection.clone());

        events
    }

    /// Serialize with configuration with proper indentation
    fn serialize_with_config(&self, config: &serde_json::Value, yaml: &mut String, indent: usize) {
        match config {
            serde_json::Value::Object(map) => {
                for (key, value) in map {
                    let indent_str = " ".repeat(indent);
                    match value {
                        serde_json::Value::String(s) => {
                            yaml.push_str(&format!("{}{}: {}\n", indent_str, key, s));
                        }
                        serde_json::Value::Number(n) => {
                            yaml.push_str(&format!("{}{}: {}\n", indent_str, key, n));
                        }
                        serde_json::Value::Bool(b) => {
                            yaml.push_str(&format!("{}{}: {}\n", indent_str, key, b));
                        }
                        serde_json::Value::Array(arr) => {
                            yaml.push_str(&format!("{}{}:\n", indent_str, key));
                            for item in arr {
                                let item_indent = " ".repeat(indent + 2);
                                yaml.push_str(&format!("{}- {}\n", item_indent, item));
                            }
                        }
                        serde_json::Value::Object(_) => {
                            yaml.push_str(&format!("{}{}:\n", indent_str, key));
                            self.serialize_with_config(value, yaml, indent + 2);
                        }
                        serde_json::Value::Null => {
                            yaml.push_str(&format!("{}{}: null\n", indent_str, key));
                        }
                    }
                }
            }
            _ => {
                let indent_str = " ".repeat(indent);
                yaml.push_str(&format!("{}{}\n", indent_str, config));
            }
        }
    }

    /// Write the generated workflow to file
    pub fn write_workflow<P: AsRef<Path>>(&self, output_path: P) -> Result<()> {
        let yaml = self.generate_workflow()?;
        fs::write(output_path, yaml).context("Failed to write GitHub Actions workflow file")?;
        Ok(())
    }
}

/// Strip JSONC comments from content
fn strip_jsonc_comments(content: &str) -> Result<String> {
    let mut result = String::new();
    let mut in_string = false;
    let mut escape_next = false;
    let mut i = 0;
    let chars: Vec<char> = content.chars().collect();

    while i < chars.len() {
        let ch = chars[i];

        if escape_next {
            result.push(ch);
            escape_next = false;
            i += 1;
            continue;
        }

        if ch == '\\' {
            escape_next = true;
            result.push(ch);
            i += 1;
            continue;
        }

        if ch == '"' && !escape_next {
            in_string = !in_string;
            result.push(ch);
            i += 1;
            continue;
        }

        if !in_string {
            // Check for single-line comment
            if ch == '/' && i + 1 < chars.len() && chars[i + 1] == '/' {
                // Skip to end of line
                while i < chars.len() && chars[i] != '\n' {
                    i += 1;
                }
                if i < chars.len() {
                    result.push('\n');
                }
                continue;
            }

            // Check for multi-line comment
            if ch == '/' && i + 1 < chars.len() && chars[i + 1] == '*' {
                // Skip to end of comment
                i += 2;
                while i < chars.len() - 1 {
                    if chars[i] == '*' && chars[i + 1] == '/' {
                        i += 2;
                        break;
                    }
                    i += 1;
                }
                continue;
            }
        }

        result.push(ch);
        i += 1;
    }

    Ok(result)
}

/// Generate GitHub Actions workflow from JSONC configuration
pub async fn generate_workflow(config_path: &str, output_path: &str, validate: bool) -> Result<()> {
    println!("🔧 Generating GitHub Actions workflow from JSONC configuration...");

    let generator = GitHubActionsGenerator::from_jsonc(config_path)?;
    generator.write_workflow(output_path)?;

    if validate {
        let yaml = generator.generate_workflow()?;
        validate_workflow_yaml(&yaml)?;
    }

    println!("✅ Generated GitHub Actions workflow: {}", output_path);
    Ok(())
}

/// Validate generated workflow YAML
fn validate_workflow_yaml(yaml: &str) -> Result<()> {
    // Basic YAML validation
    let _: serde_yaml::Value =
        serde_yaml::from_str(yaml).with_context(|| "Generated workflow YAML is invalid")?;

    // Check for required fields
    if !yaml.contains("name:") {
        anyhow::bail!("Workflow must have a name");
    }

    if !yaml.contains("on:") {
        anyhow::bail!("Workflow must have triggers");
    }

    if !yaml.contains("jobs:") {
        anyhow::bail!("Workflow must have jobs");
    }

    println!("✅ Workflow YAML validation passed");
    Ok(())
}
