// This file is auto-generated by `cargo xtask`
// Generated file: xtask/src/wasm_event_bus.rs
// Do not edit this file manually - changes will be overwritten

use anyhow::{Context, Result};
use once_cell::sync::Lazy;
use serde_json::Value;
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use crate::event_bus::{EventBus, EventBusConfig, HooksmithEvent};

/// WASM component handler registration (simplified for now)
pub struct WasmComponentHandler {
    /// Component name
    pub name: String,
    /// Component path
    pub component_path: PathBuf,
    /// Supported event types
    pub supported_events: Vec<String>,
    /// Supported event categories
    pub supported_categories: Vec<String>,
    /// Handler ID
    pub handler_id: u32,
}

/// WASM event bus host implementation (simplified)
pub struct WasmEventBusHost {
    /// Event bus instance
    event_bus: Arc<Mutex<EventBus>>,
    /// Registered WASM component handlers
    handlers: Arc<Mutex<HashMap<u32, WasmComponentHandler>>>,
    /// Next handler ID
    next_handler_id: Arc<Mutex<u32>>,
}

impl WasmEventBusHost {
    /// Create a new WASM event bus host
    pub fn new(event_bus_config: EventBusConfig) -> Result<Self> {
        let event_bus = Arc::new(Mutex::new(EventBus::new(event_bus_config)?));
        let handlers = Arc::new(Mutex::new(HashMap::new()));
        let next_handler_id = Arc::new(Mutex::new(1));

        Ok(Self {
            event_bus,
            handlers,
            next_handler_id,
        })
    }

    /// Load and register a WASM component (simplified)
    pub async fn load_component(&self, component_path: &PathBuf) -> Result<u32> {
        println!("🔧 Loading WASM component: {}", component_path.display());

        if !component_path.exists() {
            anyhow::bail!("Component file not found: {}", component_path.display());
        }

        // Get component metadata (simplified for now)
        let metadata = self.get_component_metadata(component_path)?;
        println!("📦 Component: {} v{}", metadata.name, metadata.version);
        println!("   Description: {}", metadata.description);
        println!("   Supported events: {:?}", metadata.supported_events);
        println!(
            "   Supported categories: {:?}",
            metadata.supported_categories
        );

        // Register the handler
        let handler_id = {
            let mut id = self.next_handler_id.lock().unwrap();
            let current_id = *id;
            *id += 1;
            current_id
        };

        let handler = WasmComponentHandler {
            name: metadata.name.clone(),
            component_path: component_path.clone(),
            supported_events: metadata.supported_events,
            supported_categories: metadata.supported_categories,
            handler_id,
        };

        {
            let mut handlers = self.handlers.lock().unwrap();
            handlers.insert(handler_id, handler);
        }

        println!("✅ Component registered with handler ID: {handler_id}");

        Ok(handler_id)
    }

    /// Unregister a WASM component handler
    pub fn unregister_handler(&self, handler_id: u32) -> Result<()> {
        let mut handlers = self.handlers.lock().unwrap();
        if handlers.remove(&handler_id).is_some() {
            println!("🗑️ Unregistered handler: {handler_id}");
            Ok(())
        } else {
            anyhow::bail!("Handler not found: {}", handler_id)
        }
    }

    /// Emit an event to all registered WASM handlers (simplified)
    pub async fn emit_event(&self, event: HooksmithEvent) -> Result<()> {
        // First, emit to the main event bus
        {
            let mut event_bus = self.event_bus.lock().unwrap();
            event_bus.emit(event.clone())?;
        }

        // Then, dispatch to WASM components (simplified for now)
        let handlers = self.handlers.lock().unwrap();

        for (_handler_id, handler) in handlers.iter() {
            // Check if handler supports this event type
            if !handler.supported_events.is_empty()
                && !handler.supported_events.contains(&event.event)
            {
                continue;
            }

            // For now, just log that the component would handle this event
            println!(
                "📡 WASM component {} would handle event: {}",
                handler.name, event.event
            );
        }

        Ok(())
    }

    /// Get event bus statistics
    pub fn get_stats(&self) -> Result<Value> {
        let event_bus = self.event_bus.lock().unwrap();
        let stats = event_bus.get_stats()?;
        let handlers = self.handlers.lock().unwrap();

        let wasm_stats = serde_json::json!({
            "total_events": stats.total_events,
            "events_by_actor": stats.events_by_actor,
            "events_by_type": stats.events_by_type,
            "events_by_hook": stats.events_by_hook,
            "active_wasm_handlers": handlers.len(),
            "wasm_handlers": handlers.keys().collect::<Vec<_>>()
        });

        Ok(wasm_stats)
    }

    /// Get component metadata from WASM component (simplified)
    fn get_component_metadata(&self, component_path: &PathBuf) -> Result<ComponentMetadata> {
        // This would use the actual WIT bindings
        // For now, return mock metadata based on filename
        let name = component_path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("unknown-component")
            .to_string();

        Ok(ComponentMetadata {
            name,
            version: "1.0.0".to_string(),
            description: "Mock WASM component".to_string(),
            supported_events: vec![
                "validation_passed".to_string(),
                "validation_failed".to_string(),
                "validation_started".to_string(),
            ],
            supported_categories: vec!["validation".to_string()],
        })
    }

    /// Convert HooksmithEvent to WIT format
    fn convert_to_wit_event(&self, event: &HooksmithEvent) -> Result<WitHooksmithEvent> {
        Ok(WitHooksmithEvent {
            id: event.id.clone(),
            ts: event.ts.to_rfc3339(),
            actor: event.actor.clone(),
            event: event.event.clone(),
            hook: event.hook.clone(),
            state: event.state.clone(),
            context: serde_json::to_string(&event.context)?,
            error: event
                .error
                .as_ref()
                .and_then(|e| serde_json::to_string(e).ok()),
            session_id: event.session_id.clone(),
            duration_ms: event.duration_ms,
        })
    }

    /// Call WASM event handler

    /// List all registered WASM components
    pub fn list_components(&self) -> Result<Vec<ComponentInfo>> {
        let handlers = self.handlers.lock().unwrap();
        let components: Vec<ComponentInfo> = handlers
            .values()
            .map(|handler| ComponentInfo {
                id: handler.handler_id,
                name: handler.name.clone(),
                supported_events: handler.supported_events.clone(),
                supported_categories: handler.supported_categories.clone(),
            })
            .collect();

        Ok(components)
    }
}

/// Component metadata structure
#[derive(Debug)]
struct ComponentMetadata {
    name: String,
    version: String,
    description: String,
    supported_events: Vec<String>,
    supported_categories: Vec<String>,
}

/// WIT event structure (simplified for now)
#[derive(Debug)]
struct WitHooksmithEvent {
    id: String,
    ts: String,
    actor: String,
    event: String,
    hook: Option<String>,
    state: Option<String>,
    context: String,
    error: Option<String>,
    session_id: Option<String>,
    duration_ms: Option<u64>,
}

/// WIT event handler result (simplified for now)
#[derive(Debug)]
struct WitEventHandlerResult {
    success: bool,
    error: Option<String>,
    response: Option<String>,
}

/// Component information for listing
#[derive(Debug, serde::Serialize)]
pub struct ComponentInfo {
    pub id: u32,
    pub name: String,
    pub supported_events: Vec<String>,
    pub supported_categories: Vec<String>,
}

/// Global WASM event bus host instance
static WASM_EVENT_BUS_HOST: Lazy<Mutex<Option<Arc<WasmEventBusHost>>>> =
    Lazy::new(|| Mutex::new(None));

/// Initialize the global WASM event bus host
pub fn init_wasm_event_bus_host(config: EventBusConfig) -> Result<()> {
    let host = WasmEventBusHost::new(config)?;
    let mut guard = WASM_EVENT_BUS_HOST.lock().unwrap();
    *guard = Some(Arc::new(host));
    Ok(())
}

/// Get the global WASM event bus host
pub fn get_wasm_event_bus_host() -> Option<Arc<WasmEventBusHost>> {
    WASM_EVENT_BUS_HOST.lock().unwrap().clone()
}

/// Load a WASM component
pub async fn load_wasm_component(component_path: &PathBuf) -> Result<u32> {
    if let Some(host) = get_wasm_event_bus_host() {
        host.load_component(component_path).await
    } else {
        anyhow::bail!("WASM event bus host not initialized")
    }
}

/// Unregister a WASM component handler
pub fn unregister_wasm_handler(handler_id: u32) -> Result<()> {
    if let Some(host) = get_wasm_event_bus_host() {
        host.unregister_handler(handler_id)
    } else {
        anyhow::bail!("WASM event bus host not initialized")
    }
}

/// Emit event to WASM components
pub async fn emit_event_to_wasm(event: HooksmithEvent) -> Result<()> {
    if let Some(host) = get_wasm_event_bus_host() {
        host.emit_event(event).await
    } else {
        anyhow::bail!("WASM event bus host not initialized")
    }
}

/// Get WASM event bus statistics
pub fn get_wasm_event_bus_stats() -> Result<Value> {
    if let Some(host) = get_wasm_event_bus_host() {
        host.get_stats()
    } else {
        anyhow::bail!("WASM event bus host not initialized")
    }
}

/// List WASM components
pub fn list_wasm_components() -> Result<Vec<ComponentInfo>> {
    if let Some(host) = get_wasm_event_bus_host() {
        host.list_components()
    } else {
        anyhow::bail!("WASM event bus host not initialized")
    }
}

/// Example WASM component implementation
pub mod example_component {
    use super::*;

    /// Example validation component
    pub struct ValidationComponent {
        /// Component configuration
        config: Value,
        /// Validation rules
        rules: Vec<String>,
    }

    impl ValidationComponent {
        /// Create a new validation component
        pub fn new(config: Value) -> Self {
            let rules = config
                .get("rules")
                .and_then(|r| r.as_array())
                .map(|arr| {
                    arr.iter()
                        .filter_map(|v| v.as_str().map(|s| s.to_string()))
                        .collect()
                })
                .unwrap_or_default();

            Self { config, rules }
        }

        /// Handle validation events
        pub fn handle_validation_event(&self, event: &HooksmithEvent) -> Result<bool> {
            match event.event.as_str() {
                "validation_started" => {
                    println!("🔍 Validation started by: {}", event.actor);
                    Ok(true)
                }
                "validation_passed" => {
                    println!("✅ Validation passed for: {}", event.actor);
                    Ok(true)
                }
                "validation_failed" => {
                    println!("❌ Validation failed for: {}", event.actor);
                    if let Some(error) = &event.error {
                        println!("   Error: {error}");
                    }
                    Ok(false)
                }
                _ => Ok(true),
            }
        }

        /// Get component metadata
        pub fn get_metadata(&self) -> ComponentMetadata {
            ComponentMetadata {
                name: "validation-component".to_string(),
                version: "1.0.0".to_string(),
                description: "Validates events and provides feedback".to_string(),
                supported_events: vec![
                    "validation_started".to_string(),
                    "validation_passed".to_string(),
                    "validation_failed".to_string(),
                ],
                supported_categories: vec!["validation".to_string()],
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_wasm_event_bus_host_creation() {
        let config = EventBusConfig::default();
        let host = WasmEventBusHost::new(config);
        assert!(host.is_ok());
    }

    #[test]
    fn test_component_metadata() {
        let metadata = ComponentMetadata {
            name: "test-component".to_string(),
            version: "1.0.0".to_string(),
            description: "Test component".to_string(),
            supported_events: vec!["test_event".to_string()],
            supported_categories: vec!["test".to_string()],
        };

        assert_eq!(metadata.name, "test-component");
        assert_eq!(metadata.version, "1.0.0");
        assert_eq!(metadata.supported_events.len(), 1);
    }
}
