// GENERATED FILE - DO NOT EDIT
// This file is automatically generated by xtask
// To modify this file, update the source and regenerate

// GENERATED FILE - DO NOT EDIT
// This file is automatically generated by xtask
// To modify this file, update the source and regenerate

// GENERATED FILE - DO NOT EDIT
// This file is automatically generated by xtask
// To modify this file, update the source and regenerate

//! modules module
//!
//! This module contains modules functionality.
//! Auto-generated by xtask gen-mods

/// Contract State Machine functionality
pub mod contract_state_machine;
/// Contract Validation functionality
pub mod contract_validation;
/// Generator functionality
pub mod generator;
/// Git Model functionality
pub mod git_model;
/// Hierarchical Validation functionality
pub mod hierarchical_validation;
/// Hook Builder functionality
pub mod hook_builder;
/// Lefthook functionality
pub mod lefthook;
/// Wasm functionality
pub mod wasm;
