// GENERATED FILE - DO NOT EDIT
// This file is automatically generated by xtask
// To modify this file, update the source and regenerate

// GENERATED FILE - DO NOT EDIT
// This file is automatically generated by xtask
// To modify this file, update the source and regenerate

//! commands module
//!
//! This module contains commands functionality.
//! Auto-generated by xtask gen-mods

/// Contract Validation functionality
pub mod contract_validation;
