// This file is auto-generated by `cargo xtask`
// Generated file: components/validation-handler/src/lib.rs
// Do not edit this file manually - changes will be overwritten
//!
//! Validation Handler Component
//!
//! This component implements the WIT interface for validation operations.

#[cfg(feature = "host")]
wit_bindgen::generate!({
    path: "../wit/validation-handler.wit",
    world: "validation-handler",
});

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Event severity levels
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum EventSeverity {
    Trace,
    Debug,
    Info,
    Warn,
    Error,
    Critical,
}

/// Event categories
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum EventCategory {
    HookStateMachine,
    Git,
    Validation,
    Build,
    Contract,
    File,
    System,
    User,
    Performance,
    Security,
}

/// Hooksmith event structure
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HooksmithEvent {
    pub id: String,
    pub ts: String,
    pub actor: String,
    pub event: String,
    pub hook: Option<String>,
    pub state: Option<String>,
    pub context: String,
    pub error: Option<String>,
    pub session_id: Option<String>,
    pub duration_ms: Option<u64>,
}

/// Event handler result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventHandlerResult {
    pub success: bool,
    pub error: Option<String>,
    pub response: Option<String>,
}

/// Component metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComponentMetadata {
    pub name: String,
    pub version: String,
    pub description: String,
    pub supported_events: Vec<String>,
    pub supported_categories: Vec<EventCategory>,
}

/// Validation handler component
pub struct ValidationHandler {
    /// Component configuration
    config: Value,
    /// Validation rules
    rules: Vec<String>,
    /// Validation statistics
    stats: ValidationStats,
}

/// Validation statistics
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidationStats {
    pub total_validations: u64,
    pub passed_validations: u64,
    pub failed_validations: u64,
    pub last_validation_time: Option<String>,
}

impl ValidationHandler {
    /// Create a new validation handler
    pub fn new(config: Value) -> Self {
        let rules = config
            .get("rules")
            .and_then(|r| r.as_array())
            .map(|arr| {
                arr.iter()
                    .filter_map(|v| v.as_str().map(|s| s.to_string()))
                    .collect()
            })
            .unwrap_or_default();

        Self {
            config,
            rules,
            stats: ValidationStats {
                total_validations: 0,
                passed_validations: 0,
                failed_validations: 0,
                last_validation_time: None,
            },
        }
    }

    /// Handle an event
    pub fn handle_event(&mut self, event: &HooksmithEvent) -> EventHandlerResult {
        match event.event.as_str() {
            "validation_started" => self.handle_validation_started(event),
            "validation_passed" => self.handle_validation_passed(event),
            "validation_failed" => self.handle_validation_failed(event),
            "commit_created" => self.handle_commit_created(event),
            "push_attempted" => self.handle_push_attempted(event),
            _ => EventHandlerResult {
                success: true,
                error: None,
                response: Some(format!("Event '{}' not handled by validation component", event.event)),
            },
        }
    }

    /// Handle validation started event
    fn handle_validation_started(&mut self, event: &HooksmithEvent) -> EventHandlerResult {
        self.stats.total_validations += 1;
        self.stats.last_validation_time = Some(event.ts.clone());

        let response = serde_json::json!({
            "component": "validation-handler",
            "action": "validation_started",
            "actor": event.actor,
            "hook": event.hook,
            "rules_count": self.rules.len(),
            "timestamp": event.ts
        });

        EventHandlerResult {
            success: true,
            error: None,
            response: Some(response.to_string()),
        }
    }

    /// Handle validation passed event
    fn handle_validation_passed(&mut self, event: &HooksmithEvent) -> EventHandlerResult {
        self.stats.passed_validations += 1;

        let context: Value = serde_json::from_str(&event.context).unwrap_or_default();
        let empty_vec = Vec::new();
        let files = context.get("files").and_then(|f| f.as_array()).unwrap_or(&empty_vec);

        let response = serde_json::json!({
            "component": "validation-handler",
            "action": "validation_passed",
            "actor": event.actor,
            "hook": event.hook,
            "files_validated": files.len(),
            "stats": {
                "total": self.stats.total_validations,
                "passed": self.stats.passed_validations,
                "failed": self.stats.failed_validations
            }
        });

        EventHandlerResult {
            success: true,
            error: None,
            response: Some(response.to_string()),
        }
    }

    /// Handle validation failed event
    fn handle_validation_failed(&mut self, event: &HooksmithEvent) -> EventHandlerResult {
        self.stats.failed_validations += 1;

        let error_details = if let Some(error) = &event.error {
            serde_json::from_str::<Value>(error).unwrap_or_default()
        } else {
            Value::Null
        };

        let response = serde_json::json!({
            "component": "validation-handler",
            "action": "validation_failed",
            "actor": event.actor,
            "hook": event.hook,
            "error": error_details,
            "stats": {
                "total": self.stats.total_validations,
                "passed": self.stats.passed_validations,
                "failed": self.stats.failed_validations
            }
        });

        EventHandlerResult {
            success: false,
            error: Some(format!("Validation failed for actor: {}", event.actor)),
            response: Some(response.to_string()),
        }
    }

    /// Handle commit created event
    fn handle_commit_created(&mut self, event: &HooksmithEvent) -> EventHandlerResult {
        let context: Value = serde_json::from_str(&event.context).unwrap_or_default();
        let commit_hash = context.get("commit_hash").and_then(|h| h.as_str()).unwrap_or("unknown");
        let message = context.get("message").and_then(|m| m.as_str()).unwrap_or("no message");

        let response = serde_json::json!({
            "component": "validation-handler",
            "action": "commit_created",
            "actor": event.actor,
            "commit_hash": commit_hash,
            "message": message,
            "validation_status": if self.stats.failed_validations == 0 {
                "ready_for_push"
            } else {
                "validation_failed"
            }
        });

        EventHandlerResult {
            success: true,
            error: None,
            response: Some(response.to_string()),
        }
    }

    /// Handle push attempted event
    fn handle_push_attempted(&mut self, event: &HooksmithEvent) -> EventHandlerResult {
        let context: Value = serde_json::from_str(&event.context).unwrap_or_default();
        let branch = context.get("branch").and_then(|b| b.as_str()).unwrap_or("unknown");

        let response = serde_json::json!({
            "component": "validation-handler",
            "action": "push_attempted",
            "actor": event.actor,
            "branch": branch,
            "validation_summary": {
                "total_validations": self.stats.total_validations,
                "passed_validations": self.stats.passed_validations,
                "failed_validations": self.stats.failed_validations,
                "success_rate": if self.stats.total_validations > 0 {
                    (self.stats.passed_validations as f64 / self.stats.total_validations as f64) * 100.0
                } else {
                    0.0
                }
            }
        });

        EventHandlerResult {
            success: true,
            error: None,
            response: Some(response.to_string()),
        }
    }

    /// Get component metadata
    pub fn get_metadata(&self) -> ComponentMetadata {
        ComponentMetadata {
            name: "validation-handler".to_string(),
            version: "1.0.0".to_string(),
            description: "Handles validation events and provides feedback".to_string(),
            supported_events: vec![
                "validation_started".to_string(),
                "validation_passed".to_string(),
                "validation_failed".to_string(),
                "commit_created".to_string(),
                "push_attempted".to_string(),
            ],
            supported_categories: vec![
                EventCategory::Validation,
                EventCategory::Git,
                EventCategory::HookStateMachine,
            ],
        }
    }

    /// Get validation statistics
    pub fn get_stats(&self) -> &ValidationStats {
        &self.stats
    }

    /// Get component configuration
    pub fn get_config(&self) -> &Value {
        &self.config
    }

    /// Get validation rules
    pub fn get_rules(&self) -> &[String] {
        &self.rules
    }
}

/// Initialize the component
pub fn init(config: Value) -> Result<ValidationHandler, String> {
    Ok(ValidationHandler::new(config))
}

/// Handle an event (main entry point for WASM)
pub fn handle_event(handler: &mut ValidationHandler, event: &HooksmithEvent) -> EventHandlerResult {
    handler.handle_event(event)
}

/// Get component metadata (main entry point for WASM)
pub fn get_metadata(handler: &ValidationHandler) -> ComponentMetadata {
    handler.get_metadata()
}

/// Get validation statistics
pub fn get_stats(handler: &ValidationHandler) -> ValidationStats {
    handler.get_stats().clone()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_validation_handler_creation() {
        let config = serde_json::json!({
            "rules": ["rule1", "rule2", "rule3"]
        });

        let handler = ValidationHandler::new(config);
        assert_eq!(handler.rules.len(), 3);
        assert_eq!(handler.stats.total_validations, 0);
    }

    #[test]
    fn test_validation_started_event() {
        let config = serde_json::json!({});
        let mut handler = ValidationHandler::new(config);

        let event = HooksmithEvent {
            id: "test-1".to_string(),
            ts: "2025-08-03T16:00:00Z".to_string(),
            actor: "test-actor".to_string(),
            event: "validation_started".to_string(),
            hook: Some("pre-commit".to_string()),
            state: Some("validating".to_string()),
            context: "{}".to_string(),
            error: None,
            session_id: Some("session-1".to_string()),
            duration_ms: None,
        };

        let result = handler.handle_event(&event);
        assert!(result.success);
        assert_eq!(handler.stats.total_validations, 1);
    }

    #[test]
    fn test_validation_passed_event() {
        let config = serde_json::json!({});
        let mut handler = ValidationHandler::new(config);

        let event = HooksmithEvent {
            id: "test-2".to_string(),
            ts: "2025-08-03T16:00:00Z".to_string(),
            actor: "test-actor".to_string(),
            event: "validation_passed".to_string(),
            hook: Some("pre-commit".to_string()),
            state: Some("validating".to_string()),
            context: serde_json::json!({
                "files": ["src/main.rs", "src/lib.rs"]
            }).to_string(),
            error: None,
            session_id: Some("session-1".to_string()),
            duration_ms: Some(1500),
        };

        let result = handler.handle_event(&event);
        assert!(result.success);
        assert_eq!(handler.stats.passed_validations, 1);
    }

    #[test]
    fn test_validation_failed_event() {
        let config = serde_json::json!({});
        let mut handler = ValidationHandler::new(config);

        let event = HooksmithEvent {
            id: "test-3".to_string(),
            ts: "2025-08-03T16:00:00Z".to_string(),
            actor: "test-actor".to_string(),
            event: "validation_failed".to_string(),
            hook: Some("pre-commit".to_string()),
            state: Some("validating".to_string()),
            context: "{}".to_string(),
            error: Some(serde_json::json!({
                "message": "Validation failed",
                "details": "Some validation details"
            }).to_string()),
            session_id: Some("session-1".to_string()),
            duration_ms: Some(2000),
        };

        let result = handler.handle_event(&event);
        assert!(!result.success);
        assert_eq!(handler.stats.failed_validations, 1);
        assert!(result.error.is_some());
    }

    #[test]
    fn test_component_metadata() {
        let config = serde_json::json!({});
        let handler = ValidationHandler::new(config);
        let metadata = handler.get_metadata();

        assert_eq!(metadata.name, "validation-handler");
        assert_eq!(metadata.version, "1.0.0");
        assert_eq!(metadata.supported_events.len(), 5);
        assert_eq!(metadata.supported_categories.len(), 3);
    }
}

/// Validation Handler Component Implementation
#[cfg(feature = "host")]
struct ValidationHandlerComponent;

#[cfg(feature = "host")]
impl validation_handler::ValidationHandler for ValidationHandlerComponent {
    fn validate(
        content: String,
        config: validation_handler::ValidationConfig,
    ) -> Result<validation_handler::ValidationResult, String> {
        // Implementation using existing validation logic
        let mut handler = ValidationHandler::new(serde_json::json!({}));
        
        // Convert WIT config to internal format
        let rules: Vec<String> = config.rules.iter().map(|r| r.name.clone()).collect();
        
        // Perform validation
        let mut error_count = 0;
        let mut warning_count = 0;
        let mut messages = Vec::new();
        
        for rule in &config.rules {
            if rule.enabled {
                // Simple validation logic - in real implementation, apply actual rules
                if content.contains(&rule.name) {
                    messages.push(format!("Rule '{}' applied", rule.name));
                } else {
                    if config.strict {
                        error_count += 1;
                        messages.push(format!("Rule '{}' failed", rule.name));
                    } else {
                        warning_count += 1;
                        messages.push(format!("Rule '{}' warning", rule.name));
                    }
                }
            }
        }
        
        Ok(validation_handler::ValidationResult {
            success: error_count == 0,
            error_count,
            warning_count,
            messages,
            details: Some(format!("Validated content with {} rules", config.rules.len())),
        })
    }

    fn validate_file(
        file_path: String,
        config: validation_handler::ValidationConfig,
    ) -> Result<validation_handler::ValidationResult, String> {
        // Implementation for file validation
        // In a real implementation, read the file and validate its content
        let content = format!("File content from {}", file_path);
        Self::validate(content, config)
    }

    fn is_valid(content: String, rule_name: String) -> Result<bool, String> {
        // Simple validation check
        Ok(content.contains(&rule_name))
    }

    fn get_rules() -> Result<Vec<validation_handler::ValidationRule>, String> {
        // Return default validation rules
        Ok(vec![
            validation_handler::ValidationRule {
                name: "basic-validation".to_string(),
                description: "Basic content validation".to_string(),
                severity: validation_handler::ValidationSeverity::Info,
                enabled: true,
                params: vec![],
            },
            validation_handler::ValidationRule {
                name: "strict-validation".to_string(),
                description: "Strict content validation".to_string(),
                severity: validation_handler::ValidationSeverity::Error,
                enabled: true,
                params: vec!["strict".to_string()],
            },
        ])
    }

    fn add_rule(rule: validation_handler::ValidationRule) -> Result<bool, String> {
        // In a real implementation, add the rule to the rule set
        Ok(true)
    }
}

#[cfg(feature = "host")]
export_validation_handler!(ValidationHandlerComponent); 
