//! Example demonstrating generated file validation
//!
//! This example shows how to use the generated file validation system
//! to prevent manual modifications to files that are automatically generated.

use std::process::Command;

/// Simple implementation of generated file validation
struct GeneratedFileValidator;

impl GeneratedFileValidator {
    /// Check if a file is marked as generated in .gitattributes
    fn is_file_generated(file_path: &str) -> Result<bool, String> {
        let output = Command::new("git")
            .args(["check-attr", "generated", "--", file_path])
            .output()
            .map_err(|e| format!("Failed to run git check-attr: {}", e))?;

        if !output.status.success() {
            return Err(format!(
                "Git check-attr failed: {}",
                String::from_utf8_lossy(&output.stderr)
            ));
        }

        let output_str = String::from_utf8_lossy(&output.stdout);
        Ok(output_str.contains("true"))
    }

    /// Get list of changed files (staged or unstaged)
    fn get_changed_files(staged_only: bool) -> Result<Vec<String>, String> {
        let args = if staged_only {
            vec!["diff", "--cached", "--name-only"]
        } else {
            vec!["diff", "--name-only"]
        };

        let output = Command::new("git")
            .args(&args)
            .output()
            .map_err(|e| format!("Failed to run git diff: {}", e))?;

        if !output.status.success() {
            return Err(format!(
                "Git diff failed: {}",
                String::from_utf8_lossy(&output.stderr)
            ));
        }

        let files = String::from_utf8_lossy(&output.stdout)
            .lines()
            .filter(|line| !line.trim().is_empty())
            .map(|s| s.to_string())
            .collect();

        Ok(files)
    }

    /// Validate that no generated files have been manually modified
    fn validate_generated_files(staged_only: bool, strict: bool) -> Result<(), String> {
        println!("🔍 Validating generated files...");

        let changed_files = Self::get_changed_files(staged_only)?;
        let mut generated_files = Vec::new();

        for file in &changed_files {
            if Self::is_file_generated(file)? {
                generated_files.push(file.clone());
            }
        }

        if generated_files.is_empty() {
            println!("✅ All generated files are valid!");
            return Ok(());
        }

        let error_message = Self::format_error_message(&generated_files);
        println!("❌ {}", error_message);

        if strict {
            return Err(error_message);
        }

        Ok(())
    }

    /// Format a user-friendly error message
    fn format_error_message(modified_files: &[String]) -> String {
        let mut message = String::new();
        message
            .push_str("The following files are generated and should not be manually modified:\n\n");

        for file in modified_files {
            message.push_str(&format!("  • {}\n", file));
        }

        message.push_str("\n✅ Instead, regenerate them by running:\n\n");
        message.push_str("  ./xtask gen-all\n\n");
        message.push_str("Or use specific generation commands:\n");
        message.push_str("  ./xtask gen-lefthook    # for lefthook.yml\n");
        message.push_str("  ./xtask gen-docs        # for documentation\n");
        message.push_str("  ./xtask gen-mods        # for module files\n");
        message.push_str("  ./xtask gen-wit         # for WIT interfaces\n");

        message
    }

    /// Add generated file headers to files
    fn add_generated_header(file_path: &str) -> Result<(), String> {
        use std::fs;

        let content = fs::read_to_string(file_path)
            .map_err(|e| format!("Failed to read file {}: {}", file_path, e))?;

        // Check if header already exists
        if content.starts_with("# GENERATED FILE - DO NOT EDIT") {
            println!("✅ File {} already has generated header", file_path);
            return Ok(());
        }

        let header = "# GENERATED FILE - DO NOT EDIT\n# This file is automatically generated by xtask\n# To modify this file, update the source and regenerate\n\n";
        let new_content = format!("{}{}", header, content);

        fs::write(file_path, new_content)
            .map_err(|e| format!("Failed to write file {}: {}", file_path, e))?;

        println!("✅ Added generated header to {}", file_path);
        Ok(())
    }

    /// Check if a file has a generated header
    fn has_generated_header(file_path: &str) -> Result<bool, String> {
        use std::fs;

        let content = fs::read_to_string(file_path)
            .map_err(|e| format!("Failed to read file {}: {}", file_path, e))?;

        Ok(content.starts_with("# GENERATED FILE - DO NOT EDIT"))
    }
}

fn main() {
    println!("🚀 Generated File Validation Demo");
    println!("================================\n");

    // Example 1: Validate staged files
    println!("1. Validating staged files...");
    match GeneratedFileValidator::validate_generated_files(true, false) {
        Ok(()) => println!("✅ Validation passed"),
        Err(e) => println!("❌ Validation failed: {}", e),
    }

    println!();

    // Example 2: Validate all changes
    println!("2. Validating all changes...");
    match GeneratedFileValidator::validate_generated_files(false, false) {
        Ok(()) => println!("✅ Validation passed"),
        Err(e) => println!("❌ Validation failed: {}", e),
    }

    println!();

    // Example 3: Check specific files
    println!("3. Checking specific files...");
    let test_files = vec![
        "lefthook.yml",
        "docs/GENERATED_FILE_VALIDATION.md",
        "src/main.rs",
    ];

    for file in test_files {
        match GeneratedFileValidator::is_file_generated(file) {
            Ok(is_generated) => {
                if is_generated {
                    println!("  • {}: 🔒 Generated file", file);

                    // Check if it has a header
                    match GeneratedFileValidator::has_generated_header(file) {
                        Ok(has_header) => {
                            if has_header {
                                println!("    ✅ Has generated header");
                            } else {
                                println!("    ⚠️  Missing generated header");
                            }
                        }
                        Err(e) => println!("    ❌ Error checking header: {}", e),
                    }
                } else {
                    println!("  • {}: 📝 Regular file", file);
                }
            }
            Err(e) => println!("  • {}: ❌ Error: {}", file, e),
        }
    }

    println!();

    // Example 4: Add headers to generated files
    println!("4. Adding headers to generated files...");
    let generated_files = vec!["lefthook.yml", "docs/GENERATED_FILE_VALIDATION.md"];

    for file in generated_files {
        if let Ok(is_generated) = GeneratedFileValidator::is_file_generated(file) {
            if is_generated {
                match GeneratedFileValidator::add_generated_header(file) {
                    Ok(()) => println!("  ✅ Added header to {}", file),
                    Err(e) => println!("  ❌ Failed to add header to {}: {}", file, e),
                }
            }
        }
    }

    println!();

    // Example 5: Show .gitattributes content
    println!("5. Current .gitattributes configuration:");
    match std::fs::read_to_string(".gitattributes") {
        Ok(content) => {
            for line in content.lines() {
                if line.contains("generated=true") {
                    println!("  {}", line);
                }
            }
        }
        Err(e) => println!("  ❌ Failed to read .gitattributes: {}", e),
    }

    println!();
    println!("🎉 Demo completed!");
    println!();
    println!("📚 Next steps:");
    println!("  1. Add more files to .gitattributes with generated=true");
    println!("  2. Run validation in your CI/CD pipeline");
    println!("  3. Integrate with your pre-commit hooks");
    println!("  4. Use the full xtask implementation for production");
}
