use std::fs;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("🧪 Testing Codegen Markers and Git Linguist Integration");
    println!("=======================================================");
    println!("");

    // Test CLI help generation with codegen markers
    println!("📝 Testing CLI Help Generation with Codegen Markers...");
    let cli_help = generate_test_cli_help_with_markers()?;
    fs::write("test_cli_help_with_markers.md", cli_help)?;
    println!("✅ CLI help with codegen markers generated");

    // Test structure generation with codegen markers
    println!("📁 Testing Structure Generation with Codegen Markers...");
    let structure = generate_test_structure_with_markers()?;
    fs::write("test_structure_with_markers.md", structure)?;
    println!("✅ Structure with codegen markers generated");

    // Test examples generation with codegen markers
    println!("📚 Testing Examples Generation with Codegen Markers...");
    let examples = generate_test_examples_with_markers()?;
    fs::write("test_examples_with_markers.md", examples)?;
    println!("✅ Examples with codegen markers generated");

    // Test component docs generation with codegen markers
    println!("🧩 Testing Component Docs Generation with Codegen Markers...");
    let component_docs = generate_test_component_docs_with_markers()?;
    fs::write("test_component_docs_with_markers.md", component_docs)?;
    println!("✅ Component docs with codegen markers generated");

    println!("");
    println!("📄 Generated Files with Codegen Markers:");
    println!("========================================");

    let files = vec![
        "test_cli_help_with_markers.md",
        "test_structure_with_markers.md",
        "test_examples_with_markers.md",
        "test_component_docs_with_markers.md",
    ];

    for file in files {
        println!("");
        println!("📄 {}", file);
        println!("{}", "=".repeat(file.len() + 3));

        let content = fs::read_to_string(file)?;
        let lines: Vec<&str> = content.lines().take(10).collect();

        for line in lines {
            println!("{}", line);
        }

        if content.lines().count() > 10 {
            println!("...");
        }
    }

    println!("");
    println!("🏷️  Git Linguist Integration");
    println!("============================");
    println!("");
    println!("The .gitattributes file includes linguist-generated=true for all generated files:");
    println!("");
    println!("docs/*.md        codegen linguist-generated=true");
    println!("components/*/README.md codegen linguist-generated=true");
    println!("STRUCTURE.md     codegen linguist-generated=true");
    println!("");
    println!("This tells GitHub to:");
    println!("✅ Hide generated files from language statistics");
    println!("✅ Skip generated files in pull request diffs");
    println!("✅ Mark files as 'generated' in the UI");
    println!("✅ Prevent manual editing warnings");
    println!("");

    println!("🔍 Codegen Marker Features");
    println!("==========================");
    println!("");
    println!("Each generated file includes:");
    println!("✅ HTML comment markers at the top");
    println!("✅ Clear 'auto-generated' indicators");
    println!("✅ File path identification");
    println!("✅ 'Do not edit manually' warnings");
    println!("✅ Footer markers with generation info");
    println!("");

    println!("🎉 All tests passed!");
    println!("The codegen marker system is working correctly.");
    println!("");
    println!("Next steps:");
    println!("1. Run: cargo xtask gen-docs-comprehensive --all --validate");
    println!("2. Check that all generated files have proper markers");
    println!("3. Verify Git linguist integration works on GitHub");
    println!("");

    Ok(())
}

fn generate_test_cli_help_with_markers() -> Result<String, Box<dyn std::error::Error>> {
    let mut content = String::new();

    // Add codegen markers (this would be done by the main system)
    content
        .push_str("<!-- This file is auto-generated by `cargo xtask gen-docs-comprehensive` -->\n");
    content.push_str("<!-- Generated file: docs/CLI_HELP.md -->\n");
    content.push_str("<!-- Do not edit this file manually - changes will be overwritten -->\n\n");

    content.push_str("# CLI Help Documentation\n\n");
    content.push_str("This document contains the help output for all CLI commands.\n\n");
    content.push_str("## Main Help\n");
    content.push_str("```\n");
    content.push_str("hooksmith 0.1.0\n");
    content.push_str("A CLI tool for building Rust binaries into Lefthook hooks\n\n");
    content.push_str("USAGE:\n");
    content.push_str("    hooksmith <SUBCOMMAND>\n\n");
    content.push_str("OPTIONS:\n");
    content.push_str("    -h, --help    Print help information\n");
    content.push_str("    -V, --version Print version information\n\n");
    content.push_str("SUBCOMMANDS:\n");
    content.push_str("    build     Build Rust binaries for Git hooks\n");
    content.push_str("    generate  Generate Lefthook configuration\n");
    content.push_str("    help      Print this message or the help of the given subcommand(s)\n");
    content.push_str("    install   Install hooks into Git repository\n");
    content.push_str("    list      List available hooks\n");
    content.push_str("    test      Test command to verify CLI functionality\n");
    content.push_str("    wasm      WASM component management\n");
    content.push_str("```\n\n");
    content.push_str("---\n\n");
    content.push_str("*This file is auto-generated by `cargo xtask gen-docs-comprehensive`. The CLI help section is automatically updated from the actual CLI output.*\n");

    Ok(content)
}

fn generate_test_structure_with_markers() -> Result<String, Box<dyn std::error::Error>> {
    let mut content = String::new();

    // Add codegen markers
    content
        .push_str("<!-- This file is auto-generated by `cargo xtask gen-docs-comprehensive` -->\n");
    content.push_str("<!-- Generated file: docs/STRUCTURE.md -->\n");
    content.push_str("<!-- Do not edit this file manually - changes will be overwritten -->\n\n");

    content.push_str("# Repository Structure\n\n");
    content.push_str("This document shows the complete file structure of the repository.\n\n");
    content.push_str("## 📁 File Structure\n\n");
    content.push_str("```\n");
    content.push_str(".\n");
    content.push_str("├── Cargo.toml\n");
    content.push_str("├── README.md\n");
    content.push_str("├── src/\n");
    content.push_str("│   ├── main.rs\n");
    content.push_str("│   └── lib.rs\n");
    content.push_str("├── components/\n");
    content.push_str("│   ├── cli-core/\n");
    content.push_str("│   └── worktree-runner/\n");
    content.push_str("└── tests/\n");
    content.push_str("    └── integration.rs\n");
    content.push_str("```\n\n");
    content.push_str("## 📊 File Count Summary\n\n");
    content.push_str("- **Total Files**:       15\n");
    content.push_str("- **Rust Files**:        8 (.rs)\n");
    content.push_str("- **Configuration Files**:        3 (.toml, .yaml, .rc)\n");
    content.push_str("- **Documentation**:        2 (.md)\n");
    content.push_str("- **Scripts**:        1 (.sh)\n");
    content.push_str("\n");
    content.push_str("---\n\n");
    content.push_str("*Generated using `cargo xtask gen-docs-comprehensive`. This file is auto-generated and should not be edited manually.*\n");

    Ok(content)
}

fn generate_test_examples_with_markers() -> Result<String, Box<dyn std::error::Error>> {
    let mut content = String::new();

    // Add codegen markers
    content
        .push_str("<!-- This file is auto-generated by `cargo xtask gen-docs-comprehensive` -->\n");
    content.push_str("<!-- Generated file: docs/EXAMPLES.md -->\n");
    content.push_str("<!-- Do not edit this file manually - changes will be overwritten -->\n\n");

    content.push_str("# Code Examples\n\n");
    content.push_str(
        "This document contains code examples demonstrating Hooksmith functionality.\n\n",
    );
    content.push_str("## Found 2 Examples\n\n");
    content.push_str("### Table of Contents\n\n");
    content.push_str("1. [Basic CLI Setup](#basic-cli-setup)\n");
    content.push_str("2. [Hook Building](#hook-building)\n");
    content.push_str("\n");
    content.push_str("## Basic CLI Setup\n\n");
    content.push_str("Basic CLI setup example.\n\n");
    content.push_str("### Code\n\n");
    content.push_str("```rust\n");
    content.push_str("use anyhow::Result;\n");
    content.push_str("use clap::Parser;\n\n");
    content.push_str("#[derive(Parser)]\n");
    content.push_str("struct Cli {\n");
    content.push_str("    #[arg(long)]\n");
    content.push_str("    verbose: bool,\n");
    content.push_str("}\n\n");
    content.push_str("fn main() -> Result<()> {\n");
    content.push_str("    let cli = Cli::parse();\n");
    content.push_str("    println!(\"Verbose: {}\", cli.verbose);\n");
    content.push_str("    Ok(())\n");
    content.push_str("}\n");
    content.push_str("```\n\n");
    content.push_str("---\n\n");
    content.push_str("*This file is auto-generated by `cargo xtask gen-docs-comprehensive`. Do not edit manually - changes will be overwritten.*\n");

    Ok(content)
}

fn generate_test_component_docs_with_markers() -> Result<String, Box<dyn std::error::Error>> {
    let mut content = String::new();

    // Add codegen markers
    content
        .push_str("<!-- This file is auto-generated by `cargo xtask gen-docs-comprehensive` -->\n");
    content.push_str("<!-- Generated file: components/cli-core/README.md -->\n");
    content.push_str("<!-- Do not edit this file manually - changes will be overwritten -->\n\n");

    content.push_str("# CLI Core\n\n");
    content.push_str("Core CLI functionality and utilities for Hooksmith.\n\n");
    content.push_str("## Dependencies\n\n");
    content.push_str("- anyhow\n");
    content.push_str("- clap\n");
    content.push_str("- serde\n");
    content.push_str("- serde_json\n");
    content.push_str("\n");
    content.push_str("## Features\n\n");
    content.push_str("- Command parsing\n");
    content.push_str("- Error handling\n");
    content.push_str("- Configuration management\n");
    content.push_str("\n");
    content.push_str("## Usage\n\n");
    content.push_str("```rust\n");
    content.push_str("use hooksmith::cli_core::{CliApp, Config};\n\n");
    content.push_str("let config = Config::default();\n");
    content.push_str("let app = CliApp::new(config);\n");
    content.push_str("app.run()?;\n");
    content.push_str("```\n\n");
    content.push_str("---\n\n");
    content.push_str("*This file is auto-generated by `cargo xtask gen-docs-comprehensive`. Do not edit manually - changes will be overwritten.*\n");

    Ok(content)
}
