// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod hooksmith {
        pub mod git_filter {
            /// * Git Filter Component Interface
            ///  *
            ///  * This WIT interface defines the contract for Git object filtering and validation
            ///  * operations. It provides a standardized way to process Git objects (blobs, trees,
            ///  * commits, tags) according to configurable rules and contracts.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod git_filter {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Git object type enumeration
                /// Defines the different types of Git objects that can be processed
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum GitObjectType {
                    /// Git blob object (file content)
                    Blob,
                    /// Git tree object (directory structure)
                    Tree,
                    /// Git commit object (version history)
                    Commit,
                    /// Git tag object (annotated references)
                    Tag,
                }
                impl ::core::fmt::Debug for GitObjectType {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            GitObjectType::Blob => {
                                f.debug_tuple("GitObjectType::Blob").finish()
                            }
                            GitObjectType::Tree => {
                                f.debug_tuple("GitObjectType::Tree").finish()
                            }
                            GitObjectType::Commit => {
                                f.debug_tuple("GitObjectType::Commit").finish()
                            }
                            GitObjectType::Tag => {
                                f.debug_tuple("GitObjectType::Tag").finish()
                            }
                        }
                    }
                }
                impl GitObjectType {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> GitObjectType {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => GitObjectType::Blob,
                            1 => GitObjectType::Tree,
                            2 => GitObjectType::Commit,
                            3 => GitObjectType::Tag,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// Filter operation type enumeration
                /// Defines the different operations that can be performed on Git objects
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum FilterOperation {
                    /// Validate object content against rules
                    Validate,
                    /// Transform object content according to rules
                    Transform,
                    /// Filter object content (include/exclude)
                    Filter,
                    /// Check object content for compliance
                    Check,
                }
                impl ::core::fmt::Debug for FilterOperation {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            FilterOperation::Validate => {
                                f.debug_tuple("FilterOperation::Validate").finish()
                            }
                            FilterOperation::Transform => {
                                f.debug_tuple("FilterOperation::Transform").finish()
                            }
                            FilterOperation::Filter => {
                                f.debug_tuple("FilterOperation::Filter").finish()
                            }
                            FilterOperation::Check => {
                                f.debug_tuple("FilterOperation::Check").finish()
                            }
                        }
                    }
                }
                impl FilterOperation {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> FilterOperation {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => FilterOperation::Validate,
                            1 => FilterOperation::Transform,
                            2 => FilterOperation::Filter,
                            3 => FilterOperation::Check,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// * Git object filter configuration
                ///    *
                ///    * Contains all the parameters needed to configure a filtering operation
                ///    * on a Git object.
                #[derive(Clone)]
                pub struct FilterConfig {
                    /// The type of Git object to process
                    pub object_type: GitObjectType,
                    /// The operation to perform on the object
                    pub operation: FilterOperation,
                    /// Whether to apply strict validation (fails on any violation)
                    pub strict: bool,
                    /// Additional filter parameters as key-value pairs
                    pub params: _rt::Vec<_rt::String>,
                }
                impl ::core::fmt::Debug for FilterConfig {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("FilterConfig")
                            .field("object-type", &self.object_type)
                            .field("operation", &self.operation)
                            .field("strict", &self.strict)
                            .field("params", &self.params)
                            .finish()
                    }
                }
                /// * Filter operation result
                ///    *
                ///    * Contains the outcome of a filtering operation, including success status,
                ///    * processed content, error messages, and validation details.
                #[derive(Clone)]
                pub struct FilterResult {
                    /// Whether the filter operation completed successfully
                    pub success: bool,
                    /// The processed/filtered content (if successful)
                    pub content: Option<_rt::String>,
                    /// Error message if the operation failed
                    pub error: Option<_rt::String>,
                    /// Detailed validation or processing information
                    pub details: _rt::Vec<_rt::String>,
                }
                impl ::core::fmt::Debug for FilterResult {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("FilterResult")
                            .field("success", &self.success)
                            .field("content", &self.content)
                            .field("error", &self.error)
                            .field("details", &self.details)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_validate_blob_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                    arg5: *mut u8,
                    arg6: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let base4 = arg5;
                    let len4 = arg6;
                    let mut result4 = _rt::Vec::with_capacity(len4);
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        let e4 = {
                            let l1 = *base.add(0).cast::<*mut u8>();
                            let l2 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len3 = l2;
                            let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
                            _rt::string_lift(bytes3)
                        };
                        result4.push(e4);
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result5 = T::validate_blob(
                        _rt::string_lift(bytes0),
                        FilterConfig {
                            object_type: GitObjectType::_lift(arg2 as u8),
                            operation: FilterOperation::_lift(arg3 as u8),
                            strict: _rt::bool_lift(arg4 as u8),
                            params: result4,
                        },
                    );
                    let ptr6 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result5 {
                        Ok(e) => {
                            *ptr6.add(0).cast::<u8>() = (0i32) as u8;
                            let FilterResult {
                                success: success7,
                                content: content7,
                                error: error7,
                                details: details7,
                            } = e;
                            *ptr6
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match success7 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            match content7 {
                                Some(e) => {
                                    *ptr6
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec8 = (e.into_bytes()).into_boxed_slice();
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    ::core::mem::forget(vec8);
                                    *ptr6
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len8;
                                    *ptr6
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr8.cast_mut();
                                }
                                None => {
                                    *ptr6
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match error7 {
                                Some(e) => {
                                    *ptr6
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec9 = (e.into_bytes()).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *ptr6
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *ptr6
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr9.cast_mut();
                                }
                                None => {
                                    *ptr6
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                            let vec11 = details7;
                            let len11 = vec11.len();
                            let layout11 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec11.len() * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result11 = if layout11.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout11).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout11);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec11.into_iter().enumerate() {
                                let base = result11
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let vec10 = (e.into_bytes()).into_boxed_slice();
                                    let ptr10 = vec10.as_ptr().cast::<u8>();
                                    let len10 = vec10.len();
                                    ::core::mem::forget(vec10);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len10;
                                    *base.add(0).cast::<*mut u8>() = ptr10.cast_mut();
                                }
                            }
                            *ptr6
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len11;
                            *ptr6
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result11;
                        }
                        Err(e) => {
                            *ptr6.add(0).cast::<u8>() = (1i32) as u8;
                            let vec12 = (e.into_bytes()).into_boxed_slice();
                            let ptr12 = vec12.as_ptr().cast::<u8>();
                            let len12 = vec12.len();
                            ::core::mem::forget(vec12);
                            *ptr6
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len12;
                            *ptr6
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr12.cast_mut();
                        }
                    };
                    ptr6
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_validate_blob<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = i32::from(
                                *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l1 {
                                0 => {}
                                _ => {
                                    let l2 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l3 = *arg0
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l2, l3, 1);
                                }
                            }
                            let l4 = i32::from(
                                *arg0
                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l4 {
                                0 => {}
                                _ => {
                                    let l5 = *arg0
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l6 = *arg0
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l5, l6, 1);
                                }
                            }
                            let l7 = *arg0
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l8 = *arg0
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base11 = l7;
                            let len11 = l8;
                            for i in 0..len11 {
                                let base = base11
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l9 = *base.add(0).cast::<*mut u8>();
                                    let l10 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l9, l10, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base11,
                                len11 * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                        }
                        _ => {
                            let l12 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l13 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l12, l13, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_filter_object_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                    arg5: *mut u8,
                    arg6: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let base4 = arg5;
                    let len4 = arg6;
                    let mut result4 = _rt::Vec::with_capacity(len4);
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        let e4 = {
                            let l1 = *base.add(0).cast::<*mut u8>();
                            let l2 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len3 = l2;
                            let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
                            _rt::string_lift(bytes3)
                        };
                        result4.push(e4);
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result5 = T::filter_object(
                        _rt::string_lift(bytes0),
                        FilterConfig {
                            object_type: GitObjectType::_lift(arg2 as u8),
                            operation: FilterOperation::_lift(arg3 as u8),
                            strict: _rt::bool_lift(arg4 as u8),
                            params: result4,
                        },
                    );
                    let ptr6 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result5 {
                        Ok(e) => {
                            *ptr6.add(0).cast::<u8>() = (0i32) as u8;
                            let FilterResult {
                                success: success7,
                                content: content7,
                                error: error7,
                                details: details7,
                            } = e;
                            *ptr6
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match success7 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            match content7 {
                                Some(e) => {
                                    *ptr6
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec8 = (e.into_bytes()).into_boxed_slice();
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    ::core::mem::forget(vec8);
                                    *ptr6
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len8;
                                    *ptr6
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr8.cast_mut();
                                }
                                None => {
                                    *ptr6
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match error7 {
                                Some(e) => {
                                    *ptr6
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec9 = (e.into_bytes()).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *ptr6
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *ptr6
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr9.cast_mut();
                                }
                                None => {
                                    *ptr6
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                            let vec11 = details7;
                            let len11 = vec11.len();
                            let layout11 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec11.len() * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result11 = if layout11.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout11).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout11);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec11.into_iter().enumerate() {
                                let base = result11
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let vec10 = (e.into_bytes()).into_boxed_slice();
                                    let ptr10 = vec10.as_ptr().cast::<u8>();
                                    let len10 = vec10.len();
                                    ::core::mem::forget(vec10);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len10;
                                    *base.add(0).cast::<*mut u8>() = ptr10.cast_mut();
                                }
                            }
                            *ptr6
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len11;
                            *ptr6
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result11;
                        }
                        Err(e) => {
                            *ptr6.add(0).cast::<u8>() = (1i32) as u8;
                            let vec12 = (e.into_bytes()).into_boxed_slice();
                            let ptr12 = vec12.as_ptr().cast::<u8>();
                            let len12 = vec12.len();
                            ::core::mem::forget(vec12);
                            *ptr6
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len12;
                            *ptr6
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr12.cast_mut();
                        }
                    };
                    ptr6
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_filter_object<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = i32::from(
                                *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l1 {
                                0 => {}
                                _ => {
                                    let l2 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l3 = *arg0
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l2, l3, 1);
                                }
                            }
                            let l4 = i32::from(
                                *arg0
                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l4 {
                                0 => {}
                                _ => {
                                    let l5 = *arg0
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l6 = *arg0
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l5, l6, 1);
                                }
                            }
                            let l7 = *arg0
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l8 = *arg0
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base11 = l7;
                            let len11 = l8;
                            for i in 0..len11 {
                                let base = base11
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l9 = *base.add(0).cast::<*mut u8>();
                                    let l10 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l9, l10, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base11,
                                len11 * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                        }
                        _ => {
                            let l12 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l13 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l12, l13, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_check_contract_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result2 = T::check_contract(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match e {
                                true => 1,
                                false => 0,
                            }) as u8;
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_check_contract<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_transform_content_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result2 = T::transform_content(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_transform_content<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// * Validate a Git blob object
                    ///    *
                    ///    * Performs validation on blob content according to the specified configuration.
                    ///    * Returns a result indicating whether the blob passes validation.
                    fn validate_blob(
                        blob_content: _rt::String,
                        config: FilterConfig,
                    ) -> Result<FilterResult, _rt::String>;
                    /// * Filter Git objects based on contracts
                    ///    *
                    ///    * Applies filtering rules to Git object content and returns the filtered result.
                    ///    * Can be used to include/exclude content based on contract requirements.
                    fn filter_object(
                        object_content: _rt::String,
                        config: FilterConfig,
                    ) -> Result<FilterResult, _rt::String>;
                    /// * Check if content matches contract requirements
                    ///    *
                    ///    * Performs a boolean check to determine if content complies with the specified
                    ///    * contract. Returns true if content matches contract requirements.
                    fn check_contract(
                        content: _rt::String,
                        contract_name: _rt::String,
                    ) -> Result<bool, _rt::String>;
                    /// * Transform content according to contract rules
                    ///    *
                    ///    * Applies transformation rules to content based on the specified contract.
                    ///    * Returns the transformed content or an error if transformation fails.
                    fn transform_content(
                        content: _rt::String,
                        contract_name: _rt::String,
                    ) -> Result<_rt::String, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_hooksmith_git_filter_git_filter_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "hooksmith:git-filter/git-filter#validate-blob")] unsafe extern
                        "C" fn export_validate_blob(arg0 : * mut u8, arg1 : usize, arg2 :
                        i32, arg3 : i32, arg4 : i32, arg5 : * mut u8, arg6 : usize,) -> *
                        mut u8 { unsafe { $($path_to_types)*::
                        _export_validate_blob_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4,
                        arg5, arg6) } } #[unsafe (export_name =
                        "cabi_post_hooksmith:git-filter/git-filter#validate-blob")]
                        unsafe extern "C" fn _post_return_validate_blob(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_validate_blob::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "hooksmith:git-filter/git-filter#filter-object")] unsafe extern
                        "C" fn export_filter_object(arg0 : * mut u8, arg1 : usize, arg2 :
                        i32, arg3 : i32, arg4 : i32, arg5 : * mut u8, arg6 : usize,) -> *
                        mut u8 { unsafe { $($path_to_types)*::
                        _export_filter_object_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4,
                        arg5, arg6) } } #[unsafe (export_name =
                        "cabi_post_hooksmith:git-filter/git-filter#filter-object")]
                        unsafe extern "C" fn _post_return_filter_object(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_filter_object::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "hooksmith:git-filter/git-filter#check-contract")] unsafe extern
                        "C" fn export_check_contract(arg0 : * mut u8, arg1 : usize, arg2
                        : * mut u8, arg3 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_check_contract_cabi::<$ty > (arg0,
                        arg1, arg2, arg3) } } #[unsafe (export_name =
                        "cabi_post_hooksmith:git-filter/git-filter#check-contract")]
                        unsafe extern "C" fn _post_return_check_contract(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_check_contract::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "hooksmith:git-filter/git-filter#transform-content")] unsafe
                        extern "C" fn export_transform_content(arg0 : * mut u8, arg1 :
                        usize, arg2 : * mut u8, arg3 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_transform_content_cabi::<$ty >
                        (arg0, arg1, arg2, arg3) } } #[unsafe (export_name =
                        "cabi_post_hooksmith:git-filter/git-filter#transform-content")]
                        unsafe extern "C" fn _post_return_transform_content(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_transform_content::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_hooksmith_git_filter_git_filter_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 10 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 10
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_git_filter_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::hooksmith::git_filter::git_filter::__export_hooksmith_git_filter_git_filter_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::hooksmith::git_filter::git_filter);
    };
}
#[doc(inline)]
pub(crate) use __export_git_filter_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:hooksmith:git-filter:git-filter-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 657] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8a\x04\x01A\x02\x01\
A\x02\x01B\x15\x01m\x04\x04blob\x04tree\x06commit\x03tag\x04\0\x0fgit-object-typ\
e\x03\0\0\x01m\x04\x08validate\x09transform\x06filter\x05check\x04\0\x10filter-o\
peration\x03\0\x02\x01ps\x01r\x04\x0bobject-type\x01\x09operation\x03\x06strict\x7f\
\x06params\x04\x04\0\x0dfilter-config\x03\0\x05\x01ks\x01r\x04\x07success\x7f\x07\
content\x07\x05error\x07\x07details\x04\x04\0\x0dfilter-result\x03\0\x08\x01j\x01\
\x09\x01s\x01@\x02\x0cblob-contents\x06config\x06\0\x0a\x04\0\x0dvalidate-blob\x01\
\x0b\x01@\x02\x0eobject-contents\x06config\x06\0\x0a\x04\0\x0dfilter-object\x01\x0c\
\x01j\x01\x7f\x01s\x01@\x02\x07contents\x0dcontract-names\0\x0d\x04\0\x0echeck-c\
ontract\x01\x0e\x01j\x01s\x01s\x01@\x02\x07contents\x0dcontract-names\0\x0f\x04\0\
\x11transform-content\x01\x10\x04\0\x1fhooksmith:git-filter/git-filter\x05\0\x04\
\0%hooksmith:git-filter/git-filter-world\x04\0\x0b\x16\x01\0\x10git-filter-world\
\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10\
wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
