#!/usr/bin/env rust-script
//! Pre-commit hook to validate checksums for generated files
//! This script ensures all generated files have valid checksums
//! and detects any manual modifications to generated content

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process;

/// File types that should have checksums (generated files)
const GENERATED_EXTENSIONS: &[&str] = &[
    "toml", "md", "yml", "yaml", "gitignore", "gitattributes", 
    "json", "jql", "jsonl", "wit"
];

/// Files without extensions that should have checksums
const GENERATED_NO_EXTENSION: &[&str] = &[
    "CODEOWNERS", "Makefile", ".editorconfig", ".envrc"
];

/// Directories to exclude from validation
const EXCLUDED_DIRS: &[&str] = &[
    "target", "dist", "build", "node_modules", ".git", "logs",
    "status-trends", "generated_file_demo", ".cargo", ".trunk", ".hooks"
];

/// Checksum prefixes for different file types
fn get_checksum_prefix(file_type: &str) -> &'static str {
    match file_type {
        "md" => "<!-- @checksum:",
        "toml" | "yml" | "yaml" | "gitignore" | "gitattributes" | "CODEOWNERS" | "makefile" | "editorconfig" | "envrc" => "# @checksum:",
        "json" | "jsonl" | "jql" => "// @checksum:",
        "wit" => ";; @checksum:",
        _ => "# @checksum:",
    }
}

/// Generate header prefix for different file types
fn get_header_prefix(file_type: &str) -> &'static str {
    match file_type {
        "md" => "<!-- @generated by xtask gen-files --file-type=md -->",
        "toml" => "# @generated by xtask gen-files --file-type=toml",
        "yml" => "# @generated by xtask gen-files --file-type=yml",
        "yaml" => "# @generated by xtask gen-files --file-type=yaml",
        "gitignore" => "# @generated by xtask gen-files --file-type=gitignore",
        "gitattributes" => "# @generated by xtask gen-files --file-type=gitattributes",
        "CODEOWNERS" => "# @generated by xtask gen-files --file-type=CODEOWNERS",
        "json" => "// @generated by xtask gen-files --file-type=json",
        "jsonl" => "// @generated by xtask gen-files --file-type=jsonl",
        "jql" => "// @generated by xtask gen-files --file-type=jql",
        "wit" => ";; @generated by xtask gen-files --file-type=wit",
        "makefile" => "# @generated by xtask gen-files --file-type=makefile",
        "editorconfig" => "# @generated by xtask gen-files --file-type=editorconfig",
        "envrc" => "# @generated by xtask gen-files --file-type=envrc",
        _ => "# @generated by xtask gen-files --file-type=",
    }
}

/// Compute SHA-256 checksum (first 8 characters)
fn compute_checksum(content: &str) -> String {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};
    
    let mut hasher = DefaultHasher::new();
    content.hash(&mut hasher);
    format!("{:x}", hasher.finish())[..8].to_string()
}

/// Extract file type from path
fn get_file_type(path: &Path) -> Option<String> {
    if let Some(extension) = path.extension() {
        if let Some(ext_str) = extension.to_str() {
            return Some(ext_str.to_lowercase());
        }
    }
    
    // Check for files without extensions
    if let Some(file_name) = path.file_name() {
        if let Some(name_str) = file_name.to_str() {
            if GENERATED_NO_EXTENSION.contains(&name_str) {
                return Some(name_str.to_lowercase());
            }
        }
    }
    
    None
}

/// Check if a file should have a checksum
fn should_have_checksum(path: &Path) -> bool {
    // Skip excluded directories
    if path.components().any(|component| {
        if let std::path::Component::Normal(name) = component {
            EXCLUDED_DIRS.contains(&name.to_str().unwrap_or(""))
        } else {
            false
        }
    }) {
        return false;
    }
    
    // Check file extension
    if let Some(extension) = path.extension() {
        if let Some(ext_str) = extension.to_str() {
            return GENERATED_EXTENSIONS.contains(&ext_str);
        }
    }
    
    // Check files without extensions
    if let Some(file_name) = path.file_name() {
        if let Some(name_str) = file_name.to_str() {
            return GENERATED_NO_EXTENSION.contains(&name_str);
        }
    }
    
    false
}

/// Validate checksum for a single file
fn validate_file_checksum(file_path: &Path) -> Result<bool, String> {
    let file_type = get_file_type(file_path)
        .ok_or_else(|| format!("Could not determine file type for {}", file_path.display()))?;
    
    let content = fs::read_to_string(file_path)
        .map_err(|e| format!("Failed to read {}: {}", file_path.display(), e))?;
    
    let lines: Vec<&str> = content.lines().collect();
    
    // Check for generated header
    let header_prefix = get_header_prefix(&file_type);
    let checksum_prefix = get_checksum_prefix(&file_type);
    
    if lines.len() < 2 {
        return Err(format!("{}: File too short to contain generated header", file_path.display()));
    }
    
    // Check first line for generated header
    if !lines[0].contains(header_prefix) {
        return Err(format!("{}: Missing generated header. Expected: {}", file_path.display(), header_prefix));
    }
    
    // Check second line for checksum
    if !lines[1].contains(checksum_prefix) {
        return Err(format!("{}: Missing checksum header. Expected: {}", file_path.display(), checksum_prefix));
    }
    
    // Extract checksum from second line
    let checksum_line = lines[1];
    let checksum_start = checksum_line.find(checksum_prefix)
        .ok_or_else(|| format!("{}: Could not find checksum prefix", file_path.display()))?;
    
    let checksum_part = &checksum_line[checksum_start + checksum_prefix.len()..];
    let expected_checksum = checksum_part.trim().trim_end_matches(" -->").trim_end_matches(" -->");
    
    // Extract content without header (lines 3 onwards)
    let content_without_header = if lines.len() > 2 {
        lines[2..].join("\n")
    } else {
        String::new()
    };
    
    // Compute actual checksum
    let actual_checksum = compute_checksum(&content_without_header);
    
    if actual_checksum == expected_checksum {
        Ok(true)
    } else {
        Err(format!("{}: Checksum mismatch. Expected: {}, Actual: {}", 
                   file_path.display(), expected_checksum, actual_checksum))
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = env::args().collect();
    
    if args.len() < 2 {
        eprintln!("Usage: {} <file1> [file2] ...", args[0]);
        process::exit(1);
    }

    let mut errors = Vec::new();
    let mut warnings = Vec::new();
    let mut validated_files = Vec::new();

    // Process each file argument
    for file_path in &args[1..] {
        let path = Path::new(file_path);
        
        if !path.exists() {
            warnings.push(format!("File '{}' does not exist (may have been deleted)", file_path));
            continue;
        }
        
        if should_have_checksum(path) {
            match validate_file_checksum(path) {
                Ok(true) => {
                    validated_files.push(file_path.clone());
                    println!("✅ {} (checksum valid)", file_path);
                }
                Ok(false) => {
                    errors.push(format!("{}: Checksum validation failed", file_path));
                }
                Err(e) => {
                    errors.push(format!("{}: {}", file_path, e));
                }
            }
        } else {
            // File doesn't need checksum validation
            println!("⏭️  {} (no checksum required)", file_path);
        }
    }

    // Report results
    if !errors.is_empty() {
        eprintln!("\n❌ Checksum validation failed:");
        for error in &errors {
            eprintln!("   {}", error);
        }
        eprintln!("\nGenerated files must have valid checksums.");
        eprintln!("To fix, regenerate files using: cargo xtask gen-files --file-type=<type>");
        process::exit(1);
    }

    if !warnings.is_empty() {
        eprintln!("\n⚠️  Warnings:");
        for warning in &warnings {
            eprintln!("   {}", warning);
        }
    }

    if !validated_files.is_empty() {
        println!("\n✅ Checksum validation summary:");
        println!("   Validated {} generated files", validated_files.len());
        for file in &validated_files {
            println!("   - {}", file);
        }
    }

    if errors.is_empty() {
        println!("\n✅ All generated files have valid checksums");
    }

    Ok(())
} 