#!/bin/bash

# Add Checksums to Generated Files
# This script adds checksums to all generated files that don't have them yet

set -e

echo "🔧 Adding Checksums to Generated Files"
echo "======================================"

# Get list of files that need checksums
echo "📋 Finding files that need checksums..."
FILES_NEEDING_CHECKSUMS=$(git ls-files | grep -E '\.(md|toml|yml|yaml|json|wit|jql|jsonl|gitignore|gitattributes)$|^(CODEOWNERS|Makefile|\.editorconfig|\.envrc)$' | while read file; do
    if ! grep -q "@checksum" "$file" 2>/dev/null; then
        echo "$file"
    fi
done)

TOTAL_FILES=$(echo "$FILES_NEEDING_CHECKSUMS" | wc -l | tr -d ' ')
echo "Found $TOTAL_FILES files needing checksums"
echo ""

# Function to add checksum to a file
add_checksum_to_file() {
    local file="$1"
    local file_type=""
    
    # Determine file type
    if [[ "$file" == *.md ]]; then
        file_type="md"
    elif [[ "$file" == *.toml ]]; then
        file_type="toml"
    elif [[ "$file" == *.yml ]]; then
        file_type="yml"
    elif [[ "$file" == *.yaml ]]; then
        file_type="yaml"
    elif [[ "$file" == *.json ]]; then
        file_type="json"
    elif [[ "$file" == *.wit ]]; then
        file_type="wit"
    elif [[ "$file" == *.jql ]]; then
        file_type="jql"
    elif [[ "$file" == *.jsonl ]]; then
        file_type="jsonl"
    elif [[ "$file" == *.gitignore ]]; then
        file_type="gitignore"
    elif [[ "$file" == *.gitattributes ]]; then
        file_type="gitattributes"
    elif [[ "$file" == "CODEOWNERS" ]]; then
        file_type="CODEOWNERS"
    elif [[ "$file" == "Makefile" ]]; then
        file_type="makefile"
    elif [[ "$file" == ".editorconfig" ]]; then
        file_type="editorconfig"
    elif [[ "$file" == ".envrc" ]]; then
        file_type="envrc"
    else
        echo "⚠️  Unknown file type for $file"
        return 1
    fi
    
    # Get header prefix
    local header_prefix=""
    case "$file_type" in
        "md")
            header_prefix="<!-- @generated by xtask gen-files --file-type=md -->"
            ;;
        "toml"|"yml"|"yaml"|"gitignore"|"gitattributes"|"CODEOWNERS"|"makefile"|"editorconfig"|"envrc")
            header_prefix="# @generated by xtask gen-files --file-type=$file_type"
            ;;
        "json"|"jsonl"|"jql")
            header_prefix="// @generated by xtask gen-files --file-type=$file_type"
            ;;
        "wit")
            header_prefix=";; @generated by xtask gen-files --file-type=wit"
            ;;
    esac
    
    # Get checksum prefix
    local checksum_prefix=""
    case "$file_type" in
        "md")
            checksum_prefix="<!-- @checksum:"
            ;;
        "toml"|"yml"|"yaml"|"gitignore"|"gitattributes"|"CODEOWNERS"|"makefile"|"editorconfig"|"envrc")
            checksum_prefix="# @checksum:"
            ;;
        "json"|"jsonl"|"jql")
            checksum_prefix="// @checksum:"
            ;;
        "wit")
            checksum_prefix=";; @checksum:"
            ;;
    esac
    
    # Read file content
    local content=$(cat "$file")
    local lines=()
    IFS=$'\n' read -d '' -r -a lines <<< "$content"
    
    # Check if file already has generated header
    local has_header=false
    local has_checksum=false
    
    if [[ ${#lines[@]} -gt 0 ]]; then
        if [[ "${lines[0]}" == *"@generated"* ]]; then
            has_header=true
        fi
        if [[ "${lines[1]}" == *"@checksum"* ]]; then
            has_checksum=true
        fi
    fi
    
    # If file already has both header and checksum, skip
    if [[ "$has_header" == "true" && "$has_checksum" == "true" ]]; then
        echo "⏭️  $file (already has checksum)"
        return 0
    fi
    
    # Compute checksum of content (without headers)
    local content_for_checksum=""
    if [[ "$has_header" == "true" && "$has_checksum" == "true" ]]; then
        # Skip first two lines (header and checksum)
        content_for_checksum=$(printf '%s\n' "${lines[@]:2}")
    elif [[ "$has_header" == "true" ]]; then
        # Skip first line (header)
        content_for_checksum=$(printf '%s\n' "${lines[@]:1}")
    else
        # Use all content
        content_for_checksum="$content"
    fi
    
    # Compute checksum (first 8 characters of hash)
    local checksum=$(echo -n "$content_for_checksum" | sha256sum | cut -c1-8)
    
    # Create new content
    local new_content=""
    if [[ "$has_header" == "true" && "$has_checksum" == "false" ]]; then
        # Add checksum after existing header
        new_content="${lines[0]}\n$checksum_prefix $checksum"
        if [[ "$file_type" == "md" ]]; then
            new_content="$new_content -->"
        fi
        new_content="$new_content\n$(printf '%s\n' "${lines[@]:1}")"
    elif [[ "$has_header" == "false" ]]; then
        # Add both header and checksum
        new_content="$header_prefix\n$checksum_prefix $checksum"
        if [[ "$file_type" == "md" ]]; then
            new_content="$new_content -->"
        fi
        new_content="$new_content\n$content"
    fi
    
    # Write new content to file
    echo -e "$new_content" > "$file"
    echo "✅ $file (added checksum: $checksum)"
}

# Process files
echo "🔧 Adding checksums to files..."
echo ""

COUNTER=0
echo "$FILES_NEEDING_CHECKSUMS" | while read file; do
    if [[ -n "$file" ]]; then
        COUNTER=$((COUNTER + 1))
        echo "[$COUNTER/$TOTAL_FILES] Processing $file..."
        add_checksum_to_file "$file"
    fi
done

echo ""
echo "✅ Checksum addition completed!"
echo ""
echo "📊 Summary:"
echo "   • Processed $TOTAL_FILES files"
echo "   • Added checksums to generated files"
echo ""
echo "🔍 Next steps:"
echo "   1. Test validation: ./target/debug/validate-checksums <file>"
echo "   2. Commit changes: git add . && git commit -m 'Add checksums to generated files'"
echo "   3. Test pre-commit hooks: git commit --allow-empty -m 'Test pre-commit validation'" 