# @generated by xtask gen-scripts

#!/bin/bash

# Fast development cycle with all optimizations enabled
# This script provides a complete development workflow with build optimizations

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Configuration
export RUSTC_WRAPPER="sccache"
export SCCACHE_CACHE_SIZE="10G"
PARALLEL_JOBS=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 8)

# Check if we're in the right directory
if [[ ! -f "Cargo.toml" ]]; then
    log_error "Must be run from the project root directory"
    exit 1
fi

echo "🚀 Starting optimized development cycle..."
echo "=========================================="

# 1. Setup environment
log_info "Setting up development environment..."

# Check for optimization tools
if command -v sccache >/dev/null 2>&1; then
    log_success "✓ sccache available"
else
    log_warning "⚠ sccache not found - run ./scripts/optimize-build.sh to install"
fi

if command -v cargo-hakari >/dev/null 2>&1; then
    log_success "✓ cargo-hakari available"
else
    log_warning "⚠ cargo-hakari not found - run ./scripts/optimize-build.sh to install"
fi

if command -v cargo-nextest >/dev/null 2>&1; then
    log_success "✓ cargo-nextest available"
else
    log_warning "⚠ cargo-nextest not found - run ./scripts/optimize-build.sh to install"
fi

# 2. Fast check with parallel compilation
log_info "Running fast check..."
if command -v cargo-hakari >/dev/null 2>&1; then
    # Use hakari for faster dependency resolution
    cargo hakari manage-deps
fi

# Use nightly for parallel compilation if available
if rustup toolchain list | grep -q nightly; then
    log_info "Using nightly toolchain for parallel compilation..."
    export RUSTFLAGS="-Z threads=${PARALLEL_JOBS}"
    cargo +nightly check --all-targets --all-features
else
    log_info "Using stable toolchain..."
    cargo check --all-targets --all-features
fi

# 3. Run tests with cargo-nextest
log_info "Running tests..."
if command -v cargo-nextest >/dev/null 2>&1; then
    log_info "Using cargo-nextest for parallel testing..."
    cargo nextest run --all-targets --all-features --test-threads=${PARALLEL_JOBS}
else
    log_info "Using standard cargo test..."
    cargo test --all-targets --all-features
fi

# 4. Run the application
log_info "Running application..."
if [[ -f "src/main.rs" ]]; then
    cargo run --release
else
    log_info "No main.rs found, running xtask..."
    cargo run --bin xtask -- --help
fi

echo
log_success "✅ Development cycle complete!"
echo
echo "📊 Performance Summary:"
if command -v sccache >/dev/null 2>&1; then
    echo "🔧 sccache Statistics:"
    sccache --show-stats
    echo
fi

echo "💡 Tips for faster development:"
echo "  • Use 'cargo dev-fast' for fast builds"
echo "  • Use 'cargo test-parallel' for parallel tests"
echo "  • Use 'cargo watch' for continuous development"
echo "  • Monitor cache usage with './scripts/build-stats.sh'" 
