#!/bin/bash

# Enhanced File Generation with Checksum Registry
# Demonstrates the complete workflow for generating files with checksums

set -e

echo "🔧 Enhanced File Generation with Checksum Registry"
echo "================================================="

# Create test directory
TEST_DIR="test-enhanced-gen-files"
rm -rf "$TEST_DIR"
mkdir -p "$TEST_DIR"

echo "📁 Created test directory: $TEST_DIR"

# Create a sample checksum registry
echo "📋 Creating sample checksum registry..."

cat > "$TEST_DIR/generated-files.jsonc" << 'EOF'
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Hooksmith Generated Files",
  "description": "Registry of generated files with stable slugs and checksums for validation and regeneration.",
  
  // All files listed here are assumed to be generated
  // No redundant generated: true flags needed
  "files": [
    {
      "slug": "readme",
      "path": "README.md",
      "type": "md",
      "checksum": "e3b0c442"
    },
    {
      "slug": "gitignore",
      "path": ".gitignore",
      "type": "gitignore",
      "checksum": "7a2f1b9d"
    },
    {
      "slug": "cargo-toml",
      "path": "Cargo.toml",
      "type": "toml",
      "checksum": "4f9e13ac"
    },
    {
      "slug": "config-json",
      "path": "config.json",
      "type": "json",
      "checksum": "1a2b3c4d"
    },
    {
      "slug": "hooksmith-wit",
      "path": "hooksmith.wit",
      "type": "wit",
      "checksum": "5e6f7g8h"
    }
  ],
  "ignore": {
    "dirs": [
      "target/",
      "dist/",
      "node_modules/",
      "logs/",
      "status-trends/",
      "generated_file_demo/",
      ".cargo/",
      ".trunk/",
      ".hooks/",
      ".git/"
    ],
    "patterns": [
      "*.lock",
      "*.jsonl"
    ]
  }
}
EOF

echo "✅ Created sample checksum registry"

# Function to compute SHA-256 checksum (first 8 chars)
compute_checksum() {
    local content="$1"
    echo -n "$content" | sha256sum | cut -c1-8
}

# Function to generate file with checksum
generate_file_with_checksum() {
    local file_path="$1"
    local file_type="$2"
    local content="$3"
    
    echo "🔧 Generating $file_path..."
    
    # Compute checksum of content
    local checksum=$(compute_checksum "$content")
    
    # Generate header based on file type
    local header=""
    case "$file_type" in
        "md")
            header="<!-- @generated by xtask gen-files --file-type=md -->\n<!-- @checksum: $checksum -->\n"
            ;;
        "gitignore")
            header="# @generated by xtask gen-files --file-type=gitignore\n# @checksum: $checksum\n"
            ;;
        "toml")
            header="# @generated by xtask gen-files --file-type=toml\n# @checksum: $checksum\n"
            ;;
        "json")
            header="// @generated by xtask gen-files --file-type=json\n// @checksum: $checksum\n"
            ;;
        "wit")
            header=";; @generated by xtask gen-files --file-type=wit\n;; @checksum: $checksum\n"
            ;;
        *)
            header="# @generated by xtask gen-files --file-type=$file_type\n# @checksum: $checksum\n"
            ;;
    esac
    
    # Write file with header
    echo -e "$header$content" > "$file_path"
    
    echo "✅ Generated $file_path with checksum: $checksum"
    
    # Return checksum for registry update (without echo statement)
    printf "%s" "$checksum"
}

# Generate sample files
echo ""
echo "📝 Generating sample files..."

# README.md
readme_content="# Hooksmith

A comprehensive Git workflow automation tool with contract validation and structured logging.

## Features

- Contract-driven validation
- Structured logging with JSONL
- WebAssembly component support
- Lefthook integration
- Comprehensive documentation generation

## Quick Start

\`\`\`bash
cargo install --path .
\`\`\`

## Development

\`\`\`bash
cargo xtask gen-all --validate
\`\`\`"

readme_checksum=$(generate_file_with_checksum "$TEST_DIR/README.md" "md" "$readme_content")

# .gitignore
gitignore_content="target/
dist/
*.log
*.tmp
*.bak
*.lock
node_modules/
.cargo/
.trunk/
.hooks/"

gitignore_checksum=$(generate_file_with_checksum "$TEST_DIR/.gitignore" "gitignore" "$gitignore_content")

# Cargo.toml
cargo_content="[package]
name = \"hooksmith\"
version = \"0.1.0\"
edition = \"2021\"
authors = [\"Your Name <your.email@example.com>\"]
description = \"Git workflow automation with contract validation\"
license = \"MIT\"

[dependencies]
serde = { version = \"1.0\", features = [\"derive\"] }
anyhow = \"1.0\"
tokio = { version = \"1.0\", features = [\"full\"] }"

cargo_checksum=$(generate_file_with_checksum "$TEST_DIR/Cargo.toml" "toml" "$cargo_content")

# config.json
config_content="{
  \"project\": {
    \"name\": \"hooksmith\",
    \"version\": \"0.1.0\",
    \"description\": \"Git workflow automation tool\"
  },
  \"features\": {
    \"contract_validation\": true,
    \"structured_logging\": true,
    \"wasm_support\": true
  },
  \"generated\": true
}"

config_checksum=$(generate_file_with_checksum "$TEST_DIR/config.json" "json" "$config_content")

# hooksmith.wit
wit_content="package hooksmith:validation;

interface validation-handler {
  validate-file: func(path: string) -> result<validation-result, validation-error>;
  validate-contract: func(contract: string, content: string) -> result<bool, validation-error>;
}

record validation-result {
  valid: bool,
  errors: list<string>,
  warnings: list<string>,
}

record validation-error {
  code: string,
  message: string,
}"

wit_checksum=$(generate_file_with_checksum "$TEST_DIR/hooksmith.wit" "wit" "$wit_content")

# Update the registry with actual checksums
echo ""
echo "📋 Updating checksum registry with actual checksums..."

cat > "$TEST_DIR/generated-files.jsonc" << EOF
{
  "\$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Hooksmith Generated Files",
  "description": "Registry of generated files with stable slugs and checksums for validation and regeneration.",
  
  // All files listed here are assumed to be generated
  // No redundant generated: true flags needed
  "files": [
    {
      "slug": "readme",
      "path": "README.md",
      "type": "md",
      "checksum": "$readme_checksum"
    },
    {
      "slug": "gitignore",
      "path": ".gitignore",
      "type": "gitignore",
      "checksum": "$gitignore_checksum"
    },
    {
      "slug": "cargo-toml",
      "path": "Cargo.toml",
      "type": "toml",
      "checksum": "$cargo_checksum"
    },
    {
      "slug": "config-json",
      "path": "config.json",
      "type": "json",
      "checksum": "$config_checksum"
    },
    {
      "slug": "hooksmith-wit",
      "path": "hooksmith.wit",
      "type": "wit",
      "checksum": "$wit_checksum"
    }
  ],
  "ignore": {
    "dirs": [
      "target/",
      "dist/",
      "node_modules/",
      "logs/",
      "status-trends/",
      "generated_file_demo/",
      ".cargo/",
      ".trunk/",
      ".hooks/",
      ".git/"
    ],
    "patterns": [
      "*.lock",
      "*.jsonl"
    ]
  }
}
EOF

echo "✅ Updated checksum registry"

# Function to validate file checksum
validate_file_checksum() {
    local file_path="$1"
    local expected_checksum="$2"
    
    echo "🔍 Validating $file_path..."
    
    # Read file content
    local content=$(cat "$file_path")
    
    # Extract content without header (first 2 lines)
    local content_without_header=$(echo "$content" | tail -n +3)
    
    # Compute actual checksum
    local actual_checksum=$(compute_checksum "$content_without_header")
    
    if [ "$actual_checksum" = "$expected_checksum" ]; then
        echo "✅ $file_path: checksum matches ($actual_checksum)"
        return 0
    else
        echo "❌ $file_path: checksum mismatch (expected: $expected_checksum, actual: $actual_checksum)"
        return 1
    fi
}

# Validate all files
echo ""
echo "🔍 Validating all generated files..."

# Extract checksums from registry
readme_expected=$(grep -A 4 '"slug": "readme"' "$TEST_DIR/generated-files.jsonc" | grep '"checksum"' | cut -d'"' -f4)
gitignore_expected=$(grep -A 4 '"slug": "gitignore"' "$TEST_DIR/generated-files.jsonc" | grep '"checksum"' | cut -d'"' -f4)
cargo_expected=$(grep -A 4 '"slug": "cargo-toml"' "$TEST_DIR/generated-files.jsonc" | grep '"checksum"' | cut -d'"' -f4)
config_expected=$(grep -A 4 '"slug": "config-json"' "$TEST_DIR/generated-files.jsonc" | grep '"checksum"' | cut -d'"' -f4)
wit_expected=$(grep -A 4 '"slug": "hooksmith-wit"' "$TEST_DIR/generated-files.jsonc" | grep '"checksum"' | cut -d'"' -f4)

validate_file_checksum "$TEST_DIR/README.md" "$readme_expected"
validate_file_checksum "$TEST_DIR/.gitignore" "$gitignore_expected"
validate_file_checksum "$TEST_DIR/Cargo.toml" "$cargo_expected"
validate_file_checksum "$TEST_DIR/config.json" "$config_expected"
validate_file_checksum "$TEST_DIR/hooksmith.wit" "$wit_expected"

# Demonstrate tamper detection
echo ""
echo "🔧 Demonstrating tamper detection..."

echo "📝 Modifying README.md content (simulating manual edit)..."
echo "" >> "$TEST_DIR/README.md"
echo "# Manual addition - this should invalidate the checksum" >> "$TEST_DIR/README.md"

echo "🔍 Re-validating README.md..."
if validate_file_checksum "$TEST_DIR/README.md" "$readme_expected"; then
    echo "❌ ERROR: Tamper detection failed!"
else
    echo "✅ SUCCESS: Tamper detection working correctly!"
fi

# Show the complete workflow
echo ""
echo "🔄 Complete Workflow Summary:"
echo "============================"
echo ""
echo "1. 📋 Registry Management:"
echo "   • config/generated-files.jsonc contains file metadata and checksums"
echo "   • Each file has: slug, path, type, checksum"
echo "   • Registry serves as source of truth for validation"
echo ""
echo "2. 🔧 File Generation:"
echo "   • Generate file content"
echo "   • Compute SHA-256 checksum of content"
echo "   • Add header with checksum"
echo "   • Write file to disk"
echo "   • Update registry with new checksum"
echo ""
echo "3. 🔍 Validation:"
echo "   • Read file content"
echo "   • Strip header lines"
echo "   • Compute checksum of remaining content"
echo "   • Compare with registry checksum"
echo "   • Report validation result"
echo ""
echo "4. 🛡️ Tamper Detection:"
echo "   • Any manual modification changes content checksum"
echo "   • Validation fails when checksums don't match"
echo "   • Ensures generated files remain unmodified"
echo ""

# Show file contents
echo "📝 Generated File Examples:"
echo "=========================="
echo ""
echo "1. README.md:"
head -5 "$TEST_DIR/README.md"
echo ""
echo "2. .gitignore:"
head -5 "$TEST_DIR/.gitignore"
echo ""
echo "3. hooksmith.wit:"
head -5 "$TEST_DIR/hooksmith.wit"
echo ""

# Show registry structure
echo "📋 Registry Structure:"
echo "====================="
echo ""
echo "The registry contains:"
echo "• File metadata (slug, path, type)"
echo "• Checksums for validation"
echo "• Ignore rules for filtering"
echo "• JSONC format with comments"
echo ""

echo "🎯 Benefits Achieved:"
echo "===================="
echo "✅ Tamper detection: Any manual edit fails validation"
echo "✅ Deterministic builds: Checksums confirm expected content"
echo "✅ Registry source of truth: Centralized file tracking"
echo "✅ Easy regeneration: Slugs + checksums enable automation"
echo "✅ Comprehensive validation: All generated files tracked"
echo ""

echo "🧹 Cleaning up test directory..."
rm -rf "$TEST_DIR"

echo "✅ Enhanced file generation demonstration completed!"
echo ""
echo "📚 Next Steps:"
echo "1. Integrate this workflow into cargo xtask gen-files"
echo "2. Create migration script for existing files"
echo "3. Add registry validation to pre-commit hooks"
echo "4. Implement automatic checksum updates"
echo "5. Add to CI/CD pipeline for ongoing validation" 
