#!/usr/bin/env rust

use std::collections::HashMap;
use std::env;
use std::fs;
use std::io;
use std::path::Path;
use std::process::{Command, Stdio};

fn main() -> io::Result<()> {
    let args: Vec<String> = env::args().collect();
    let default_file = ".gitattributes".to_string();
    let output_file = args.get(1).unwrap_or(&default_file);
    
    println!("🔍 Analyzing repository files with hyperpolyglot...");
    
    // Get all tracked files from git
    let files = get_git_files()?;
    println!("📁 Found {} tracked files", files.len());
    
    // Detect languages for each file
    let language_map = detect_languages(&files)?;
    println!("🎯 Detected {} unique languages", language_map.len());
    
    // Generate .gitattributes content
    let gitattributes_content = generate_gitattributes(&language_map)?;
    
    // Write to file
    fs::write(output_file, gitattributes_content)?;
    println!("✅ Generated {} with {} language entries", output_file, language_map.len());
    
    // Print summary
    print_summary(&language_map);
    
    Ok(())
}

fn get_git_files() -> io::Result<Vec<String>> {
    let output = Command::new("git")
        .args(&["ls-files", "--cached", "--full-name"])
        .output()?;
    
    if !output.status.success() {
        return Err(io::Error::new(
            io::ErrorKind::Other,
            "Failed to get git files"
        ));
    }
    
    let files = String::from_utf8_lossy(&output.stdout)
        .lines()
        .map(|s| s.to_string())
        .collect();
    
    Ok(files)
}

fn detect_languages(files: &[String]) -> io::Result<HashMap<String, Vec<String>>> {
    let mut language_map: HashMap<String, Vec<String>> = HashMap::new();
    
    for file in files {
        if let Some(language) = detect_single_file_language(file)? {
            language_map
                .entry(language)
                .or_insert_with(Vec::new)
                .push(file.clone());
        }
    }
    
    Ok(language_map)
}

fn detect_single_file_language(file_path: &str) -> io::Result<Option<String>> {
    // Skip files that don't exist or are directories
    if !Path::new(file_path).exists() {
        return Ok(None);
    }
    
    let output = Command::new("hyply")
        .args(&["--breakdown", file_path])
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()?;
    
    if !output.status.success() {
        // Skip files that can't be analyzed
        return Ok(None);
    }
    
    let output_str = String::from_utf8_lossy(&output.stdout);
    
    // Parse hyply output to extract language
    // hyply outputs like: "100.00% Rust" for single files
    for line in output_str.lines() {
        if line.contains('%') {
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() >= 2 {
                let language = parts[1];
                return Ok(Some(language.to_string()));
            }
        }
    }
    
    Ok(None)
}

fn generate_gitattributes(language_map: &HashMap<String, Vec<String>>) -> io::Result<String> {
    let mut content = String::new();
    
    // Header
    content.push_str("# @generated by generate-gitattributes.rs\n");
    content.push_str("# @checksum: auto-generated\n\n");
    content.push_str("# GENERATED FILE - DO NOT EDIT\n");
    content.push_str("# This file is automatically generated by generate-gitattributes.rs\n");
    content.push_str("# To modify this file, update the source and regenerate\n\n");
    
    content.push_str("# =============================================================================\n");
    content.push_str("# LANGUAGE DETECTION RESULTS\n");
    content.push_str("# =============================================================================\n");
    content.push_str("# Generated from hyperpolyglot analysis of repository files\n\n");
    
    // Generate linguist-language attributes for each language
    for (language, files) in language_map {
        content.push_str(&format!("# {} files\n", language));
        for file in files {
            content.push_str(&format!("{} linguist-language={}\n", file, language));
        }
        content.push_str("\n");
    }
    
    // Add common exclusions and overrides
    content.push_str("# =============================================================================\n");
    content.push_str("# COMMON EXCLUSIONS AND OVERRIDES\n");
    content.push_str("# =============================================================================\n\n");
    
    // Mark generated files
    content.push_str("# Generated files - mark as linguist-generated\n");
    content.push_str("target/ linguist-generated=true\n");
    content.push_str("dist/ linguist-generated=true\n");
    content.push_str("build/ linguist-generated=true\n");
    content.push_str("node_modules/ linguist-generated=true\n");
    content.push_str(".git/ linguist-generated=true\n\n");
    
    // Mark documentation files
    content.push_str("# Documentation files - exclude from language stats\n");
    content.push_str("*.md linguist-documentation=true\n");
    content.push_str("*.txt linguist-documentation=true\n");
    content.push_str("*.rst linguist-documentation=true\n\n");
    
    // Mark vendored files
    content.push_str("# Vendored files - exclude from language stats\n");
    content.push_str("vendor/ linguist-vendored=true\n");
    content.push_str("third_party/ linguist-vendored=true\n");
    content.push_str("deps/ linguist-vendored=true\n\n");
    
    // Make certain file types detectable
    content.push_str("# Make certain file types detectable in language stats\n");
    content.push_str("*.yaml linguist-detectable=true\n");
    content.push_str("*.yml linguist-detectable=true\n");
    content.push_str("*.json linguist-detectable=true\n");
    content.push_str("*.toml linguist-detectable=true\n");
    content.push_str("*.lock linguist-detectable=true\n\n");
    
    Ok(content)
}

fn print_summary(language_map: &HashMap<String, Vec<String>>) {
    println!("\n📊 Language Detection Summary:");
    println!("{}", "=".repeat(50));
    
    let mut languages: Vec<_> = language_map.iter().collect();
    languages.sort_by(|a, b| b.1.len().cmp(&a.1.len()));
    
    for (language, files) in languages {
        println!("{:15} {} files", language, files.len());
    }
    
    println!("\n💡 Next steps:");
    println!("1. Review the generated .gitattributes file");
    println!("2. Commit the changes to your repository");
    println!("3. GitHub will use these attributes for language statistics");
    println!("4. Use in your CI pipeline for language-specific processing");
}
