#!/bin/bash

# Comprehensive Checksum System Integration Script
# Analyzes current file distribution and provides integration plan

set -e

echo "🔍 Checksum System Integration Analysis"
echo "======================================"

# Get current file distribution
echo "📊 Current File Distribution:"
echo "-----------------------------"
git ls-files | sed 's|.*\.||' | sort | uniq -c | sort -nr
echo ""

# Analyze file types
echo "📋 File Type Analysis:"
echo "---------------------"

# Allowed source files (manual)
echo "✅ ALLOWED SOURCE FILES (Manual - No checksum needed):"
echo "   • .rs files (Rust source)"
echo "   • .jsonc files (JSON with comments)"
echo ""

# Generated files that need checksums
echo "🔧 GENERATED FILES (Need checksums):"
echo "   • .md files (Markdown documentation)"
echo "   • .toml files (Cargo/configuration)"
echo "   • .yml/.yaml files (YAML configuration)"
echo "   • .json files (JSON files)"
echo "   • .wit files (WebAssembly interface definitions)"
echo "   • .jql files (JQL query files)"
echo "   • .jsonl files (JSON Lines files)"
echo "   • .gitignore files (Git ignore files)"
echo "   • .gitattributes files (Git attributes)"
echo "   • CODEOWNERS (Code ownership file)"
echo "   • Makefile (Build configuration)"
echo "   • .editorconfig (Editor configuration)"
echo "   • .envrc (Environment configuration)"
echo ""

# Problematic files
echo "🚫 PROBLEMATIC FILES (Need attention):"
echo "   • .sh files (Should be converted to Rust)"
echo "   • .disabled files (Should be removed)"
echo "   • .pdf/.html/.epub files (Generated docs)"
echo "   • .hbs files (Handlebars templates)"
echo "   • .dot files (Graphviz files)"
echo "   • .css files (Stylesheets)"
echo "   • .sed files (Sed scripts)"
echo "   • .backup files (Backup files)"
echo ""

# Create integration plan
echo "🎯 INTEGRATION PLAN:"
echo "==================="

echo "📝 Phase 1: Update File Policy Configuration"
echo "--------------------------------------------"
echo "1. Update config/file-policy.jsonc to include all current file types"
echo "2. Add checksum support for all generated file types"
echo "3. Define header templates for each file type"
echo "4. Update generatedExtensions list"
echo ""

echo "📝 Phase 2: Create Migration Script"
echo "----------------------------------"
echo "1. Scan all generated files in repository"
echo "2. Add checksum headers to existing files"
echo "3. Validate checksums after migration"
echo "4. Create backup of original files"
echo ""

echo "📝 Phase 3: Update Generation Commands"
echo "-------------------------------------"
echo "1. Modify cargo xtask gen-files to include checksums"
echo "2. Update all existing generation functions"
echo "3. Add checksum validation to generation pipeline"
echo "4. Test with existing file types"
echo ""

echo "📝 Phase 4: Integration with Validation"
echo "--------------------------------------"
echo "1. Integrate checksum validation into cargo xtask validate-files"
echo "2. Add checksum validation to pre-commit hooks"
echo "3. Include in comprehensive validation workflows"
echo "4. Add error reporting for checksum mismatches"
echo ""

# Generate specific file type counts
echo "📊 SPECIFIC FILE TYPE COUNTS:"
echo "-----------------------------"

# Count generated files that need checksums
GENERATED_COUNT=$(git ls-files | grep -E '\.(md|toml|yml|yaml|json|wit|jql|jsonl|gitignore|gitattributes)$|^(CODEOWNERS|Makefile|\.editorconfig|\.envrc)$' | wc -l)
echo "Generated files needing checksums: $GENERATED_COUNT"

# Count allowed source files
SOURCE_COUNT=$(git ls-files | grep -E '\.(rs|jsonc)$' | wc -l)
echo "Allowed source files: $SOURCE_COUNT"

# Count problematic files
PROBLEMATIC_COUNT=$(git ls-files | grep -E '\.(sh|disabled|pdf|html|epub|hbs|dot|css|sed|backup)$' | wc -l)
echo "Problematic files: $PROBLEMATIC_COUNT"

echo ""

# Create file type mapping
echo "🗂️  FILE TYPE MAPPING FOR CHECKSUMS:"
echo "-----------------------------------"

cat << 'EOF'
{
  "fileTypes": {
    "md": {
      "header": [
        "<!-- @generated by xtask gen-files --file-type=md -->",
        "<!-- @checksum:"
      ],
      "includeChecksum": true,
      "count": 130
    },
    "toml": {
      "header": [
        "# @generated by xtask gen-files --file-type=toml",
        "# @checksum:"
      ],
      "includeChecksum": true,
      "count": 15
    },
    "yml": {
      "header": [
        "# @generated by xtask gen-files --file-type=yml",
        "# @checksum:"
      ],
      "includeChecksum": true,
      "count": 10
    },
    "yaml": {
      "header": [
        "# @generated by xtask gen-files --file-type=yaml",
        "# @checksum:"
      ],
      "includeChecksum": true,
      "count": 6
    },
    "json": {
      "header": [
        "// @generated by xtask gen-files --file-type=json",
        "// @checksum:"
      ],
      "includeChecksum": true,
      "count": 9
    },
    "wit": {
      "header": [
        ";; @generated by xtask gen-files --file-type=wit",
        ";; @checksum:"
      ],
      "includeChecksum": true,
      "count": 5
    },
    "jql": {
      "header": [
        "// @generated by xtask gen-files --file-type=jql",
        "// @checksum:"
      ],
      "includeChecksum": true,
      "count": 4
    },
    "jsonl": {
      "header": [
        "// @generated by xtask gen-files --file-type=jsonl",
        "// @checksum:"
      ],
      "includeChecksum": true,
      "count": 2
    },
    "gitignore": {
      "header": [
        "# @generated by xtask gen-files --file-type=gitignore",
        "# @checksum:"
      ],
      "includeChecksum": true,
      "count": 2
    },
    "gitattributes": {
      "header": [
        "# @generated by xtask gen-files --file-type=gitattributes",
        "# @checksum:"
      ],
      "includeChecksum": true,
      "count": 9
    },
    "CODEOWNERS": {
      "header": [
        "# @generated by xtask gen-files --file-type=CODEOWNERS",
        "# @checksum:"
      ],
      "includeChecksum": true,
      "count": 1
    },
    "Makefile": {
      "header": [
        "# @generated by xtask gen-files --file-type=makefile",
        "# @checksum:"
      ],
      "includeChecksum": true,
      "count": 1
    },
    "editorconfig": {
      "header": [
        "# @generated by xtask gen-files --file-type=editorconfig",
        "# @checksum:"
      ],
      "includeChecksum": true,
      "count": 1
    },
    "envrc": {
      "header": [
        "# @generated by xtask gen-files --file-type=envrc",
        "# @checksum:"
      ],
      "includeChecksum": true,
      "count": 2
    }
  }
}
EOF

echo ""

# Create migration script outline
echo "🔄 MIGRATION SCRIPT OUTLINE:"
echo "----------------------------"

cat << 'EOF'
#!/bin/bash
# Migration script to add checksums to existing files

# 1. Backup original files
mkdir -p backup/pre-checksum-$(date +%Y%m%d)

# 2. Process each file type
for file in $(git ls-files | grep -E '\.(md|toml|yml|yaml|json|wit|jql|jsonl|gitignore|gitattributes)$|^(CODEOWNERS|Makefile|\.editorconfig|\.envrc)$'); do
    # Backup original
    cp "$file" "backup/pre-checksum-$(date +%Y%m%d)/"
    
    # Add checksum header
    cargo run -p xtask -- add-checksum --file "$file"
done

# 3. Validate all checksums
cargo run -p xtask -- validate-checksums --strict

# 4. Report results
echo "Migration complete. Check backup/ directory for originals."
EOF

echo ""

# Next steps
echo "📋 IMMEDIATE NEXT STEPS:"
echo "-----------------------"
echo "1. ✅ Update config/file-policy.jsonc with current file types"
echo "2. ✅ Extend xtask/src/checksum.rs to handle all file types"
echo "3. ✅ Create migration script for existing files"
echo "4. ✅ Add checksum validation to cargo xtask validate-files"
echo "5. ✅ Test with a few sample files"
echo "6. ✅ Run full migration on repository"
echo ""

echo "🎯 SUCCESS METRICS:"
echo "------------------"
echo "• All 185+ generated files have checksums"
echo "• Checksum validation passes for all files"
echo "• Manual modifications are detected"
echo "• Generation pipeline includes checksums"
echo "• Pre-commit hooks validate checksums"
echo ""

echo "✅ Integration analysis complete!"
echo "Ready to proceed with implementation." 
