#!/usr/bin/env -S rustc --edition=2021 -o /tmp/run-component && /tmp/run-component

// @generated by xtask gen-config
// @checksum: {checksum}

// @generated
// This file is automatically generated. Do not edit manually.
// Generated by: Hooksmith xtask

// Simple component runner for WIT-first architecture
// Usage: rustc --edition=2021 -o /tmp/run-component scripts/run_component_simple.rs && /tmp/run-component <function> <component.wasm> [args...]

use std::env;
use std::path::Path;
use std::process::{Command, exit};

fn main() {
    let args: Vec<String> = env::args().collect();
    
    if args.len() < 3 {
        eprintln!("❌ Usage: {} <function> <component.wasm> [args...]", args[0]);
        eprintln!();
        eprintln!("📋 Available components:");
        eprintln!("  - hook-builder: Hook building and validation");
        eprintln!("  - worktree-runner: Git worktree management");
        eprintln!("  - git-filter: Git blob filtering and validation");
        eprintln!("  - validation-handler: General validation logic");
        eprintln!();
        eprintln!("💡 Examples:");
        eprintln!("  {} validate-source target/wasm32-wasip2/release/hook_builder.wasm", args[0]);
        eprintln!("  {} list-worktrees target/wasm32-wasip2/release/worktree_runner.wasm", args[0]);
        eprintln!("  {} validate-blob target/wasm32-wasip2/release/git_filter.wasm --blob test-data", args[0]);
        exit(1);
    }

    let function = &args[1];
    let component = &args[2];
    let component_args = &args[3..];

    // Check if wasmtime is available
    if Command::new("wasmtime").arg("--version").output().is_err() {
        eprintln!("❌ wasmtime is not installed or not in PATH");
        eprintln!("   Install wasmtime from: https://wasmtime.dev/");
        exit(1);
    }

    // Validate arguments
    if function.is_empty() {
        eprintln!("❌ Function name cannot be empty");
        exit(1);
    }

    if !Path::new(component).exists() {
        eprintln!("❌ Component file not found: {}", component);
        exit(1);
    }

    if !component.ends_with(".wasm") {
        eprintln!("⚠️  Warning: File does not have .wasm extension: {}", component);
    }

    println!("ℹ️  Running component: {}", component);
    println!("ℹ️  Function: {}", function);
    
    if !component_args.is_empty() {
        println!("ℹ️  Arguments: {}", component_args.join(" "));
    }

    // Build wasmtime command
    let mut cmd = Command::new("wasmtime");
    cmd.args(["run", "--invoke", function, component]);
    cmd.args(component_args);

    // Add additional wasmtime arguments if specified
    if let Ok(wasmtime_args) = env::var("WASMTIME_ARGS") {
        println!("ℹ️  Additional wasmtime args: {}", wasmtime_args);
        for arg in wasmtime_args.split_whitespace() {
            cmd.arg(arg);
        }
    }

    if env::var("VERBOSE").is_ok() {
        println!("ℹ️  Command: {:?}", cmd);
    }

    // Run the component
    let output = match cmd.output() {
        Ok(output) => output,
        Err(e) => {
            eprintln!("❌ Failed to execute wasmtime: {}", e);
            exit(1);
        }
    };

    if output.status.success() {
        println!("✅ Component executed successfully");
        if !output.stdout.is_empty() {
            print!("{}", String::from_utf8_lossy(&output.stdout));
        }
    } else {
        println!("❌ Component execution failed (exit code: {})", output.status);
        if !output.stderr.is_empty() {
            eprint!("{}", String::from_utf8_lossy(&output.stderr));
        }
        if !output.stdout.is_empty() {
            print!("{}", String::from_utf8_lossy(&output.stdout));
        }
        if env::var("STRICT").is_ok() {
            exit(output.status.code().unwrap_or(1));
        }
    }
} 
