#!/usr/bin/env -S cargo run --bin run-component --

// @generated by xtask gen-config
// @checksum: {checksum}

// @generated
// This file is automatically generated. Do not edit manually.
// Generated by: Hooksmith xtask

// Component runner for WIT-first architecture
// Usage: cargo run --bin run-component <function> <component.wasm> [args...]

use std::env;
use std::path::Path;
use std::process::{Command, ExitCode};
use anyhow::{Context, Result};
use clap::{Parser, Subcommand};

#[derive(Parser)]
#[command(
    name = "run-component",
    about = "Component runner for Hooksmith WIT components",
    version,
    long_about = "Run WIT components using wasmtime with --invoke flag"
)]
struct Cli {
    /// Function name to invoke
    #[arg(value_name = "FUNCTION")]
    function: String,

    /// Path to the WASM component file
    #[arg(value_name = "COMPONENT")]
    component: String,

    /// Additional arguments to pass to the component
    #[arg(value_name = "ARGS")]
    args: Vec<String>,

    /// Additional wasmtime arguments
    #[arg(long, env = "WASMTIME_ARGS")]
    wasmtime_args: Option<String>,

    /// Verbose output
    #[arg(short, long, env = "VERBOSE")]
    verbose: bool,

    /// Strict mode - exit on errors
    #[arg(long, env = "STRICT")]
    strict: bool,

    /// Show available components and functions
    #[arg(long)]
    list: bool,
}

#[derive(Subcommand)]
enum Commands {
    /// List available components and their functions
    List,
    
    /// Run a specific component function
    Run {
        /// Function name to invoke
        function: String,
        
        /// Path to the WASM component file
        component: String,
        
        /// Additional arguments
        args: Vec<String>,
    },
}

fn main() -> ExitCode {
    if let Err(e) = run() {
        eprintln!("❌ Error: {}", e);
        ExitCode::FAILURE
    } else {
        ExitCode::SUCCESS
    }
}

fn run() -> Result<()> {
    let cli = Cli::parse();

    // Check if wasmtime is available
    check_wasmtime()?;

    if cli.list {
        list_components()?;
        return Ok(());
    }

    // Validate arguments
    validate_args(&cli.function, &cli.component)?;

    // Run the component
    run_component(&cli)?;

    Ok(())
}

fn check_wasmtime() -> Result<()> {
    if Command::new("wasmtime")
        .arg("--version")
        .output()
        .is_err()
    {
        anyhow::bail!(
            "wasmtime is not installed or not in PATH\n\
             Install wasmtime from: https://wasmtime.dev/"
        );
    }
    Ok(())
}

fn validate_args(function: &str, component: &str) -> Result<()> {
    if function.is_empty() {
        anyhow::bail!("Function name cannot be empty");
    }

    if !Path::new(component).exists() {
        anyhow::bail!("Component file not found: {}", component);
    }

    if !component.ends_with(".wasm") {
        eprintln!("⚠️  Warning: File does not have .wasm extension: {}", component);
    }

    Ok(())
}

fn list_components() -> Result<()> {
    println!("📋 Available Hooksmith WIT Components");
    println!();

    let components = vec![
        ComponentInfo {
            name: "hook-builder",
            description: "Hook building and validation",
            functions: vec![
                "validate-source",
                "build-hook",
                "check-config",
                "generate-bindings",
            ],
            default_path: "target/wasm32-wasip2/release/hook_builder.wasm",
        },
        ComponentInfo {
            name: "worktree-runner",
            description: "Git worktree management",
            functions: vec![
                "list-worktrees",
                "create-worktree",
                "remove-worktree",
                "check-status",
            ],
            default_path: "target/wasm32-wasip2/release/worktree_runner.wasm",
        },
        ComponentInfo {
            name: "git-filter",
            description: "Git blob filtering and validation",
            functions: vec![
                "validate-blob",
                "filter-object",
                "check-contract",
                "transform-content",
            ],
            default_path: "target/wasm32-wasip2/release/git_filter.wasm",
        },
        ComponentInfo {
            name: "validation-handler",
            description: "General validation logic",
            functions: vec![
                "validate",
                "validate-file",
                "is-valid",
                "get-rules",
                "add-rule",
            ],
            default_path: "target/wasm32-wasip2/release/validation_handler.wasm",
        },
    ];

    for component in components {
        println!("🔧 {}", component.name);
        println!("   Description: {}", component.description);
        println!("   Default path: {}", component.default_path);
        println!("   Functions:");
        for func in component.functions {
            println!("     - {}", func);
        }
        println!();
    }

    println!("💡 Usage examples:");
    println!("   cargo run --bin run-component validate-source target/wasm32-wasip2/release/hook_builder.wasm --source-path src/main.rs");
    println!("   cargo run --bin run-component list-worktrees target/wasm32-wasip2/release/worktree_runner.wasm");
    println!("   cargo run --bin run-component validate-blob target/wasm32-wasip2/release/git_filter.wasm --blob test-data");
    println!("   cargo run --bin run-component validate target/wasm32-wasip2/release/validation_handler.wasm --input test");
    println!();
    println!("🔧 Environment variables:");
    println!("   WASMTIME_ARGS: Additional arguments to pass to wasmtime");
    println!("   VERBOSE: Set to 1 for verbose output");
    println!("   STRICT: Set to 1 to exit on errors");

    Ok(())
}

fn run_component(cli: &Cli) -> Result<()> {
    println!("ℹ️  Running component: {}", cli.component);
    println!("ℹ️  Function: {}", cli.function);
    
    if !cli.args.is_empty() {
        println!("ℹ️  Arguments: {}", cli.args.join(" "));
    }

    // Build wasmtime command
    let mut cmd = Command::new("wasmtime");
    cmd.args(["run", "--invoke", &cli.function, &cli.component]);
    cmd.args(&cli.args);

    // Add additional wasmtime arguments if specified
    if let Some(ref wasmtime_args) = cli.wasmtime_args {
        println!("ℹ️  Additional wasmtime args: {}", wasmtime_args);
        for arg in wasmtime_args.split_whitespace() {
            cmd.arg(arg);
        }
    }

    if cli.verbose {
        println!("ℹ️  Command: {:?}", cmd);
    }

    // Run the component
    let output = cmd.output().context("Failed to execute wasmtime")?;

    if output.status.success() {
        println!("✅ Component executed successfully");
        if !output.stdout.is_empty() {
            print!("{}", String::from_utf8_lossy(&output.stdout));
        }
    } else {
        println!("❌ Component execution failed (exit code: {})", output.status);
        if !output.stderr.is_empty() {
            eprint!("{}", String::from_utf8_lossy(&output.stderr));
        }
        if !output.stdout.is_empty() {
            print!("{}", String::from_utf8_lossy(&output.stdout));
        }
        if cli.strict {
            std::process::exit(output.status.code().unwrap_or(1));
        }
    }

    Ok(())
}

#[derive(Debug)]
struct ComponentInfo {
    name: &'static str,
    description: &'static str,
    functions: Vec<&'static str>,
    default_path: &'static str,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_validate_args() {
        // Valid arguments
        assert!(validate_args("test-function", "test.wasm").is_ok());
        
        // Invalid function name
        assert!(validate_args("", "test.wasm").is_err());
        
        // Non-existent file
        assert!(validate_args("test-function", "non-existent.wasm").is_err());
    }

    #[test]
    fn test_check_wasmtime() {
        // This test assumes wasmtime is available in the test environment
        // In a real test environment, you might want to mock this
        let result = check_wasmtime();
        // We can't guarantee wasmtime is available in all test environments
        // so we just check that it doesn't panic
    }
} 
