#!/bin/bash
# @generated by xtask gen-config
# @checksum: {checksum}

# @generated
# This file is automatically generated. Do not edit manually.
# Generated by: Hooksmith xtask

# Component runner script for WIT-first architecture
# Usage: ./scripts/run_component.sh <function> <component.wasm> [args...]

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Show usage
show_usage() {
    cat << EOF
Component Runner for Hooksmith WIT Components

Usage: $0 <function> <component.wasm> [args...]

Examples:
  $0 'validate-source' target/wasm32-wasip2/release/hook_builder.wasm --source-path src/main.rs
  $0 'list-worktrees' target/wasm32-wasip2/release/worktree_runner.wasm
  $0 'validate-blob' target/wasm32-wasip2/release/git_filter.wasm --blob test-data
  $0 'validate' target/wasm32-wasip2/release/validation_handler.wasm --input test

Available components:
  - hook-builder: Hook building and validation
  - worktree-runner: Git worktree management
  - git-filter: Git blob filtering and validation
  - validation-handler: General validation logic

Environment variables:
  WASMTIME_ARGS: Additional arguments to pass to wasmtime
  VERBOSE: Set to 1 for verbose output
  STRICT: Set to 1 to exit on errors

EOF
}

# Check if wasmtime is available
check_wasmtime() {
    if ! command -v wasmtime >/dev/null 2>&1; then
        print_error "wasmtime is not installed or not in PATH"
        print_info "Install wasmtime from: https://wasmtime.dev/"
        exit 1
    fi
}

# Validate arguments
validate_args() {
    if [ $# -lt 2 ]; then
        print_error "Insufficient arguments"
        show_usage
        exit 1
    fi

    local function_name="$1"
    local component_path="$2"

    if [ -z "$function_name" ]; then
        print_error "Function name cannot be empty"
        exit 1
    fi

    if [ ! -f "$component_path" ]; then
        print_error "Component file not found: $component_path"
        exit 1
    fi

    if [[ "$component_path" != *.wasm ]]; then
        print_warning "File does not have .wasm extension: $component_path"
    fi
}

# Run the component
run_component() {
    local function_name="$1"
    local component_path="$2"
    shift 2
    local args=("$@")

    print_info "Running component: $component_path"
    print_info "Function: $function_name"
    if [ ${#args[@]} -gt 0 ]; then
        print_info "Arguments: ${args[*]}"
    fi

    # Build wasmtime command
    local wasmtime_cmd=("wasmtime" "run" "--invoke" "$function_name" "$component_path")
    wasmtime_cmd+=("${args[@]}")

    # Add additional wasmtime arguments if specified
    if [ -n "${WASMTIME_ARGS:-}" ]; then
        print_info "Additional wasmtime args: $WASMTIME_ARGS"
        # Split WASMTIME_ARGS into array
        IFS=' ' read -ra additional_args <<< "$WASMTIME_ARGS"
        wasmtime_cmd+=("${additional_args[@]}")
    fi

    if [ "${VERBOSE:-0}" = "1" ]; then
        print_info "Command: ${wasmtime_cmd[*]}"
    fi

    # Run the component
    local exit_code=0
    local output
    output=$("${wasmtime_cmd[@]}" 2>&1) || exit_code=$?

    if [ $exit_code -eq 0 ]; then
        print_success "Component executed successfully"
        echo "$output"
    else
        print_error "Component execution failed (exit code: $exit_code)"
        echo "$output"
        if [ "${STRICT:-0}" = "1" ]; then
            exit $exit_code
        fi
    fi
}

# Main execution
main() {
    # Check if help is requested
    if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
        show_usage
        exit 0
    fi

    check_wasmtime
    validate_args "$@"
    run_component "$@"
}

# Run main function with all arguments
main "$@" 
