# @generated by xtask gen-scripts

#!/bin/bash
# Safe Pre-Push Hook
# This hook provides additional safety checks beyond git aliases
# and integrates with the clean auto-push workflow

set -e

# Colors for clean output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Icons for structured output
ICON_SUCCESS="✅"
ICON_ERROR="❌"
ICON_WARNING="⚠️"
ICON_INFO="ℹ️"
ICON_PUSH="🚀"
ICON_CHECK="🔍"
ICON_BRANCH="🌿"
ICON_SECURITY="🔒"

# Function to print styled output
print_status() {
    local status=$1
    local message=$2
    case $status in
        "success")
            echo -e "${GREEN}${ICON_SUCCESS} ${message}${NC}"
            ;;
        "error")
            echo -e "${RED}${ICON_ERROR} ${message}${NC}"
            ;;
        "warning")
            echo -e "${YELLOW}${ICON_WARNING} ${message}${NC}"
            ;;
        "info")
            echo -e "${BLUE}${ICON_INFO} ${message}${NC}"
            ;;
        "push")
            echo -e "${PURPLE}${ICON_PUSH} ${message}${NC}"
            ;;
        "check")
            echo -e "${CYAN}${ICON_CHECK} ${message}${NC}"
            ;;
        "security")
            echo -e "${RED}${ICON_SECURITY} ${message}${NC}"
            ;;
    esac
}

# Function to get current branch
get_current_branch() {
    git rev-parse --abbrev-ref HEAD
}

# Function to check if branch is protected
is_protected_branch() {
    local branch=$1
    case $branch in
        "main"|"master"|"develop"|"production")
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

# Function to check for dangerous patterns in commit messages
check_commit_messages() {
    print_status "check" "Validating commit messages..."
    
    local dangerous_patterns=(
        "WIP"
        "TODO"
        "FIXME"
        "HACK"
        "TEMP"
        "DEBUG"
        "TEST"
    )
    
    local has_dangerous_commits=false
    
    # Get commits being pushed
    while read local_ref local_sha remote_ref remote_sha; do
        if [[ "$local_sha" != "0000000000000000000000000000000000000000" ]]; then
            # Get commit messages for this push
            local commits=$(git log --format="%B" $remote_sha..$local_sha 2>/dev/null || true)
            
            for pattern in "${dangerous_patterns[@]}"; do
                if echo "$commits" | grep -qi "$pattern"; then
                    print_status "warning" "Found potentially dangerous commit message with '$pattern'"
                    has_dangerous_commits=true
                fi
            done
        fi
    done
    
    if [[ "$has_dangerous_commits" == "true" ]]; then
        print_status "warning" "Consider reviewing commit messages before pushing"
    else
        print_status "success" "All commit messages look good"
    fi
}

# Function to check for large files
check_large_files() {
    print_status "check" "Checking for large files..."
    
    local max_size_mb=50  # 50MB limit
    local large_files=()
    
    # Get files being pushed
    while read local_ref local_sha remote_ref remote_sha; do
        if [[ "$local_sha" != "0000000000000000000000000000000000000000" ]]; then
            # Get files changed in this push
            local files=$(git diff --name-only $remote_sha..$local_sha 2>/dev/null || true)
            
            for file in $files; do
                if [[ -f "$file" ]]; then
                    local size_mb=$(du -m "$file" 2>/dev/null | cut -f1 || echo "0")
                    if [[ $size_mb -gt $max_size_mb ]]; then
                        large_files+=("$file ($size_mb MB)")
                    fi
                fi
            done
        fi
    done
    
    if [[ ${#large_files[@]} -gt 0 ]]; then
        print_status "warning" "Found large files:"
        for file in "${large_files[@]}"; do
            echo "  • $file"
        done
        print_status "info" "Consider using git-lfs for large files"
    else
        print_status "success" "No large files detected"
    fi
}

# Function to check for sensitive data
check_sensitive_data() {
    print_status "check" "Checking for sensitive data..."
    
    local sensitive_patterns=(
        "password.*=.*['\"][^'\"]*['\"]"
        "secret.*=.*['\"][^'\"]*['\"]"
        "api_key.*=.*['\"][^'\"]*['\"]"
        "token.*=.*['\"][^'\"]*['\"]"
        "private_key.*=.*['\"][^'\"]*['\"]"
        "BEGIN.*PRIVATE.*KEY"
        "BEGIN.*RSA.*PRIVATE.*KEY"
        "BEGIN.*DSA.*PRIVATE.*KEY"
        "BEGIN.*EC.*PRIVATE.*KEY"
    )
    
    local has_sensitive_data=false
    
    # Get files being pushed
    while read local_ref local_sha remote_ref remote_sha; do
        if [[ "$local_sha" != "0000000000000000000000000000000000000000" ]]; then
            # Get files changed in this push
            local files=$(git diff --name-only $remote_sha..$local_sha 2>/dev/null || true)
            
            for file in $files; do
                if [[ -f "$file" ]]; then
                    for pattern in "${sensitive_patterns[@]}"; do
                        if grep -qi "$pattern" "$file" 2>/dev/null; then
                            print_status "security" "Potential sensitive data found in $file"
                            has_sensitive_data=true
                        fi
                    done
                fi
            done
        fi
    done
    
    if [[ "$has_sensitive_data" == "true" ]]; then
        print_status "error" "Sensitive data detected! Please review before pushing"
        return 1
    else
        print_status "success" "No sensitive data detected"
    fi
}

# Function to check for merge commits
check_merge_commits() {
    print_status "check" "Checking for merge commits..."
    
    local merge_commits=0
    
    # Get commits being pushed
    while read local_ref local_sha remote_ref remote_sha; do
        if [[ "$local_sha" != "0000000000000000000000000000000000000000" ]]; then
            # Count merge commits
            merge_commits=$(git log --merges --format="%H" $remote_sha..$local_sha 2>/dev/null | wc -l || echo "0")
        fi
    done
    
    if [[ $merge_commits -gt 0 ]]; then
        print_status "warning" "Found $merge_commits merge commit(s)"
        print_status "info" "Consider using rebase for cleaner history"
    else
        print_status "success" "No merge commits detected"
    fi
}

# Function to check for uncommitted changes
check_uncommitted_changes() {
    print_status "check" "Checking for uncommitted changes..."
    
    if ! git diff-index --quiet HEAD --; then
        print_status "warning" "You have uncommitted changes"
        print_status "info" "Consider committing or stashing changes before pushing"
        
        # Show uncommitted changes
        echo ""
        print_status "info" "Uncommitted changes:"
        git status --short
        echo ""
        
        read -p "Continue with push anyway? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            print_status "info" "Push cancelled"
            exit 0
        fi
    else
        print_status "success" "Working directory is clean"
    fi
}

# Function to check for force push attempts
check_force_push() {
    print_status "check" "Checking for force push attempts..."
    
    # Check if this is a force push by comparing commit counts
    while read local_ref local_sha remote_ref remote_sha; do
        if [[ "$local_sha" != "0000000000000000000000000000000000000000" ]]; then
            local local_count=$(git rev-list --count $local_sha 2>/dev/null || echo "0")
            local remote_count=$(git rev-list --count $remote_sha 2>/dev/null || echo "0")
            
            if [[ $local_count -lt $remote_count ]]; then
                print_status "security" "Force push detected!"
                print_status "error" "Force pushes are not allowed for safety"
                return 1
            fi
        fi
    done
    
    print_status "success" "No force push detected"
}

# Function to check for protected branch pushes
check_protected_branches() {
    print_status "check" "Checking protected branch access..."
    
    local current_branch=$(get_current_branch)
    
    if is_protected_branch "$current_branch"; then
        print_status "security" "Direct push to protected branch '$current_branch' detected!"
        print_status "error" "Direct pushes to protected branches are forbidden"
        print_status "info" "Use pull requests or merge requests instead"
        return 1
    fi
    
    print_status "success" "Not pushing to protected branch"
}

# Function to run xtask validation
run_xtask_validation() {
    print_status "check" "Running xtask validation..."
    
    if command -v cargo >/dev/null 2>&1; then
        if [[ -f "Cargo.toml" ]]; then
            print_status "info" "Running cargo validation..."
            
            # Run cargo check
            if cargo check --quiet; then
                print_status "success" "Cargo check passed"
            else
                print_status "error" "Cargo check failed"
                return 1
            fi
            
            # Run cargo fmt check
            if cargo fmt --check --quiet; then
                print_status "success" "Code formatting check passed"
            else
                print_status "warning" "Code formatting issues detected"
                print_status "info" "Run 'cargo fmt' to fix formatting"
            fi
            
            # Run cargo clippy if available
            if cargo clippy --quiet 2>/dev/null; then
                print_status "success" "Clippy linting passed"
            else
                print_status "warning" "Clippy linting issues detected"
            fi
        else
            print_status "info" "Not a Rust project, skipping cargo validation"
        fi
    else
        print_status "info" "Cargo not available, skipping Rust validation"
    fi
}

# Function to show push summary
show_push_summary() {
    print_status "info" "Push Summary:"
    echo "=================="
    
    local current_branch=$(get_current_branch)
    echo "🌿 Branch: $current_branch"
    
    # Count commits being pushed
    local commit_count=0
    while read local_ref local_sha remote_ref remote_sha; do
        if [[ "$local_sha" != "0000000000000000000000000000000000000000" ]]; then
            commit_count=$(git log --oneline $remote_sha..$local_sha 2>/dev/null | wc -l || echo "0")
        fi
    done
    
    echo "📝 Commits: $commit_count"
    
    # Show files being changed
    local file_count=0
    while read local_ref local_sha remote_ref remote_sha; do
        if [[ "$local_sha" != "0000000000000000000000000000000000000000" ]]; then
            file_count=$(git diff --name-only $remote_sha..$local_sha 2>/dev/null | wc -l || echo "0")
        fi
    done
    
    echo "📁 Files: $file_count"
}

# Main pre-push hook logic
main() {
    echo ""
    print_status "push" "Running pre-push safety checks..."
    echo ""
    
    # Read stdin for push information
    local push_info=$(cat)
    
    # Store push info for processing
    echo "$push_info" > /tmp/push_info.tmp
    
    # Run all checks
    local exit_code=0
    
    # Check 1: Protected branches
    if ! check_protected_branches; then
        exit_code=1
    fi
    
    # Check 2: Force push detection
    if ! check_force_push; then
        exit_code=1
    fi
    
    # Check 3: Uncommitted changes
    check_uncommitted_changes
    
    # Check 4: Commit message validation
    check_commit_messages
    
    # Check 5: Large files
    check_large_files
    
    # Check 6: Sensitive data
    if ! check_sensitive_data; then
        exit_code=1
    fi
    
    # Check 7: Merge commits
    check_merge_commits
    
    # Check 8: Xtask validation (if available)
    if [[ -f "xtask/Cargo.toml" ]]; then
        run_xtask_validation
    fi
    
    echo ""
    
    # Show push summary
    show_push_summary
    
    echo ""
    
    # Final result
    if [[ $exit_code -eq 0 ]]; then
        print_status "success" "All pre-push checks passed!"
        print_status "push" "Ready to push"
    else
        print_status "error" "Pre-push checks failed!"
        print_status "info" "Please fix the issues above before pushing"
    fi
    
    # Clean up
    rm -f /tmp/push_info.tmp
    
    exit $exit_code
}

# Process push information from stdin
while read local_ref local_sha remote_ref remote_sha; do
    # Store for processing in main function
    echo "$local_ref $local_sha $remote_ref $remote_sha" >> /tmp/push_info.tmp
done

# Run main logic
main 
