#!/bin/bash

# Simple Checksum Registry Demo
# Demonstrates the concept of checksum validation with registry

set -e

echo "🔧 Simple Checksum Registry Demo"
echo "================================"

# Create test directory
TEST_DIR="test-simple-checksum"
rm -rf "$TEST_DIR"
mkdir -p "$TEST_DIR"

echo "📁 Created test directory: $TEST_DIR"

# Function to compute SHA-256 checksum (first 8 chars)
compute_checksum() {
    local content="$1"
    echo -n "$content" | sha256sum | cut -c1-8
}

# Create sample files with checksums
echo ""
echo "📝 Creating sample files with checksums..."

# README.md
readme_content="# Hooksmith

A comprehensive Git workflow automation tool with contract validation and structured logging.

## Features

- Contract-driven validation
- Structured logging with JSONL
- WebAssembly component support
- Lefthook integration"

readme_checksum=$(compute_checksum "$readme_content")

cat > "$TEST_DIR/README.md" << EOF
<!-- @generated by xtask gen-files --file-type=md -->
<!-- @checksum: $readme_checksum -->
$readme_content
EOF

echo "✅ Created README.md with checksum: $readme_checksum"

# .gitignore
gitignore_content="target/
dist/
*.log
*.tmp
*.bak
*.lock
node_modules/"

gitignore_checksum=$(compute_checksum "$gitignore_content")

cat > "$TEST_DIR/.gitignore" << EOF
# @generated by xtask gen-files --file-type=gitignore
# @checksum: $gitignore_checksum
$gitignore_content
EOF

echo "✅ Created .gitignore with checksum: $gitignore_checksum"

# config.json
config_content='{
  "project": {
    "name": "hooksmith",
    "version": "0.1.0"
  },
  "features": {
    "contract_validation": true,
    "structured_logging": true
  }
}'

config_checksum=$(compute_checksum "$config_content")

cat > "$TEST_DIR/config.json" << EOF
// @generated by xtask gen-files --file-type=json
// @checksum: $config_checksum
$config_content
EOF

echo "✅ Created config.json with checksum: $config_checksum"

# Create checksum registry
echo ""
echo "📋 Creating checksum registry..."

cat > "$TEST_DIR/generated-files.jsonc" << EOF
{
  "\$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Hooksmith Generated Files",
  "description": "Registry of generated files with stable slugs and checksums for validation and regeneration.",
  
  // All files listed here are assumed to be generated
  "files": [
    {
      "slug": "readme",
      "path": "README.md",
      "type": "md",
      "checksum": "$readme_checksum"
    },
    {
      "slug": "gitignore",
      "path": ".gitignore",
      "type": "gitignore",
      "checksum": "$gitignore_checksum"
    },
    {
      "slug": "config-json",
      "path": "config.json",
      "type": "json",
      "checksum": "$config_checksum"
    }
  ],
  "ignore": {
    "dirs": [
      "target/",
      "dist/",
      "node_modules/"
    ],
    "patterns": [
      "*.lock",
      "*.jsonl"
    ]
  }
}
EOF

echo "✅ Created checksum registry"

# Function to validate file checksum
validate_file_checksum() {
    local file_path="$1"
    local expected_checksum="$2"
    
    echo "🔍 Validating $file_path..."
    
    # Read file content
    local content=$(cat "$file_path")
    
    # Extract content without header (first 2 lines)
    local content_without_header=$(echo "$content" | tail -n +3)
    
    # Compute actual checksum
    local actual_checksum=$(compute_checksum "$content_without_header")
    
    if [ "$actual_checksum" = "$expected_checksum" ]; then
        echo "✅ $file_path: checksum matches ($actual_checksum)"
        return 0
    else
        echo "❌ $file_path: checksum mismatch (expected: $expected_checksum, actual: $actual_checksum)"
        return 1
    fi
}

# Validate all files
echo ""
echo "🔍 Validating all generated files..."

validate_file_checksum "$TEST_DIR/README.md" "$readme_checksum"
validate_file_checksum "$TEST_DIR/.gitignore" "$gitignore_checksum"
validate_file_checksum "$TEST_DIR/config.json" "$config_checksum"

# Demonstrate tamper detection
echo ""
echo "🔧 Demonstrating tamper detection..."

echo "📝 Modifying README.md content (simulating manual edit)..."
echo "" >> "$TEST_DIR/README.md"
echo "# Manual addition - this should invalidate the checksum" >> "$TEST_DIR/README.md"

echo "🔍 Re-validating README.md..."
if validate_file_checksum "$TEST_DIR/README.md" "$readme_checksum"; then
    echo "❌ ERROR: Tamper detection failed!"
else
    echo "✅ SUCCESS: Tamper detection working correctly!"
fi

# Show file contents
echo ""
echo "📝 Generated File Examples:"
echo "=========================="
echo ""
echo "1. README.md:"
head -5 "$TEST_DIR/README.md"
echo ""
echo "2. .gitignore:"
head -5 "$TEST_DIR/.gitignore"
echo ""
echo "3. config.json:"
head -5 "$TEST_DIR/config.json"
echo ""

# Show registry structure
echo "📋 Registry Structure:"
echo "====================="
echo ""
echo "The registry contains:"
echo "• File metadata (slug, path, type)"
echo "• Checksums for validation"
echo "• Ignore rules for filtering"
echo "• JSONC format with comments"
echo ""

echo "🎯 Benefits Achieved:"
echo "===================="
echo "✅ Tamper detection: Any manual edit fails validation"
echo "✅ Deterministic builds: Checksums confirm expected content"
echo "✅ Registry source of truth: Centralized file tracking"
echo "✅ Easy regeneration: Slugs + checksums enable automation"
echo "✅ Comprehensive validation: All generated files tracked"
echo ""

echo "🔄 Complete Workflow Summary:"
echo "============================"
echo ""
echo "1. 📋 Registry Management:"
echo "   • config/generated-files.jsonc contains file metadata and checksums"
echo "   • Each file has: slug, path, type, checksum"
echo "   • Registry serves as source of truth for validation"
echo ""
echo "2. 🔧 File Generation:"
echo "   • Generate file content"
echo "   • Compute SHA-256 checksum of content"
echo "   • Add header with checksum"
echo "   • Write file to disk"
echo "   • Update registry with new checksum"
echo ""
echo "3. 🔍 Validation:"
echo "   • Read file content"
echo "   • Strip header lines"
echo "   • Compute checksum of remaining content"
echo "   • Compare with registry checksum"
echo "   • Report validation result"
echo ""
echo "4. 🛡️ Tamper Detection:"
echo "   • Any manual modification changes content checksum"
echo "   • Validation fails when checksums don't match"
echo "   • Ensures generated files remain unmodified"
echo ""

echo "🧹 Cleaning up test directory..."
rm -rf "$TEST_DIR"

echo "✅ Simple checksum registry demonstration completed!"
echo ""
echo "📚 Next Steps:"
echo "1. Integrate this workflow into cargo xtask gen-files"
echo "2. Create migration script for existing files"
echo "3. Add registry validation to pre-commit hooks"
echo "4. Implement automatic checksum updates"
echo "5. Add to CI/CD pipeline for ongoing validation" 
