#!/bin/bash

# Test Pre-commit Checksum Validation
# Demonstrates how the pre-commit hook validates checksums for generated files

set -e

echo "🔧 Testing Pre-commit Checksum Validation"
echo "========================================="

# Create test directory
TEST_DIR="test-pre-commit-checksums"
rm -rf "$TEST_DIR"
mkdir -p "$TEST_DIR"

echo "📁 Created test directory: $TEST_DIR"

# Function to compute SHA-256 checksum (first 8 chars)
compute_checksum() {
    local content="$1"
    echo -n "$content" | sha256sum | cut -c1-8
}

# Create sample files for testing
echo ""
echo "📝 Creating sample files for pre-commit testing..."

# Create a valid .gitignore file
gitignore_content="target/
dist/
*.log
*.tmp
*.bak
*.lock
node_modules/"

gitignore_checksum=$(compute_checksum "$gitignore_content")

cat > "$TEST_DIR/.gitignore" << EOF
# @generated by xtask gen-files --file-type=gitignore
# @checksum: $gitignore_checksum
$gitignore_content
EOF

echo "✅ Created valid .gitignore with checksum: $gitignore_checksum"

# Create a valid README.md file
readme_content="# Test Project

This is a test project for demonstrating pre-commit checksum validation.

## Features

- Checksum validation
- Pre-commit hooks
- Generated file tracking"

readme_checksum=$(compute_checksum "$readme_content")

cat > "$TEST_DIR/README.md" << EOF
<!-- @generated by xtask gen-files --file-type=md -->
<!-- @checksum: $readme_checksum -->
$readme_content
EOF

echo "✅ Created valid README.md with checksum: $readme_checksum"

# Create a valid .editorconfig file
editorconfig_content="root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = space
indent_size = 2

[*.rs]
indent_size = 4"

editorconfig_checksum=$(compute_checksum "$editorconfig_content")

cat > "$TEST_DIR/.editorconfig" << EOF
# @generated by xtask gen-files --file-type=editorconfig
# @checksum: $editorconfig_checksum
$editorconfig_content
EOF

echo "✅ Created valid .editorconfig with checksum: $editorconfig_checksum"

# Create a valid .envrc file
envrc_content="export RUST_LOG=info
export RUST_BACKTRACE=1
export CARGO_INCREMENTAL=1
export SCCACHE_DIR=~/.cache/sccache
export RUSTC_WRAPPER=sccache"

envrc_checksum=$(compute_checksum "$envrc_content")

cat > "$TEST_DIR/.envrc" << EOF
# @generated by xtask gen-files --file-type=envrc
# @checksum: $envrc_checksum
$envrc_content
EOF

echo "✅ Created valid .envrc with checksum: $envrc_checksum"

# Create a Rust source file (should not need checksum)
mkdir -p "$TEST_DIR/src"
cat > "$TEST_DIR/src/main.rs" << 'EOF'
fn main() {
    println!("Hello, world!");
}
EOF

echo "✅ Created Rust source file (no checksum required)"

# Create a JSONC config file (should not need checksum)
cat > "$TEST_DIR/config.jsonc" << 'EOF'
{
  "project": {
    "name": "test-project",
    "version": "0.1.0"
  }
}
EOF

echo "✅ Created JSONC config file (no checksum required)"

# Test the pre-commit validation
echo ""
echo "🔍 Testing pre-commit checksum validation..."

# Simulate the pre-commit hook by running our validation script
echo "📋 Running checksum validation on staged files..."

# Create a simple validation function
validate_file_checksum() {
    local file_path="$1"
    
    echo "🔍 Validating $file_path..."
    
    if [[ ! -f "$file_path" ]]; then
        echo "⏭️  $file_path (file not found)"
        return 0
    fi
    
    # Check if file should have checksum
    local filename=$(basename "$file_path")
    local extension="${filename##*.}"
    
    # Files that should have checksums
    local generated_extensions=("toml" "md" "yml" "yaml" "gitignore" "gitattributes" "json" "jql" "jsonl" "wit")
    local generated_no_ext=("CODEOWNERS" "Makefile" ".editorconfig" ".envrc")
    
    # Check if file should have checksum
    local should_have_checksum=false
    
    # Check extensions
    for ext in "${generated_extensions[@]}"; do
        if [[ "$extension" == "$ext" ]]; then
            should_have_checksum=true
            break
        fi
    done
    
    # Check no-extension files
    for name in "${generated_no_ext[@]}"; do
        if [[ "$filename" == "$name" ]]; then
            should_have_checksum=true
            break
        fi
    done
    
    if [[ "$should_have_checksum" == "false" ]]; then
        echo "⏭️  $file_path (no checksum required)"
        return 0
    fi
    
    # Read file content
    local content=$(cat "$file_path")
    local lines=()
    IFS=$'\n' read -d '' -r -a lines <<< "$content"
    
    # Check for generated header
    local header_found=false
    local checksum_found=false
    local expected_checksum=""
    
    if [[ ${#lines[@]} -ge 2 ]]; then
        # Check first line for generated header
        if [[ "${lines[0]}" == *"@generated by xtask gen-files"* ]]; then
            header_found=true
        fi
        
        # Check second line for checksum
        if [[ "${lines[1]}" == *"@checksum:"* ]]; then
            checksum_found=true
            # Extract checksum
            expected_checksum=$(echo "${lines[1]}" | sed 's/.*@checksum: \([a-f0-9]*\).*/\1/')
        fi
    fi
    
    if [[ "$header_found" == "false" ]]; then
        echo "❌ $file_path: Missing generated header"
        return 1
    fi
    
    if [[ "$checksum_found" == "false" ]]; then
        echo "❌ $file_path: Missing checksum header"
        return 1
    fi
    
    # Extract content without header (lines 3 onwards)
    local content_without_header=""
    if [[ ${#lines[@]} -gt 2 ]]; then
        content_without_header=$(printf '%s\n' "${lines[@]:2}")
    fi
    
    # Compute actual checksum
    local actual_checksum=$(compute_checksum "$content_without_header")
    
    if [[ "$actual_checksum" == "$expected_checksum" ]]; then
        echo "✅ $file_path (checksum valid: $actual_checksum)"
        return 0
    else
        echo "❌ $file_path: Checksum mismatch (expected: $expected_checksum, actual: $actual_checksum)"
        return 1
    fi
}

# Test validation on all files
echo ""
echo "🔍 Running validation on all test files..."

errors=0
validated_files=()

for file in "$TEST_DIR"/* "$TEST_DIR"/.*; do
    if [[ -f "$file" ]]; then
        if validate_file_checksum "$file"; then
            if [[ "$file" == *".gitignore" || "$file" == *".md" || "$file" == *".editorconfig" || "$file" == *".envrc" ]]; then
                validated_files+=("$file")
            fi
        else
            ((errors++))
        fi
    fi
done

# Test with Rust source file
echo ""
echo "🔍 Testing with Rust source file..."
if validate_file_checksum "$TEST_DIR/src/main.rs"; then
    echo "✅ Rust source file correctly identified as not requiring checksum"
else
    echo "❌ Rust source file incorrectly flagged for checksum validation"
    ((errors++))
fi

# Test with JSONC config file
echo ""
echo "🔍 Testing with JSONC config file..."
if validate_file_checksum "$TEST_DIR/config.jsonc"; then
    echo "✅ JSONC config file correctly identified as not requiring checksum"
else
    echo "❌ JSONC config file incorrectly flagged for checksum validation"
    ((errors++))
fi

# Demonstrate tamper detection
echo ""
echo "🔧 Demonstrating tamper detection..."

echo "📝 Modifying .gitignore content (simulating manual edit)..."
echo "" >> "$TEST_DIR/.gitignore"
echo "# Manual addition - this should invalidate the checksum" >> "$TEST_DIR/.gitignore"

echo "🔍 Re-validating .gitignore..."
if validate_file_checksum "$TEST_DIR/.gitignore"; then
    echo "❌ ERROR: Tamper detection failed!"
    ((errors++))
else
    echo "✅ SUCCESS: Tamper detection working correctly!"
fi

# Report results
echo ""
echo "📊 Pre-commit Validation Results:"
echo "================================"

if [[ $errors -eq 0 ]]; then
    echo "✅ All validations passed!"
    echo "   - Validated ${#validated_files[@]} generated files"
    echo "   - Correctly identified source files"
    echo "   - Tamper detection working"
else
    echo "❌ Validation failed with $errors error(s)"
fi

echo ""
echo "🎯 Pre-commit Hook Benefits:"
echo "============================"
echo "✅ Validates checksums for all generated files"
echo "✅ Detects manual modifications to generated content"
echo "✅ Ensures only .rs and .jsonc files are source files"
echo "✅ Prevents accidental commits of modified generated files"
echo "✅ Integrates with existing validation pipeline"
echo ""

echo "🔄 Pre-commit Workflow:"
echo "======================"
echo "1. File Extension Validation:"
echo "   • Only .rs and .jsonc allowed as source files"
echo "   • All other file types must be generated"
echo ""
echo "2. Checksum Validation:"
echo "   • Validates generated file headers"
echo "   • Checks checksum integrity"
echo "   • Detects manual modifications"
echo ""
echo "3. Integration:"
echo "   • Works with lefthook configuration"
echo "   • Runs on staged files only"
echo "   • Provides clear error messages"
echo ""

echo "🧹 Cleaning up test directory..."
rm -rf "$TEST_DIR"

echo "✅ Pre-commit checksum validation test completed!"
echo ""
echo "📚 Next Steps:"
echo "1. Integrate with actual lefthook configuration"
echo "2. Test with real repository files"
echo "3. Add to CI/CD pipeline"
echo "4. Create migration script for existing files"
echo "5. Update documentation" 
