#!/bin/bash

# Test .envrc and .editorconfig Integration with Checksum System
# Demonstrates how these file types work with the enhanced checksum system

set -e

echo "🔧 Testing .envrc and .editorconfig Integration"
echo "==============================================="

# Create test directory
TEST_DIR="test-envrc-editorconfig"
rm -rf "$TEST_DIR"
mkdir -p "$TEST_DIR"

echo "📁 Created test directory: $TEST_DIR"

# Function to compute SHA-256 checksum (first 8 chars)
compute_checksum() {
    local content="$1"
    echo -n "$content" | sha256sum | cut -c1-8
}

# Create .editorconfig file with checksum
echo ""
echo "📝 Creating .editorconfig with checksum..."

editorconfig_content="root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = space
indent_size = 2

[*.rs]
indent_size = 4

[*.{md,txt}]
trim_trailing_whitespace = false

[*.{toml,yml,yaml}]
indent_size = 2

[*.json]
indent_size = 2

[*.{wit,jql}]
indent_size = 2"

editorconfig_checksum=$(compute_checksum "$editorconfig_content")

cat > "$TEST_DIR/.editorconfig" << EOF
# @generated by xtask gen-files --file-type=editorconfig
# @checksum: $editorconfig_checksum
$editorconfig_content
EOF

echo "✅ Created .editorconfig with checksum: $editorconfig_checksum"

# Create .envrc file with checksum
echo ""
echo "📝 Creating .envrc with checksum..."

envrc_content="export RUST_LOG=info
export RUST_BACKTRACE=1
export CARGO_INCREMENTAL=1
export SCCACHE_DIR=~/.cache/sccache
export RUSTC_WRAPPER=sccache
export CARGO_TARGET_DIR=target
export RUSTFLAGS=\"-C target-cpu=native\"
export CARGO_PROFILE_RELEASE_OPT_LEVEL=3
export CARGO_PROFILE_RELEASE_LTO=true"

envrc_checksum=$(compute_checksum "$envrc_content")

cat > "$TEST_DIR/.envrc" << EOF
# @generated by xtask gen-files --file-type=envrc
# @checksum: $envrc_checksum
$envrc_content
EOF

echo "✅ Created .envrc with checksum: $envrc_checksum"

# Create checksum registry for these files
echo ""
echo "📋 Creating checksum registry for .envrc and .editorconfig..."

cat > "$TEST_DIR/generated-files.jsonc" << EOF
{
  "\$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Hooksmith Generated Files",
  "description": "Registry of generated files with stable slugs and checksums for validation and regeneration.",
  
  // All files listed here are assumed to be generated
  "files": [
    {
      "slug": "root-editorconfig",
      "path": ".editorconfig",
      "type": "editorconfig",
      "checksum": "$editorconfig_checksum"
    },
    {
      "slug": "root-envrc",
      "path": ".envrc",
      "type": "envrc",
      "checksum": "$envrc_checksum"
    }
  ],
  "ignore": {
    "dirs": [
      "target/",
      "dist/",
      "node_modules/"
    ],
    "patterns": [
      "*.lock",
      "*.jsonl"
    ]
  }
}
EOF

echo "✅ Created checksum registry"

# Function to validate file checksum
validate_file_checksum() {
    local file_path="$1"
    local expected_checksum="$2"
    local file_type="$3"
    
    echo "🔍 Validating $file_path..."
    
    # Read file content
    local content=$(cat "$file_path")
    
    # Extract content without header (first 2 lines)
    local content_without_header=$(echo "$content" | tail -n +3)
    
    # Compute actual checksum
    local actual_checksum=$(compute_checksum "$content_without_header")
    
    if [ "$actual_checksum" = "$expected_checksum" ]; then
        echo "✅ $file_path: checksum matches ($actual_checksum)"
        return 0
    else
        echo "❌ $file_path: checksum mismatch (expected: $expected_checksum, actual: $actual_checksum)"
        return 1
    fi
}

# Validate both files
echo ""
echo "🔍 Validating .envrc and .editorconfig files..."

validate_file_checksum "$TEST_DIR/.editorconfig" "$editorconfig_checksum" "editorconfig"
validate_file_checksum "$TEST_DIR/.envrc" "$envrc_checksum" "envrc"

# Demonstrate tamper detection for .editorconfig
echo ""
echo "🔧 Demonstrating tamper detection for .editorconfig..."

echo "📝 Modifying .editorconfig content (simulating manual edit)..."
echo "" >> "$TEST_DIR/.editorconfig"
echo "# Manual addition - this should invalidate the checksum" >> "$TEST_DIR/.editorconfig"

echo "🔍 Re-validating .editorconfig..."
if validate_file_checksum "$TEST_DIR/.editorconfig" "$editorconfig_checksum" "editorconfig"; then
    echo "❌ ERROR: Tamper detection failed!"
else
    echo "✅ SUCCESS: Tamper detection working correctly!"
fi

# Demonstrate tamper detection for .envrc
echo ""
echo "🔧 Demonstrating tamper detection for .envrc..."

echo "📝 Modifying .envrc content (simulating manual edit)..."
echo "" >> "$TEST_DIR/.envrc"
echo "export MANUAL_ADDITION=true" >> "$TEST_DIR/.envrc"

echo "🔍 Re-validating .envrc..."
if validate_file_checksum "$TEST_DIR/.envrc" "$envrc_checksum" "envrc"; then
    echo "❌ ERROR: Tamper detection failed!"
else
    echo "✅ SUCCESS: Tamper detection working correctly!"
fi

# Show file contents
echo ""
echo "📝 Generated File Examples:"
echo "=========================="
echo ""
echo "1. .editorconfig:"
head -10 "$TEST_DIR/.editorconfig"
echo ""
echo "2. .envrc:"
head -10 "$TEST_DIR/.envrc"
echo ""

# Show registry structure
echo "📋 Registry Structure:"
echo "====================="
echo ""
echo "The registry contains entries for:"
echo "• .editorconfig (editorconfig type)"
echo "• .envrc (envrc type)"
echo "• Both with appropriate checksums"
echo ""

echo "🎯 Benefits for .envrc and .editorconfig:"
echo "========================================="
echo "✅ Configuration files are tracked as generated"
echo "✅ Environment settings are validated"
echo "✅ Editor settings are protected from manual changes"
echo "✅ Consistent formatting across the project"
echo "✅ Automated generation and validation"
echo ""

echo "🔄 Integration with Existing System:"
echo "==================================="
echo ""
echo "1. File Policy Integration:"
echo "   • .editorconfig and .envrc are in generatedExtensions"
echo "   • Header templates defined for both file types"
echo "   • Checksum validation enabled"
echo ""
echo "2. Registry Integration:"
echo "   • Files tracked in config/generated-files.jsonc"
echo "   • Stable slugs for referencing"
echo "   • Checksums for validation"
echo ""
echo "3. Validation Integration:"
echo "   • Works with cargo xtask validate-files"
echo "   • Can be added to pre-commit hooks"
echo "   • Integrates with CI/CD pipeline"
echo ""

echo "📊 File Type Support Summary:"
echo "============================"
echo "✅ .editorconfig: Editor configuration files"
echo "   - Header: # @generated by xtask gen-files --file-type=editorconfig"
echo "   - Checksum: # @checksum: [hash]"
echo "   - Purpose: Consistent code formatting"
echo ""
echo "✅ .envrc: Environment configuration files"
echo "   - Header: # @generated by xtask gen-files --file-type=envrc"
echo "   - Checksum: # @checksum: [hash]"
echo "   - Purpose: Development environment setup"
echo ""

echo "🧹 Cleaning up test directory..."
rm -rf "$TEST_DIR"

echo "✅ .envrc and .editorconfig integration test completed!"
echo ""
echo "📚 Next Steps:"
echo "1. Ensure .envrc and .editorconfig are included in generation commands"
echo "2. Add to migration script for existing files"
echo "3. Include in pre-commit validation"
echo "4. Test with actual repository files"
echo "5. Add to CI/CD pipeline validation" 
