// This file is auto-generated by `cargo xtask`
// Generated file: xtask/src/event_bus.rs
// Do not edit this file manually - changes will be overwritten

use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;
use std::fs::{File, OpenOptions};
use std::io::{BufWriter, Write};
use std::path::PathBuf;
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};
use tokio::sync::broadcast;
use tokio::task::JoinHandle;
use uuid::Uuid;

/// Core event structure for Hooksmith
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HooksmithEvent {
    /// Unique event ID
    pub id: String,
    /// Event timestamp
    pub ts: DateTime<Utc>,
    /// Actor that emitted the event (e.g., "xtask-auto-push", "lefthook-pre-commit")
    pub actor: String,
    /// Event type (e.g., "validation_passed", "commit_created", "push_attempted")
    pub event: String,
    /// Optional hook context (e.g., "pre-commit", "pre-push")
    pub hook: Option<String>,
    /// Optional state machine phase (e.g., "validating", "committing", "pushing")
    pub state: Option<String>,
    /// Flexible JSON context payload
    pub context: Value,
    /// Optional error information
    pub error: Option<Value>,
    /// Session ID for grouping related events
    pub session_id: Option<String>,
    /// Event duration in milliseconds (if applicable)
    pub duration_ms: Option<u64>,
}

impl HooksmithEvent {
    /// Create a new event
    pub fn new(actor: String, event: String, context: Value) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            ts: Utc::now(),
            actor,
            event,
            hook: None,
            state: None,
            context,
            error: None,
            session_id: None,
            duration_ms: None,
        }
    }

    /// Set hook context
    pub fn with_hook(mut self, hook: String) -> Self {
        self.hook = Some(hook);
        self
    }

    /// Set state machine phase
    pub fn with_state(mut self, state: String) -> Self {
        self.state = Some(state);
        self
    }

    /// Set error information
    pub fn with_error(mut self, error: Value) -> Self {
        self.error = Some(error);
        self
    }

    /// Set session ID
    pub fn with_session_id(mut self, session_id: String) -> Self {
        self.session_id = Some(session_id);
        self
    }

    /// Set duration
    pub fn with_duration(mut self, duration: Duration) -> Self {
        self.duration_ms = Some(duration.as_millis() as u64);
        self
    }

    /// Convert to JSONL format
    pub fn to_jsonl(&self) -> Result<String> {
        Ok(serde_json::to_string(self)?)
    }
}

/// Event handler trait for processing events
pub trait EventHandler: Send + Sync {
    /// Handle an event
    fn handle_event(&mut self, event: &HooksmithEvent) -> Result<()>;
    /// Get handler name
    fn name(&self) -> &str;
    /// Check if handler should process this event
    fn should_handle(&self, event: &HooksmithEvent) -> bool {
        true
    }
}

/// Event bus configuration
#[derive(Debug, Clone)]
pub struct EventBusConfig {
    /// Whether to enable JSONL persistence
    pub enable_persistence: bool,
    /// JSONL file path
    pub jsonl_file: Option<PathBuf>,
    /// Batch size for JSONL writes
    pub batch_size: usize,
    /// Flush interval for JSONL writes (milliseconds)
    pub flush_interval_ms: u64,
    /// Broadcast channel capacity
    pub broadcast_capacity: usize,
    /// Whether to enable console output
    pub console_output: bool,
    /// Session ID for current run
    pub session_id: Option<String>,
}

impl Default for EventBusConfig {
    fn default() -> Self {
        Self {
            enable_persistence: true,
            jsonl_file: Some(PathBuf::from(".hooksmith/events.jsonl")),
            batch_size: 10,
            flush_interval_ms: 1000,
            broadcast_capacity: 1000,
            console_output: true,
            session_id: Some(Uuid::new_v4().to_string()),
        }
    }
}

/// Main event bus that handles in-memory events and optional persistence
pub struct EventBus {
    /// Configuration
    config: EventBusConfig,
    /// Broadcast channel for in-memory events
    pub broadcast_tx: broadcast::Sender<HooksmithEvent>,
    /// Event handlers
    handlers: Vec<Box<dyn EventHandler>>,
    /// JSONL writer task
    jsonl_writer: Option<JoinHandle<()>>,
    /// Event statistics
    stats: Arc<Mutex<EventStats>>,
    /// Session ID
    session_id: String,
}

/// Event statistics
#[derive(Debug, Default, Clone)]
pub struct EventStats {
    pub total_events: u64,
    pub events_by_actor: HashMap<String, u64>,
    pub events_by_type: HashMap<String, u64>,
    pub events_by_hook: HashMap<String, u64>,
    pub start_time: Option<Instant>,
}

impl EventBus {
    /// Create a new event bus
    pub fn new(config: EventBusConfig) -> Result<Self> {
        let session_id = config
            .session_id
            .clone()
            .unwrap_or_else(|| Uuid::new_v4().to_string());
        let (broadcast_tx, _) = broadcast::channel(config.broadcast_capacity);

        let mut event_bus = Self {
            config,
            broadcast_tx,
            handlers: Vec::new(),
            jsonl_writer: None,
            stats: Arc::new(Mutex::new(EventStats::default())),
            session_id,
        };

        // Start JSONL writer if persistence is enabled
        if event_bus.config.enable_persistence {
            event_bus.start_jsonl_writer()?;
        }

        Ok(event_bus)
    }

    /// Emit an event to the bus
    pub fn emit(&mut self, mut event: HooksmithEvent) -> Result<()> {
        // Set session ID if not already set
        if event.session_id.is_none() {
            event.session_id = Some(self.session_id.clone());
        }

        // Update statistics
        self.update_stats(&event)?;

        // Console output
        if self.config.console_output {
            self.print_console(&event)?;
        }

        // Broadcast to subscribers
        let _ = self.broadcast_tx.send(event.clone());

        // Process with handlers
        for handler in &mut self.handlers {
            if handler.should_handle(&event) {
                if let Err(e) = handler.handle_event(&event) {
                    eprintln!("Handler {} failed: {}", handler.name(), e);
                }
            }
        }

        Ok(())
    }

    /// Add an event handler
    pub fn add_handler(&mut self, handler: Box<dyn EventHandler>) {
        self.handlers.push(handler);
    }

    /// Create a subscriber for real-time events
    pub fn subscribe(&self) -> broadcast::Receiver<HooksmithEvent> {
        self.broadcast_tx.subscribe()
    }

    /// Get event statistics
    pub fn get_stats(&self) -> Result<EventStats> {
        Ok(self.stats.lock().unwrap().clone())
    }

    /// Get current session ID
    pub fn session_id(&self) -> &str {
        &self.session_id
    }

    /// Start JSONL writer task
    fn start_jsonl_writer(&mut self) -> Result<()> {
        if let Some(jsonl_file) = &self.config.jsonl_file {
            // Create directory if it doesn't exist
            if let Some(parent) = jsonl_file.parent() {
                std::fs::create_dir_all(parent)?;
            }

            let file = OpenOptions::new()
                .create(true)
                .append(true)
                .open(jsonl_file)?;

            let writer = Arc::new(Mutex::new(BufWriter::new(file)));
            let batch_size = self.config.batch_size;
            let flush_interval = Duration::from_millis(self.config.flush_interval_ms);
            let mut receiver = self.broadcast_tx.subscribe();

            let writer_task = tokio::spawn(async move {
                let mut batch = Vec::new();
                let mut last_flush = Instant::now();

                while let Ok(event) = receiver.recv().await {
                    batch.push(event);

                    // Flush if batch is full or interval has passed
                    if batch.len() >= batch_size || last_flush.elapsed() >= flush_interval {
                        if let Err(e) = Self::flush_batch(&writer, &mut batch).await {
                            eprintln!("JSONL writer error: {}", e);
                        }
                        last_flush = Instant::now();
                    }
                }
            });

            self.jsonl_writer = Some(writer_task);
        }

        Ok(())
    }

    /// Flush a batch of events to JSONL file
    async fn flush_batch(
        writer: &Arc<Mutex<BufWriter<File>>>,
        batch: &mut Vec<HooksmithEvent>,
    ) -> Result<()> {
        if batch.is_empty() {
            return Ok(());
        }

        let mut writer = writer.lock().unwrap();
        for event in batch.drain(..) {
            let jsonl = event.to_jsonl()?;
            writeln!(writer, "{}", jsonl)?;
        }
        writer.flush()?;

        Ok(())
    }

    /// Update event statistics
    fn update_stats(&self, event: &HooksmithEvent) -> Result<()> {
        let mut stats = self.stats.lock().unwrap();

        if stats.start_time.is_none() {
            stats.start_time = Some(Instant::now());
        }

        stats.total_events += 1;
        *stats
            .events_by_actor
            .entry(event.actor.clone())
            .or_insert(0) += 1;
        *stats.events_by_type.entry(event.event.clone()).or_insert(0) += 1;
        if let Some(hook) = &event.hook {
            *stats.events_by_hook.entry(hook.clone()).or_insert(0) += 1;
        }

        Ok(())
    }

    /// Print event to console with formatting
    fn print_console(&self, event: &HooksmithEvent) -> Result<()> {
        let event_icon = match event.event.as_str() {
            "validation_started" | "validation_passed" => "✅",
            "validation_failed" => "❌",
            "commit_created" => "📝",
            "push_attempted" | "push_success" => "🚀",
            "push_error" => "💥",
            "state_transition" => "🔄",
            _ => "📡",
        };

        let hook_icon = event.hook.as_ref().map_or("", |hook| match hook.as_str() {
            "pre-commit" => "🔍",
            "pre-push" => "🚀",
            "commit-msg" => "📝",
            _ => "⚙️",
        });

        let duration_str = if let Some(duration) = event.duration_ms {
            format!(" ({duration}ms)")
        } else {
            String::new()
        };

        println!(
            "{} {} [{}] {}: {}{}",
            event_icon,
            hook_icon,
            event.event,
            event.actor,
            serde_json::to_string_pretty(&event.context)?,
            duration_str
        );

        if let Some(error) = &event.error {
            println!("  ❌ Error: {}", serde_json::to_string_pretty(error)?);
        }

        Ok(())
    }
}

/// Global event bus instance
static mut EVENT_BUS: Option<Arc<EventBus>> = None;

/// Initialize the global event bus
pub fn init_event_bus(config: EventBusConfig) -> Result<()> {
    let event_bus = EventBus::new(config)?;
    unsafe {
        EVENT_BUS = Some(Arc::new(event_bus));
    }
    Ok(())
}

/// Get the global event bus
pub fn get_event_bus() -> Option<Arc<EventBus>> {
    unsafe { EVENT_BUS.clone() }
}

/// Emit an event using the global event bus
pub fn emit_event(event: HooksmithEvent) -> Result<()> {
    if let Some(bus) = get_event_bus() {
        // For now, we'll just broadcast the event directly
        // In a real implementation, we'd need to handle the mutable reference properly
        let _ = bus.broadcast_tx.send(event);
    }
    Ok(())
}

/// Convenience function to emit validation events
pub fn emit_validation_event(
    actor: &str,
    hook: Option<&str>,
    state: Option<&str>,
    passed: bool,
    context: Value,
) -> Result<()> {
    let event_type = if passed {
        "validation_passed"
    } else {
        "validation_failed"
    };
    let mut event = HooksmithEvent::new(actor.to_string(), event_type.to_string(), context);

    if let Some(h) = hook {
        event = event.with_hook(h.to_string());
    }
    if let Some(s) = state {
        event = event.with_state(s.to_string());
    }

    emit_event(event)
}

/// Convenience function to emit commit events
pub fn emit_commit_event(
    actor: &str,
    commit_hash: &str,
    message: &str,
    files: Vec<String>,
) -> Result<()> {
    let context = serde_json::json!({
        "commit_hash": commit_hash,
        "message": message,
        "files": files
    });

    let event = HooksmithEvent::new(actor.to_string(), "commit_created".to_string(), context);

    emit_event(event)
}

/// Convenience function to emit push events
pub fn emit_push_event(
    actor: &str,
    success: bool,
    branch: &str,
    remote: &str,
    error: Option<&str>,
) -> Result<()> {
    let event_type = if success {
        "push_success"
    } else {
        "push_error"
    };
    let mut context = serde_json::json!({
        "branch": branch,
        "remote": remote
    });

    let mut event = HooksmithEvent::new(actor.to_string(), event_type.to_string(), context);

    if let Some(err) = error {
        event = event.with_error(serde_json::json!({ "message": err }));
    }

    emit_event(event)
}

/// Convenience function to emit state transition events
pub fn emit_state_transition_event(
    actor: &str,
    from_state: &str,
    to_state: &str,
    trigger: &str,
) -> Result<()> {
    let context = serde_json::json!({
        "from_state": from_state,
        "to_state": to_state,
        "trigger": trigger
    });

    let event = HooksmithEvent::new(actor.to_string(), "state_transition".to_string(), context)
        .with_state(to_state.to_string());

    emit_event(event)
}

/// Event processor for handling events from JSONL files
pub struct EventProcessor {
    /// Event handlers
    handlers: Vec<Box<dyn EventHandler>>,
    /// Whether to replay events
    replay_mode: bool,
}

impl EventProcessor {
    /// Create a new event processor
    pub fn new(replay_mode: bool) -> Self {
        Self {
            handlers: Vec::new(),
            replay_mode,
        }
    }

    /// Add an event handler
    pub fn add_handler(&mut self, handler: Box<dyn EventHandler>) {
        self.handlers.push(handler);
    }

    /// Process events from a JSONL file
    pub fn process_file(&mut self, file_path: &PathBuf) -> Result<()> {
        let content = std::fs::read_to_string(file_path).context(format!(
            "Failed to read event file: {}",
            file_path.display()
        ))?;

        let mut events = Vec::new();
        for line in content.lines() {
            if !line.trim().is_empty() {
                if let Ok(event) = serde_json::from_str::<HooksmithEvent>(line) {
                    events.push(event);
                }
            }
        }

        println!(
            "📊 Processing {} events from {}",
            events.len(),
            file_path.display()
        );

        for event in events {
            for handler in &mut self.handlers {
                if handler.should_handle(&event) {
                    if let Err(e) = handler.handle_event(&event) {
                        eprintln!("Handler {} failed: {}", handler.name(), e);
                    }
                }
            }
        }

        Ok(())
    }

    /// Start processing events from the global event bus
    pub async fn start_processing(&mut self) -> Result<()> {
        let mut receiver = if let Some(bus) = get_event_bus() {
            bus.subscribe()
        } else {
            anyhow::bail!("Event bus not initialized");
        };

        println!("🎯 Event processor started");

        while let Ok(event) = receiver.recv().await {
            for handler in &mut self.handlers {
                if handler.should_handle(&event) {
                    if let Err(e) = handler.handle_event(&event) {
                        eprintln!("Handler {} failed: {}", handler.name(), e);
                    }
                }
            }
        }

        Ok(())
    }
}

/// Default event handlers
/// Auto-push handler
pub struct AutoPushHandler {
    /// Whether auto-push is enabled
    enabled: bool,
    /// Current validation state
    validation_passed: bool,
}

impl AutoPushHandler {
    pub fn new(enabled: bool) -> Self {
        Self {
            enabled,
            validation_passed: false,
        }
    }
}

impl EventHandler for AutoPushHandler {
    fn handle_event(&mut self, event: &HooksmithEvent) -> Result<()> {
        if !self.enabled {
            return Ok(());
        }

        match event.event.as_str() {
            "validation_passed" => {
                self.validation_passed = true;
                println!("✅ Auto-push: Validation passed, ready for commit");
            }
            "validation_failed" => {
                self.validation_passed = false;
                println!("❌ Auto-push: Validation failed, commit blocked");
            }
            "commit_created" => {
                if self.validation_passed {
                    println!("🚀 Auto-push: Commit created, attempting push");
                    // Here you would trigger the actual git push
                    emit_push_event("auto-push-handler", true, "main", "origin", None)?;
                } else {
                    println!("⚠️ Auto-push: Commit created but validation failed, skipping push");
                }
            }
            _ => {}
        }

        Ok(())
    }

    fn name(&self) -> &str {
        "auto_push"
    }

    fn should_handle(&self, event: &HooksmithEvent) -> bool {
        matches!(
            event.event.as_str(),
            "validation_passed" | "validation_failed" | "commit_created"
        )
    }
}

/// Notification handler
pub struct NotificationHandler {
    /// Whether notifications are enabled
    enabled: bool,
}

impl NotificationHandler {
    pub fn new(enabled: bool) -> Self {
        Self { enabled }
    }
}

impl EventHandler for NotificationHandler {
    fn handle_event(&mut self, event: &HooksmithEvent) -> Result<()> {
        if !self.enabled {
            return Ok(());
        }

        match event.event.as_str() {
            "push_success" => {
                println!(
                    "🎉 Notification: Push successful to {}",
                    event.context["branch"].as_str().unwrap_or("unknown")
                );
            }
            "push_error" => {
                println!(
                    "🚨 Notification: Push failed - {}",
                    event
                        .error
                        .as_ref()
                        .and_then(|e| e["message"].as_str())
                        .unwrap_or("unknown error")
                );
            }
            "validation_failed" => {
                println!(
                    "⚠️ Notification: Validation failed in {}",
                    event.hook.as_ref().unwrap_or(&"unknown".to_string())
                );
            }
            _ => {}
        }

        Ok(())
    }

    fn name(&self) -> &str {
        "notification"
    }

    fn should_handle(&self, event: &HooksmithEvent) -> bool {
        matches!(
            event.event.as_str(),
            "push_success" | "push_error" | "validation_failed"
        )
    }
}

/// Metrics handler
pub struct MetricsHandler {
    /// Performance metrics
    metrics: HashMap<String, u64>,
}

impl MetricsHandler {
    pub fn new() -> Self {
        Self {
            metrics: HashMap::new(),
        }
    }
}

impl EventHandler for MetricsHandler {
    fn handle_event(&mut self, event: &HooksmithEvent) -> Result<()> {
        // Track event counts
        *self
            .metrics
            .entry(format!("events.{}", event.event))
            .or_insert(0) += 1;

        // Track performance
        if let Some(duration) = event.duration_ms {
            let key = format!("duration.{}", event.event);
            let current = self.metrics.get(&key).unwrap_or(&0);
            self.metrics.insert(key, current + duration);
        }

        Ok(())
    }

    fn name(&self) -> &str {
        "metrics"
    }

    fn should_handle(&self, _event: &HooksmithEvent) -> bool {
        true // Track all events
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_event_creation() {
        let context = serde_json::json!({
            "branch": "main",
            "files": ["src/main.rs"]
        });

        let event = HooksmithEvent::new(
            "xtask-auto-push".to_string(),
            "validation_passed".to_string(),
            context,
        );

        assert_eq!(event.actor, "xtask-auto-push");
        assert_eq!(event.event, "validation_passed");
        assert!(event.id.len() > 0);
    }

    #[test]
    fn test_event_with_hook_and_state() {
        let context = serde_json::json!({});
        let event = HooksmithEvent::new(
            "lefthook".to_string(),
            "validation_started".to_string(),
            context,
        )
        .with_hook("pre-commit".to_string())
        .with_state("validating".to_string());

        assert_eq!(event.hook, Some("pre-commit".to_string()));
        assert_eq!(event.state, Some("validating".to_string()));
    }

    #[test]
    fn test_event_jsonl_serialization() {
        let context = serde_json::json!({
            "branch": "feature/foo"
        });

        let event = HooksmithEvent::new(
            "xtask-auto-push".to_string(),
            "commit_created".to_string(),
            context,
        );

        let jsonl = event.to_jsonl().unwrap();
        assert!(jsonl.contains("commit_created"));
        assert!(jsonl.contains("feature/foo"));
    }
}
