//! Generated File Validator
//!
//! This module provides validation logic to prevent manual modifications
//! to files that are automatically generated by xtask.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};
use std::process::Command;

/// Configuration for generated file validation
#[derive(Debug, Clone)]
pub struct GeneratedFileConfig {
    /// Whether to check staged files only
    pub staged_only: bool,
    /// Whether to exit with error on violations
    pub strict: bool,
    /// Custom error message for violations
    pub custom_message: Option<String>,
}

impl Default for GeneratedFileConfig {
    fn default() -> Self {
        Self {
            staged_only: true,
            strict: true,
            custom_message: None,
        }
    }
}

/// Result of generated file validation
#[derive(Debug, Clone)]
pub struct GeneratedFileValidationResult {
    /// Whether validation passed
    pub is_valid: bool,
    /// List of files that were manually modified
    #[allow(dead_code)]
    pub modified_files: Vec<PathBuf>,
    /// Error message if validation failed
    pub error_message: Option<String>,
}

impl GeneratedFileValidationResult {
    /// Create a successful validation result
    pub fn success() -> Self {
        Self {
            is_valid: true,
            modified_files: Vec::new(),
            error_message: None,
        }
    }

    /// Create a failed validation result
    pub fn failure(modified_files: Vec<PathBuf>, error_message: String) -> Self {
        Self {
            is_valid: false,
            modified_files,
            error_message: Some(error_message),
        }
    }
}

/// Validator for generated files
pub struct GeneratedFileValidator;

impl GeneratedFileValidator {
    /// Validate that no generated files have been manually modified
    pub fn validate(config: &GeneratedFileConfig) -> Result<GeneratedFileValidationResult> {
        let changed_files = Self::get_changed_files(config.staged_only)?;
        let generated_files = Self::get_generated_files(&changed_files)?;

        if generated_files.is_empty() {
            return Ok(GeneratedFileValidationResult::success());
        }

        let error_message = Self::format_error_message(&generated_files, config);
        let result = GeneratedFileValidationResult::failure(generated_files, error_message);

        if config.strict {
            return Err(anyhow::anyhow!(
                "{}",
                result.error_message.as_ref().unwrap()
            ));
        }

        Ok(result)
    }

    /// Get list of changed files (staged or unstaged)
    fn get_changed_files(staged_only: bool) -> Result<Vec<PathBuf>> {
        let args = if staged_only {
            vec!["diff", "--cached", "--name-only"]
        } else {
            vec!["diff", "--name-only"]
        };

        let output = Command::new("git")
            .args(&args)
            .output()
            .context("Failed to run git diff")?;

        if !output.status.success() {
            return Err(anyhow::anyhow!(
                "Git diff failed: {}",
                String::from_utf8_lossy(&output.stderr)
            ));
        }

        let files = String::from_utf8_lossy(&output.stdout)
            .lines()
            .filter(|line| !line.trim().is_empty())
            .map(PathBuf::from)
            .collect();

        Ok(files)
    }

    /// Check which files are marked as generated in .gitattributes
    fn get_generated_files(changed_files: &[PathBuf]) -> Result<Vec<PathBuf>> {
        let mut generated_files = Vec::new();

        for file in changed_files {
            if Self::is_file_generated(file)? {
                generated_files.push(file.clone());
            }
        }

        Ok(generated_files)
    }

    /// Check if a specific file is marked as generated
    fn is_file_generated(file_path: &Path) -> Result<bool> {
        let output = Command::new("git")
            .args(["check-attr", "generated", "--", file_path.to_str().unwrap()])
            .output()
            .context("Failed to run git check-attr")?;

        if !output.status.success() {
            return Err(anyhow::anyhow!(
                "Git check-attr failed: {}",
                String::from_utf8_lossy(&output.stderr)
            ));
        }

        let output_str = String::from_utf8_lossy(&output.stdout);
        Ok(output_str.contains("true"))
    }

    /// Format a user-friendly error message
    fn format_error_message(modified_files: &[PathBuf], config: &GeneratedFileConfig) -> String {
        let mut message = String::new();

        if let Some(ref custom_msg) = config.custom_message {
            message.push_str(custom_msg);
            message.push('\n');
        } else {
            message.push_str(
                "❌ The following files are generated and should not be manually modified:\n\n",
            );
        }

        for file in modified_files {
            message.push_str(&format!("  • {}\n", file.display()));
        }

        message.push_str("\n✅ Instead, regenerate them by running:\n\n");
        message.push_str("  ./xtask gen-all\n\n");
        message.push_str("Or use specific generation commands:\n");
        message.push_str("  ./xtask gen-lefthook    # for lefthook.yml\n");
        message.push_str("  ./xtask gen-docs        # for documentation\n");
        message.push_str("  ./xtask gen-mods        # for module files\n");
        message.push_str("  ./xtask gen-wit         # for WIT interfaces\n");
        message.push_str("  ./xtask gen-gitattributes # for git attributes files\n");

        message
    }

    /// Add generated file headers to files
    pub fn add_generated_headers(files: &[PathBuf]) -> Result<()> {
        for file in files {
            Self::add_generated_header(file)?;
        }
        Ok(())
    }

    /// Add a generated file header to a specific file
    pub fn add_generated_header(file_path: &Path) -> Result<()> {
        // Skip binary files
        let extension = file_path
            .extension()
            .and_then(|ext| ext.to_str())
            .unwrap_or("");
        let binary_extensions = [
            "epub", "pdf", "png", "jpg", "jpeg", "gif", "ico", "svg", "zip", "tar", "gz",
        ];

        if binary_extensions.contains(&extension) {
            // Binary files can't have text headers, so skip them
            return Ok(());
        }

        let content = std::fs::read_to_string(file_path)
            .context(format!("Failed to read file: {}", file_path.display()))?;

        // Check if header already exists
        if content.starts_with("# GENERATED FILE - DO NOT EDIT") {
            return Ok(());
        }

        // Use appropriate comment style based on file extension
        let header = if extension == "rs" {
            "// GENERATED FILE - DO NOT EDIT\n// This file is automatically generated by xtask\n// To modify this file, update the source and regenerate\n\n"
        } else {
            "# GENERATED FILE - DO NOT EDIT\n# This file is automatically generated by xtask\n# To modify this file, update the source and regenerate\n\n"
        };
        let new_content = format!("{header}{content}");

        std::fs::write(file_path, new_content)
            .context(format!("Failed to write file: {}", file_path.display()))?;

        Ok(())
    }

    /// Validate that all generated files have proper headers
    pub fn validate_headers() -> Result<GeneratedFileValidationResult> {
        let all_files = Self::get_all_tracked_files()?;
        let generated_files = Self::get_generated_files(&all_files)?;
        let mut missing_headers = Vec::new();

        for file in generated_files {
            if !Self::has_generated_header(&file)? {
                missing_headers.push(file);
            }
        }

        if missing_headers.is_empty() {
            return Ok(GeneratedFileValidationResult::success());
        }

        let error_message = format!(
            "❌ The following generated files are missing proper headers:\n\n{}\n\n✅ Add headers by running:\n\n  ./xtask add-generated-headers",
            missing_headers
                .iter()
                .map(|f| format!("  • {}", f.display()))
                .collect::<Vec<_>>()
                .join("\n")
        );

        Ok(GeneratedFileValidationResult::failure(
            missing_headers,
            error_message,
        ))
    }

    /// Get all tracked files in the repository
    fn get_all_tracked_files() -> Result<Vec<PathBuf>> {
        let output = Command::new("git")
            .args(["ls-files"])
            .output()
            .context("Failed to run git ls-files")?;

        if !output.status.success() {
            return Err(anyhow::anyhow!(
                "Git ls-files failed: {}",
                String::from_utf8_lossy(&output.stderr)
            ));
        }

        let files = String::from_utf8_lossy(&output.stdout)
            .lines()
            .filter(|line| !line.trim().is_empty())
            .map(PathBuf::from)
            .collect();

        Ok(files)
    }

    /// Check if a file has a generated header
    fn has_generated_header(file_path: &Path) -> Result<bool> {
        // Skip binary files and files that can't have traditional headers
        let extension = file_path
            .extension()
            .and_then(|ext| ext.to_str())
            .unwrap_or("");
        let binary_extensions = [
            "epub", "pdf", "png", "jpg", "jpeg", "gif", "ico", "svg", "zip", "tar", "gz",
        ];
        let no_header_extensions = ["json"];

        if binary_extensions.contains(&extension) {
            // Binary files are considered to have headers (they can't have text headers)
            return Ok(true);
        }

        if no_header_extensions.contains(&extension) {
            // Files that can't have traditional headers are considered to have headers
            return Ok(true);
        }

        let content = std::fs::read_to_string(file_path)
            .context(format!("Failed to read file: {}", file_path.display()))?;

        // Check for multiple comment styles
        Ok(content.starts_with("# GENERATED FILE - DO NOT EDIT")
            || content.starts_with("// GENERATED FILE - DO NOT EDIT")
            || content.starts_with("<!-- This file is auto-generated"))
    }

    /// Get list of all generated files in the repository
    pub fn get_all_generated_files() -> Result<Vec<PathBuf>> {
        let all_files = Self::get_all_tracked_files()?;
        Self::get_generated_files(&all_files)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn test_generated_header_detection() {
        let temp_dir = TempDir::new().unwrap();
        let file_path = temp_dir.path().join("test.rs");

        // Test file without header
        fs::write(&file_path, "fn main() {}").unwrap();
        assert!(!GeneratedFileValidator::has_generated_header(&file_path).unwrap());

        // Test file with header
        let content_with_header = "# GENERATED FILE - DO NOT EDIT\nfn main() {}";
        fs::write(&file_path, content_with_header).unwrap();
        assert!(GeneratedFileValidator::has_generated_header(&file_path).unwrap());
    }

    #[test]
    fn test_error_message_formatting() {
        let files = vec![
            PathBuf::from("lefthook.yml"),
            PathBuf::from("docs/README.md"),
        ];
        let config = GeneratedFileConfig::default();
        let message = GeneratedFileValidator::format_error_message(&files, &config);

        assert!(message.contains("❌ The following files are generated"));
        assert!(message.contains("lefthook.yml"));
        assert!(message.contains("docs/README.md"));
        assert!(message.contains("./xtask gen-all"));
    }
}
