//! Project Status Tracking
//!
//! This module tracks the percentage of files that are either:
//! - Rust source files (.rs)
//! - Code-generated files that originate from Rust
//!
//! The goal is to achieve 100% Rust-owned coverage where all non-Rust files
//! are generated by the Rust pipeline.

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use std::process::Command;

/// File status information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileStatus {
    /// File path
    pub path: String,
    /// File extension
    pub extension: String,
    /// Whether it's a Rust source file
    pub is_rust: bool,
    /// Whether it's marked as generated
    pub is_generated: bool,
    /// Whether it's manually maintained
    pub is_manual: bool,
    /// File category
    pub category: FileCategory,
}

/// File categories
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum FileCategory {
    /// Rust source files
    Rust,
    /// Generated files (from Rust pipeline)
    Generated,
    /// Manual files (need migration)
    Manual,
}

/// Project status statistics
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectStatus {
    /// Total number of tracked files
    pub total_files: usize,
    /// Number of Rust source files
    pub rust_files: usize,
    /// Number of generated files
    pub generated_files: usize,
    /// Number of manual files
    pub manual_files: usize,
    /// Rust-owned coverage percentage
    pub rust_owned_coverage: f64,
    /// Goal coverage percentage
    pub goal_coverage: f64,
    /// Whether the goal is met
    pub goal_met: bool,
    /// File type breakdown
    pub file_type_breakdown: HashMap<String, FileTypeStats>,
    /// Manual files that should be migrated
    pub manual_files_to_migrate: Vec<String>,
}

/// File type statistics
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileTypeStats {
    /// File extension
    pub extension: String,
    /// Total count
    pub total: usize,
    /// Generated count
    pub generated: usize,
    /// Manual count
    pub manual: usize,
    /// Rust count
    pub rust: usize,
}

/// File type migration status
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum MigrationStatus {
    /// Keep as-is (.rs files)
    Keep,
    /// Generate from Rust (.md, .toml, .yml)
    Generate,
    /// Remove entirely (.sh, .shellcheckrc)
    Remove,
    /// Consolidate to another format (.pdf -> .md + CI)
    Consolidate,
}

/// File type information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileTypeInfo {
    /// File extension
    pub extension: String,
    /// Total count
    pub count: usize,
    /// Whether it's generated
    pub is_generated: bool,
    /// Migration status
    pub migration_status: MigrationStatus,
    /// Target action description
    pub target_action: String,
    /// Priority (1-10, higher = more important)
    pub priority: u8,
    /// Estimated effort
    pub estimated_effort: String,
}

/// File type migration progress
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileTypeMigrationProgress {
    /// Total file types
    pub total_types: usize,
    /// Approved types (keep)
    pub approved_types: usize,
    /// Types to generate
    pub types_to_generate: usize,
    /// Types to remove
    pub types_to_remove: usize,
    /// Types to consolidate
    pub types_to_consolidate: usize,
    /// Migration progress percentage
    pub migration_progress: f64,
    /// File type details
    pub file_types: Vec<FileTypeInfo>,
    /// Migration recommendations
    pub recommendations: Vec<String>,
}

/// Status command configuration
#[derive(Debug, Clone)]
pub struct StatusConfig {
    /// Goal coverage percentage
    pub goal_coverage: f64,
    /// Whether to show detailed breakdown
    pub detailed: bool,
    /// Whether to show manual files to migrate
    pub show_migration_targets: bool,
    /// Whether to fail if goal not met
    pub strict: bool,
    /// Output format
    pub format: OutputFormat,
}

/// Output format options
#[derive(Debug, Clone)]
pub enum OutputFormat {
    /// Human-readable table
    Table,
    /// JSON output
    Json,
    /// Markdown output
    Markdown,
}

impl Default for StatusConfig {
    fn default() -> Self {
        Self {
            goal_coverage: 80.0,
            detailed: false,
            show_migration_targets: true,
            strict: false,
            format: OutputFormat::Table,
        }
    }
}

/// Status command CLI
#[derive(Parser)]
#[command(name = "status")]
#[command(about = "Track Rust-owned project files and coverage")]
pub struct StatusCli {
    #[command(subcommand)]
    command: StatusCommands,
}

#[derive(Subcommand)]
pub enum StatusCommands {
    /// Generate project status report
    Report {
        /// Goal coverage percentage
        #[arg(long, default_value = "80.0")]
        goal: f64,
        /// Show detailed breakdown
        #[arg(long)]
        detailed: bool,
        /// Show manual files to migrate
        #[arg(long)]
        migration_targets: bool,
        /// Fail if goal not met
        #[arg(long)]
        strict: bool,
        /// Output format (table, json, markdown)
        #[arg(long, default_value = "table")]
        format: String,
    },
    /// Generate status badge for CI
    Badge {
        /// Goal coverage percentage
        #[arg(long, default_value = "80.0")]
        goal: f64,
        /// Output file path
        #[arg(long, default_value = "status-badge.json")]
        output: String,
    },
    /// Track status over time
    Trend {
        /// Output directory for trend data
        #[arg(long, default_value = "status-trends")]
        output_dir: String,
    },
    /// Show file type breakdown
    FileTypes {
        /// Show detailed breakdown
        #[arg(long)]
        detailed: bool,
        /// Output format (table, json, markdown)
        #[arg(long, default_value = "table")]
        format: String,
    },
    /// Show migration progress
    MigrationProgress {
        /// Show detailed breakdown
        #[arg(long)]
        detailed: bool,
        /// Output format (table, json, markdown)
        #[arg(long, default_value = "table")]
        format: String,
    },
    /// Generate migration scripts
    GenerateMigrationScripts {
        /// Output directory for scripts
        #[arg(long, default_value = "migration-scripts")]
        output_dir: String,
        /// Include all file types (not just high priority)
        #[arg(long)]
        all_types: bool,
    },
}

/// Run a status command
pub async fn run_status_command(command: StatusCommands) -> Result<()> {
    match command {
        StatusCommands::Report {
            goal,
            detailed,
            migration_targets,
            strict,
            format,
        } => {
            let config = StatusConfig {
                goal_coverage: goal,
                detailed,
                show_migration_targets: migration_targets,
                strict,
                format: parse_output_format(&format)?,
            };
            generate_status_report(config).await
        }
        StatusCommands::Badge { goal, output } => generate_status_badge(goal, &output).await,
        StatusCommands::Trend { output_dir } => track_status_trend(&output_dir).await,
        StatusCommands::FileTypes { detailed, format } => {
            let format = parse_output_format(&format)?;
            analyze_file_types(detailed, format).await
        }
        StatusCommands::MigrationProgress { detailed, format } => {
            let format = parse_output_format(&format)?;
            analyze_migration_progress(detailed, format).await
        }
        StatusCommands::GenerateMigrationScripts { output_dir, all_types } => {
            generate_migration_scripts(&output_dir, all_types).await
        }
    }
}

/// Generate project status report
async fn generate_status_report(config: StatusConfig) -> Result<()> {
    println!("📊 Hooksmith Project Status Report");
    println!("===================================");

    let status = analyze_project_status(config.goal_coverage).await?;

    match config.format {
        OutputFormat::Table => print_status_table(&status, &config)?,
        OutputFormat::Json => print_status_json(&status)?,
        OutputFormat::Markdown => print_status_markdown(&status, &config)?,
    }

    if config.strict && !status.goal_met {
        anyhow::bail!(
            "Goal not met: {}% coverage (goal: {}%)",
            status.rust_owned_coverage,
            config.goal_coverage
        );
    }

    Ok(())
}

/// Analyze project status
async fn analyze_project_status(goal_coverage: f64) -> Result<ProjectStatus> {
    let tracked_files = get_tracked_files().await?;
    let mut file_statuses = Vec::new();

    for file_path in tracked_files {
        let status = analyze_file_status(&file_path).await?;
        file_statuses.push(status);
    }

    // Count files by category
    let mut rust_files = 0;
    let mut generated_files = 0;
    let mut manual_files = 0;
    let mut file_type_breakdown: HashMap<String, FileTypeStats> = HashMap::new();
    let mut manual_files_to_migrate = Vec::new();

    for status in &file_statuses {
        match status.category {
            FileCategory::Rust => rust_files += 1,
            FileCategory::Generated => generated_files += 1,
            FileCategory::Manual => {
                manual_files += 1;
                if !status.is_rust {
                    manual_files_to_migrate.push(status.path.clone());
                }
            }
        }

        // Update file type breakdown
        let stats = file_type_breakdown
            .entry(status.extension.clone())
            .or_insert(FileTypeStats {
                extension: status.extension.clone(),
                total: 0,
                generated: 0,
                manual: 0,
                rust: 0,
            });

        stats.total += 1;
        match status.category {
            FileCategory::Rust => stats.rust += 1,
            FileCategory::Generated => stats.generated += 1,
            FileCategory::Manual => stats.manual += 1,
        }
    }

    let total_files = file_statuses.len();
    let rust_owned_coverage = if total_files > 0 {
        ((rust_files + generated_files) as f64 / total_files as f64) * 100.0
    } else {
        0.0
    };

    let goal_met = rust_owned_coverage >= goal_coverage;

    Ok(ProjectStatus {
        total_files,
        rust_files,
        generated_files,
        manual_files,
        rust_owned_coverage,
        goal_coverage,
        goal_met,
        file_type_breakdown,
        manual_files_to_migrate,
    })
}

/// Get all tracked files from git
async fn get_tracked_files() -> Result<Vec<String>> {
    let output = Command::new("git")
        .args(["ls-files"])
        .output()
        .context("Failed to run git ls-files")?;

    if !output.status.success() {
        anyhow::bail!("git ls-files failed");
    }

    let files = String::from_utf8_lossy(&output.stdout)
        .lines()
        .map(|s| s.to_string())
        .collect();

    Ok(files)
}

/// Analyze status of a single file
async fn analyze_file_status(file_path: &str) -> Result<FileStatus> {
    let path = Path::new(file_path);
    let extension = path
        .extension()
        .and_then(|ext| ext.to_str())
        .unwrap_or("")
        .to_lowercase();

    let is_rust = extension == "rs";
    let is_generated = check_if_generated(file_path).await?;
    let is_manual = !is_rust && !is_generated;

    let category = if is_rust {
        FileCategory::Rust
    } else if is_generated {
        FileCategory::Generated
    } else {
        FileCategory::Manual
    };

    Ok(FileStatus {
        path: file_path.to_string(),
        extension,
        is_rust,
        is_generated,
        is_manual,
        category,
    })
}

/// Check if a file is marked as generated
async fn check_if_generated(file_path: &str) -> Result<bool> {
    let output = Command::new("git")
        .args(["check-attr", "linguist-generated", file_path])
        .output()
        .context("Failed to check file attributes")?;

    if !output.status.success() {
        return Ok(false);
    }

    let output_str = String::from_utf8_lossy(&output.stdout);
    Ok(output_str.contains("linguist-generated: true"))
}

/// Print status as table
fn print_status_table(status: &ProjectStatus, config: &StatusConfig) -> Result<()> {
    println!("\n📈 Coverage Summary");
    println!("==================");
    println!("{:<30} {:>10} {:>8}", "Metric", "Count", "Percentage");
    println!(
        "{:<30} {:>10} {:>8}",
        "Total tracked files", status.total_files, "100.0%"
    );
    println!(
        "{:<30} {:>10} {:>8.1}%",
        "Rust source files (.rs)",
        status.rust_files,
        if status.total_files > 0 {
            (status.rust_files as f64 / status.total_files as f64) * 100.0
        } else {
            0.0
        }
    );
    println!(
        "{:<30} {:>10} {:>8.1}%",
        "Generated files",
        status.generated_files,
        if status.total_files > 0 {
            (status.generated_files as f64 / status.total_files as f64) * 100.0
        } else {
            0.0
        }
    );
    println!(
        "{:<30} {:>10} {:>8.1}%",
        "Manual files",
        status.manual_files,
        if status.total_files > 0 {
            (status.manual_files as f64 / status.total_files as f64) * 100.0
        } else {
            0.0
        }
    );
    println!(
        "{:<30} {:>10} {:>8.1}%",
        "Rust-owned coverage",
        format!(
            "{}/{}",
            status.rust_files + status.generated_files,
            status.total_files
        ),
        status.rust_owned_coverage
    );
    println!("{:<30} {:>10} {:>8.1}%", "Goal", "", status.goal_coverage);

    if status.goal_met {
        println!(
            "\n✅ Goal met! Rust-owned coverage: {:.1}%",
            status.rust_owned_coverage
        );
    } else {
        println!(
            "\n❌ Goal not met. Rust-owned coverage: {:.1}% (goal: {:.1}%)",
            status.rust_owned_coverage, status.goal_coverage
        );
    }

    if config.detailed {
        print_detailed_breakdown(status)?;
    }

    if config.show_migration_targets && !status.manual_files_to_migrate.is_empty() {
        print_migration_targets(status)?;
    }

    Ok(())
}

/// Print detailed file type breakdown
fn print_detailed_breakdown(status: &ProjectStatus) -> Result<()> {
    println!("\n📋 File Type Breakdown");
    println!("=====================");
    println!(
        "{:<10} {:<8} {:<8} {:<8} {:<8}",
        "Extension", "Total", "Rust", "Generated", "Manual"
    );
    println!(
        "{:<10} {:<8} {:<8} {:<8} {:<8}",
        "---------", "-----", "----", "---------", "------"
    );

    let mut extensions: Vec<_> = status.file_type_breakdown.keys().collect();
    extensions.sort();

    for extension in extensions {
        let stats = &status.file_type_breakdown[extension];
        println!(
            "{:<10} {:<8} {:<8} {:<8} {:<8}",
            stats.extension, stats.total, stats.rust, stats.generated, stats.manual
        );
    }

    Ok(())
}

/// Print migration targets
fn print_migration_targets(status: &ProjectStatus) -> Result<()> {
    println!("\n🎯 Migration Targets");
    println!("===================");
    println!(
        "The following {} manual files should be migrated to generation:",
        status.manual_files_to_migrate.len()
    );

    for file in &status.manual_files_to_migrate {
        println!("  • {}", file);
    }

    Ok(())
}

/// Print status as JSON
fn print_status_json(status: &ProjectStatus) -> Result<()> {
    let json = serde_json::to_string_pretty(status)?;
    println!("{}", json);
    Ok(())
}

/// Print status as Markdown
fn print_status_markdown(status: &ProjectStatus, config: &StatusConfig) -> Result<()> {
    println!("# Hooksmith Project Status Report\n");

    println!("## Coverage Summary\n");
    println!("| Metric | Count | Percentage |");
    println!("|--------|-------|------------|");
    println!("| Total tracked files | {} | 100.0% |", status.total_files);
    println!(
        "| Rust source files (.rs) | {} | {:.1}% |",
        status.rust_files,
        if status.total_files > 0 {
            (status.rust_files as f64 / status.total_files as f64) * 100.0
        } else {
            0.0
        }
    );
    println!(
        "| Generated files | {} | {:.1}% |",
        status.generated_files,
        if status.total_files > 0 {
            (status.generated_files as f64 / status.total_files as f64) * 100.0
        } else {
            0.0
        }
    );
    println!(
        "| Manual files | {} | {:.1}% |",
        status.manual_files,
        if status.total_files > 0 {
            (status.manual_files as f64 / status.total_files as f64) * 100.0
        } else {
            0.0
        }
    );
    println!(
        "| **Rust-owned coverage** | **{}/{}** | **{:.1}%** |",
        status.rust_files + status.generated_files,
        status.total_files,
        status.rust_owned_coverage
    );
    println!("| Goal | | {:.1}% |", status.goal_coverage);

    if status.goal_met {
        println!(
            "\n✅ **Goal met!** Rust-owned coverage: {:.1}%",
            status.rust_owned_coverage
        );
    } else {
        println!(
            "\n❌ **Goal not met.** Rust-owned coverage: {:.1}% (goal: {:.1}%)",
            status.rust_owned_coverage, status.goal_coverage
        );
    }

    if config.detailed {
        print_markdown_breakdown(status)?;
    }

    if config.show_migration_targets && !status.manual_files_to_migrate.is_empty() {
        print_markdown_migration_targets(status)?;
    }

    Ok(())
}

/// Print detailed breakdown in Markdown
fn print_markdown_breakdown(status: &ProjectStatus) -> Result<()> {
    println!("\n## File Type Breakdown\n");
    println!("| Extension | Total | Rust | Generated | Manual |");
    println!("|-----------|-------|------|-----------|--------|");

    let mut extensions: Vec<_> = status.file_type_breakdown.keys().collect();
    extensions.sort();

    for extension in extensions {
        let stats = &status.file_type_breakdown[extension];
        println!(
            "| {} | {} | {} | {} | {} |",
            stats.extension, stats.total, stats.rust, stats.generated, stats.manual
        );
    }

    Ok(())
}

/// Print migration targets in Markdown
fn print_markdown_migration_targets(status: &ProjectStatus) -> Result<()> {
    println!("\n## Migration Targets\n");
    println!(
        "The following {} manual files should be migrated to generation:\n",
        status.manual_files_to_migrate.len()
    );

    for file in &status.manual_files_to_migrate {
        println!("- `{}`", file);
    }

    Ok(())
}

/// Generate status badge for CI
async fn generate_status_badge(goal: f64, output_path: &str) -> Result<()> {
    let status = analyze_project_status(goal).await?;

    let badge_data = serde_json::json!({
        "schemaVersion": 1,
        "label": "rust-owned",
        "message": format!("{:.1}%", status.rust_owned_coverage),
        "color": if status.goal_met { "brightgreen" } else { "red" },
        "namedLogo": "rust"
    });

    // Add codegen marker to JSON content
    let mut json_content = serde_json::to_string_pretty(&badge_data)?;
    add_json_codegen_marker(&mut json_content, output_path);

    std::fs::write(output_path, json_content)?;
    println!("✅ Status badge written to: {}", output_path);

    Ok(())
}

/// Track status over time
async fn track_status_trend(output_dir: &str) -> Result<()> {
    let status = analyze_project_status(80.0).await?;

    // Create output directory if it doesn't exist
    std::fs::create_dir_all(output_dir)?;

    // Generate timestamp
    let timestamp = chrono::Utc::now();
    let date_str = timestamp.format("%Y-%m-%d").to_string();

    // Create trend data
    let trend_data = serde_json::json!({
        "date": date_str,
        "timestamp": timestamp.to_rfc3339(),
        "coverage": status.rust_owned_coverage,
        "total_files": status.total_files,
        "rust_files": status.rust_files,
        "generated_files": status.generated_files,
        "manual_files": status.manual_files
    });

    let output_path = format!("{}/status-{}.json", output_dir, date_str);

    // Add codegen marker to JSON content
    let mut json_content = serde_json::to_string_pretty(&trend_data)?;
    add_json_codegen_marker(&mut json_content, &output_path);

    std::fs::write(&output_path, json_content)?;

    println!("✅ Trend data written to: {}", output_path);

    Ok(())
}

/// Parse output format from string
fn parse_output_format(format: &str) -> Result<OutputFormat> {
    match format.to_lowercase().as_str() {
        "table" => Ok(OutputFormat::Table),
        "json" => Ok(OutputFormat::Json),
        "markdown" => Ok(OutputFormat::Markdown),
        _ => anyhow::bail!("Unknown output format: {}", format),
    }
}

/// Add JSON codegen marker to JSON content
fn add_json_codegen_marker(content: &mut String, file_path: &str) {
    let marker = format!(
        "// This file is auto-generated by `cargo xtask status`\n// Generated file: {}\n// Do not edit this file manually - changes will be overwritten\n\n",
        file_path
    );
    content.insert_str(0, &marker);
}

/// Analyze file types and their migration status
async fn analyze_file_types(detailed: bool, format: OutputFormat) -> Result<()> {
    println!("📁 Hooksmith File Type Analysis");
    println!("===============================");

    let file_types = get_file_type_analysis().await?;

    match format {
        OutputFormat::Table => print_file_types_table(&file_types, detailed)?,
        OutputFormat::Json => print_file_types_json(&file_types)?,
        OutputFormat::Markdown => print_file_types_markdown(&file_types, detailed)?,
    }

    Ok(())
}

/// Analyze migration progress
async fn analyze_migration_progress(detailed: bool, format: OutputFormat) -> Result<()> {
    println!("🔄 Hooksmith File Type Migration Progress");
    println!("=========================================");

    let progress = get_migration_progress().await?;

    match format {
        OutputFormat::Table => print_migration_progress_table(&progress, detailed)?,
        OutputFormat::Json => print_migration_progress_json(&progress)?,
        OutputFormat::Markdown => print_migration_progress_markdown(&progress, detailed)?,
    }

    Ok(())
}

/// Get file type analysis
async fn get_file_type_analysis() -> Result<Vec<FileTypeInfo>> {
    let files = get_tracked_files().await?;
    let mut extension_counts: HashMap<String, usize> = HashMap::new();
    let mut generated_extensions: HashSet<String> = HashSet::new();

    // Count files by extension
    for file in &files {
        if let Some(ext) = std::path::Path::new(file).extension() {
            let ext_str = ext.to_string_lossy().to_string();
            *extension_counts.entry(ext_str.clone()).or_insert(0) += 1;
            
            // Check if file is generated
            if check_if_generated(file).await? {
                generated_extensions.insert(ext_str);
            }
        }
    }

    // Create file type info
    let mut file_types = Vec::new();
    for (extension, count) in extension_counts {
        let (migration_status, target_action, priority, estimated_effort) = 
            get_migration_info(&extension, count);
        
        file_types.push(FileTypeInfo {
            extension: extension.clone(),
            count,
            is_generated: generated_extensions.contains(&extension),
            migration_status,
            target_action,
            priority,
            estimated_effort,
        });
    }

    // Sort by priority (highest first)
    file_types.sort_by(|a, b| b.priority.cmp(&a.priority));

    Ok(file_types)
}

/// Get migration progress
async fn get_migration_progress() -> Result<FileTypeMigrationProgress> {
    let file_types = get_file_type_analysis().await?;
    
    let mut approved_types = 0;
    let mut types_to_generate = 0;
    let mut types_to_remove = 0;
    let mut types_to_consolidate = 0;

    for file_type in &file_types {
        match file_type.migration_status {
            MigrationStatus::Keep => approved_types += 1,
            MigrationStatus::Generate => types_to_generate += 1,
            MigrationStatus::Remove => types_to_remove += 1,
            MigrationStatus::Consolidate => types_to_consolidate += 1,
        }
    }

    let total_types = file_types.len();
    let migration_progress = if total_types > 0 {
        (approved_types as f64 / total_types as f64) * 100.0
    } else {
        0.0
    };

    let recommendations = generate_migration_recommendations(&file_types);

    Ok(FileTypeMigrationProgress {
        total_types,
        approved_types,
        types_to_generate,
        types_to_remove,
        types_to_consolidate,
        migration_progress,
        file_types,
        recommendations,
    })
}

/// Get migration information for a file extension
fn get_migration_info(extension: &str, _count: usize) -> (MigrationStatus, String, u8, String) {
    match extension {
        "rs" => (MigrationStatus::Keep, "Keep as Rust source".to_string(), 1, "N/A".to_string()),
        "md" => (MigrationStatus::Generate, "Generate from Rust doc comments".to_string(), 8, "Medium".to_string()),
        "toml" => (MigrationStatus::Generate, "Generate from workspace config".to_string(), 7, "Low".to_string()),
        "yml" | "yaml" => (MigrationStatus::Generate, "Generate from Rust structs".to_string(), 6, "Medium".to_string()),
        "json" => (MigrationStatus::Generate, "Generate from Rust structs with serde".to_string(), 5, "Low".to_string()),
        "wit" => (MigrationStatus::Generate, "Generate from Rust types using wit-bindgen".to_string(), 4, "Medium".to_string()),
        "gitattributes" | "gitignore" => (MigrationStatus::Generate, "Generate at bootstrap".to_string(), 3, "Low".to_string()),
        "sh" | "shellcheckrc" => (MigrationStatus::Remove, "Replace with xtask commands".to_string(), 9, "High".to_string()),
        "pdf" | "html" | "epub" => (MigrationStatus::Consolidate, "Generate in CI from .md".to_string(), 2, "Medium".to_string()),
        "dot" | "hbs" | "css" => (MigrationStatus::Consolidate, "Generate via schema + pretty-printer".to_string(), 2, "Medium".to_string()),
        "CODEOWNERS" => (MigrationStatus::Generate, "Generate from team config".to_string(), 3, "Low".to_string()),
        _ => (MigrationStatus::Remove, "Remove or consolidate".to_string(), 10, "High".to_string()),
    }
}

/// Generate migration recommendations
fn generate_migration_recommendations(file_types: &[FileTypeInfo]) -> Vec<String> {
    let mut recommendations = Vec::new();
    
    // High priority items
    let high_priority: Vec<_> = file_types.iter()
        .filter(|ft| ft.priority >= 8)
        .collect();
    
    if !high_priority.is_empty() {
        recommendations.push(format!("High priority: Migrate {} file types (priority 8+)", high_priority.len()));
    }

    // Shell scripts
    let shell_files: Vec<_> = file_types.iter()
        .filter(|ft| ft.extension == "sh" || ft.extension == "shellcheckrc")
        .collect();
    
    if !shell_files.is_empty() {
        recommendations.push("Replace shell scripts with xtask commands".to_string());
    }

    // Documentation consolidation
    let doc_files: Vec<_> = file_types.iter()
        .filter(|ft| ft.extension == "pdf" || ft.extension == "html" || ft.extension == "epub")
        .collect();
    
    if !doc_files.is_empty() {
        recommendations.push("Consolidate documentation formats to .md + CI generation".to_string());
    }

    // Generated files
    let manual_files: Vec<_> = file_types.iter()
        .filter(|ft| !ft.is_generated && ft.migration_status != MigrationStatus::Keep)
        .collect();
    
    if !manual_files.is_empty() {
        recommendations.push(format!("Convert {} manual files to generated from Rust", manual_files.len()));
    }

    if recommendations.is_empty() {
        recommendations.push("All file types are properly managed!".to_string());
    }

    recommendations
}

/// Print file types table
fn print_file_types_table(file_types: &[FileTypeInfo], detailed: bool) -> Result<()> {
    println!("\n📊 File Type Breakdown");
    println!("======================");
    println!("{:<15} {:<8} {:<12} {:<15} {:<10}", "Extension", "Count", "Generated", "Status", "Priority");
    println!("{:-<15} {:-<8} {:-<12} {:-<15} {:-<10}", "", "", "", "", "");

    for file_type in file_types {
        let status = match file_type.migration_status {
            MigrationStatus::Keep => "Keep",
            MigrationStatus::Generate => "Generate",
            MigrationStatus::Remove => "Remove",
            MigrationStatus::Consolidate => "Consolidate",
        };

        println!(
            "{:<15} {:<8} {:<12} {:<15} {:<10}",
            file_type.extension,
            file_type.count,
            if file_type.is_generated { "Yes" } else { "No" },
            status,
            file_type.priority
        );
    }

    if detailed {
        println!("\n📋 Detailed Migration Plan");
        println!("==========================");
        for file_type in file_types {
            println!("• {} ({} files): {}", 
                file_type.extension, 
                file_type.count, 
                file_type.target_action
            );
        }
    }

    Ok(())
}

/// Print file types JSON
fn print_file_types_json(file_types: &[FileTypeInfo]) -> Result<()> {
    let json = serde_json::to_string_pretty(file_types)?;
    println!("{}", json);
    Ok(())
}

/// Print file types markdown
fn print_file_types_markdown(file_types: &[FileTypeInfo], detailed: bool) -> Result<()> {
    println!("# File Type Analysis\n");
    println!("| Extension | Count | Generated | Status | Priority |");
    println!("|-----------|-------|-----------|--------|----------|");

    for file_type in file_types {
        let status = match file_type.migration_status {
            MigrationStatus::Keep => "Keep",
            MigrationStatus::Generate => "Generate",
            MigrationStatus::Remove => "Remove",
            MigrationStatus::Consolidate => "Consolidate",
        };

        println!(
            "| {} | {} | {} | {} | {} |",
            file_type.extension,
            file_type.count,
            if file_type.is_generated { "Yes" } else { "No" },
            status,
            file_type.priority
        );
    }

    if detailed {
        println!("\n## Migration Plan\n");
        for file_type in file_types {
            println!("- **{}** ({} files): {}", 
                file_type.extension, 
                file_type.count, 
                file_type.target_action
            );
        }
    }

    Ok(())
}

/// Print migration progress table
fn print_migration_progress_table(progress: &FileTypeMigrationProgress, detailed: bool) -> Result<()> {
    println!("\n🔄 Migration Progress");
    println!("====================");
    println!("Total file types: {}", progress.total_types);
    println!("Approved types: {}", progress.approved_types);
    println!("Types to generate: {}", progress.types_to_generate);
    println!("Types to remove: {}", progress.types_to_remove);
    println!("Types to consolidate: {}", progress.types_to_consolidate);
    println!("Migration progress: {:.1}%", progress.migration_progress);

    if !progress.recommendations.is_empty() {
        println!("\n💡 Recommendations");
        println!("==================");
        for (i, rec) in progress.recommendations.iter().enumerate() {
            println!("{}. {}", i + 1, rec);
        }
    }

    if detailed {
        println!("\n📊 Detailed File Types");
        println!("=====================");
        for file_type in &progress.file_types {
            let status = match file_type.migration_status {
                MigrationStatus::Keep => "Keep",
                MigrationStatus::Generate => "Generate",
                MigrationStatus::Remove => "Remove",
                MigrationStatus::Consolidate => "Consolidate",
            };

            println!("• {} ({} files): {} - {}", 
                file_type.extension, 
                file_type.count, 
                status,
                file_type.target_action
            );
        }
    }

    Ok(())
}

/// Print migration progress JSON
fn print_migration_progress_json(progress: &FileTypeMigrationProgress) -> Result<()> {
    let json = serde_json::to_string_pretty(progress)?;
    println!("{}", json);
    Ok(())
}

/// Print migration progress markdown
fn print_migration_progress_markdown(progress: &FileTypeMigrationProgress, detailed: bool) -> Result<()> {
    println!("# File Type Migration Progress\n");
    println!("| Metric | Count |");
    println!("|--------|-------|");
    println!("| Total file types | {} |", progress.total_types);
    println!("| Approved types | {} |", progress.approved_types);
    println!("| Types to generate | {} |", progress.types_to_generate);
    println!("| Types to remove | {} |", progress.types_to_remove);
    println!("| Types to consolidate | {} |", progress.types_to_consolidate);
    println!("| Migration progress | {:.1}% |", progress.migration_progress);

    if !progress.recommendations.is_empty() {
        println!("\n## Recommendations\n");
        for (i, rec) in progress.recommendations.iter().enumerate() {
            println!("{}. {}", i + 1, rec);
        }
    }

    if detailed {
        println!("\n## File Type Details\n");
        for file_type in &progress.file_types {
            let status = match file_type.migration_status {
                MigrationStatus::Keep => "Keep",
                MigrationStatus::Generate => "Generate",
                MigrationStatus::Remove => "Remove",
                MigrationStatus::Consolidate => "Consolidate",
            };

            println!("- **{}** ({} files): {} - {}", 
                file_type.extension, 
                file_type.count, 
                status,
                file_type.target_action
            );
        }
    }

    Ok(())
}

/// Generate migration scripts for file type normalization
async fn generate_migration_scripts(output_dir: &str, all_types: bool) -> Result<()> {
    println!("🔧 Generating Migration Scripts");
    println!("===============================");
    
    // Create output directory
    std::fs::create_dir_all(output_dir)?;
    
    let file_types = get_file_type_analysis().await?;
    let progress = get_migration_progress().await?;
    
    // Filter file types based on priority
    let target_types: Vec<_> = if all_types {
        file_types.iter().filter(|ft| ft.migration_status != MigrationStatus::Keep).collect()
    } else {
        file_types.iter().filter(|ft| ft.priority >= 8).collect()
    };
    
    println!("Generating {} migration scripts...", target_types.len());
    
    // Generate main migration script
    let main_script = generate_main_migration_script(&target_types, &progress)?;
    std::fs::write(format!("{}/migrate-all.sh", output_dir), main_script)?;
    
    // Generate individual scripts for each file type
    for file_type in &target_types {
        let script = generate_file_type_migration_script(file_type)?;
        let filename = format!("{}/migrate-{}.sh", output_dir, file_type.extension);
        std::fs::write(filename, script)?;
    }
    
    // Generate README
    let readme = generate_migration_readme(&target_types, &progress)?;
    std::fs::write(format!("{}/README.md", output_dir), readme)?;
    
    println!("✅ Generated {} migration scripts in '{}'", target_types.len() + 2, output_dir);
    println!("📖 See '{}/README.md' for usage instructions", output_dir);
    
    Ok(())
}

fn generate_main_migration_script(file_types: &[&FileTypeInfo], progress: &FileTypeMigrationProgress) -> Result<String> {
    let mut script = String::new();
    
    script.push_str("#!/bin/bash\n");
    script.push_str("# Hooksmith File Type Migration Script\n");
    script.push_str("# Generated automatically by xtask status generate-migration-scripts\n");
    script.push_str("# Current progress: ");
    script.push_str(&format!("{:.1}%\n", progress.migration_progress));
    script.push_str("\n");
    script.push_str("set -euo pipefail\n");
    script.push_str("\n");
    script.push_str("echo \"🔄 Starting Hooksmith File Type Migration\"\n");
    script.push_str("echo \"Current progress: ");
    script.push_str(&format!("{:.1}%", progress.migration_progress));
    script.push_str("\"\n");
    script.push_str("echo \"Target: 100% Rust-owned pipeline\"\n");
    script.push_str("\n");
    
    for file_type in file_types {
        script.push_str(&format!("# Migrate {} files (Priority: {}, Effort: {})\n", 
            file_type.extension, file_type.priority, file_type.estimated_effort));
        script.push_str(&format!("echo \"📁 Migrating {} files...\"\n", file_type.extension));
        script.push_str(&format!("bash migrate-{}.sh\n", file_type.extension));
        script.push_str("\n");
    }
    
    script.push_str("echo \"✅ Migration complete!\"\n");
    script.push_str("echo \"Run 'cargo xtask status migration-progress' to check progress\"\n");
    
    Ok(script)
}

fn generate_file_type_migration_script(file_type: &FileTypeInfo) -> Result<String> {
    let mut script = String::new();
    
    script.push_str("#!/bin/bash\n");
    script.push_str(&format!("# Migration script for {} files\n", file_type.extension));
    script.push_str(&format!("# Action: {}\n", file_type.target_action));
    script.push_str(&format!("# Priority: {}, Effort: {}\n", file_type.priority, file_type.estimated_effort));
    script.push_str("\n");
    script.push_str("set -euo pipefail\n");
    script.push_str("\n");
    
    match file_type.migration_status {
        MigrationStatus::Remove => {
            script.push_str(&format!("echo \"🗑️  Removing {} files...\"\n", file_type.extension));
            script.push_str(&format!("find . -name \"*.{}\" -type f -delete\n", file_type.extension));
            script.push_str(&format!("echo \"✅ Removed {} files\"\n", file_type.extension));
        }
        MigrationStatus::Generate => {
            script.push_str(&format!("echo \"🔧 Setting up generation for {} files...\"\n", file_type.extension));
            script.push_str(&format!("# TODO: Implement generation for {} files\n", file_type.extension));
            script.push_str(&format!("# Action: {}\n", file_type.target_action));
            script.push_str(&format!("echo \"⚠️  Manual implementation required for {} files\"\n", file_type.extension));
        }
        MigrationStatus::Consolidate => {
            script.push_str(&format!("echo \"🔄 Consolidating {} files...\"\n", file_type.extension));
            script.push_str(&format!("# TODO: Implement consolidation for {} files\n", file_type.extension));
            script.push_str(&format!("# Action: {}\n", file_type.target_action));
            script.push_str(&format!("echo \"⚠️  Manual implementation required for {} files\"\n", file_type.extension));
        }
        MigrationStatus::Keep => {
            script.push_str(&format!("echo \"✅ {} files are already approved\"\n", file_type.extension));
        }
    }
    
    Ok(script)
}

fn generate_migration_readme(file_types: &[&FileTypeInfo], progress: &FileTypeMigrationProgress) -> Result<String> {
    let mut readme = String::new();
    
    readme.push_str("# Hooksmith File Type Migration Scripts\n\n");
    readme.push_str("This directory contains automatically generated migration scripts for normalizing file types in the Hooksmith project.\n\n");
    readme.push_str(&format!("## Current Status\n\n"));
    readme.push_str(&format!("- **Progress**: {:.1}%\n", progress.migration_progress));
    readme.push_str(&format!("- **Total Types**: {}\n", progress.total_types));
    readme.push_str(&format!("- **Types to Migrate**: {}\n", file_types.len()));
    readme.push_str("\n");
    
    readme.push_str("## Usage\n\n");
    readme.push_str("### Run All Migrations\n");
    readme.push_str("```bash\n");
    readme.push_str("chmod +x migrate-all.sh\n");
    readme.push_str("./migrate-all.sh\n");
    readme.push_str("```\n\n");
    
    readme.push_str("### Run Individual Migrations\n");
    for file_type in file_types {
        readme.push_str(&format!("```bash\n"));
        readme.push_str(&format!("chmod +x migrate-{}.sh\n", file_type.extension));
        readme.push_str(&format!("./migrate-{}.sh\n", file_type.extension));
        readme.push_str(&format!("```\n\n"));
    }
    
    readme.push_str("## Migration Details\n\n");
    readme.push_str("| Extension | Priority | Effort | Action |\n");
    readme.push_str("|-----------|----------|--------|--------|\n");
    
    for file_type in file_types {
        readme.push_str(&format!("| {} | {} | {} | {} |\n",
            file_type.extension,
            file_type.priority,
            file_type.estimated_effort,
            file_type.target_action
        ));
    }
    
    readme.push_str("\n## Notes\n\n");
    readme.push_str("- Scripts are generated automatically by `cargo xtask status generate-migration-scripts`\n");
    readme.push_str("- Some scripts require manual implementation of the actual migration logic\n");
    readme.push_str("- Always review scripts before running them\n");
    readme.push_str("- Check progress with `cargo xtask status migration-progress`\n");
    
    Ok(readme)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_output_format() {
        assert!(matches!(
            parse_output_format("table").unwrap(),
            OutputFormat::Table
        ));
        assert!(matches!(
            parse_output_format("json").unwrap(),
            OutputFormat::Json
        ));
        assert!(matches!(
            parse_output_format("markdown").unwrap(),
            OutputFormat::Markdown
        ));
        assert!(parse_output_format("unknown").is_err());
    }

    #[test]
    fn test_status_config_default() {
        let config = StatusConfig::default();
        assert_eq!(config.goal_coverage, 80.0);
        assert!(!config.detailed);
        assert!(config.show_migration_targets);
        assert!(!config.strict);
        assert!(matches!(config.format, OutputFormat::Table));
    }
}
