//! Project Status Tracking
//!
//! This module tracks the percentage of files that are either:
//! - Rust source files (.rs)
//! - Code-generated files that originate from Rust
//!
//! The goal is to achieve 100% Rust-owned coverage where all non-Rust files
//! are generated by the Rust pipeline.

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::process::Command;

/// File status information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileStatus {
    /// File path
    pub path: String,
    /// File extension
    pub extension: String,
    /// Whether it's a Rust source file
    pub is_rust: bool,
    /// Whether it's marked as generated
    pub is_generated: bool,
    /// Whether it's manually maintained
    pub is_manual: bool,
    /// File category
    pub category: FileCategory,
}

/// File categories
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum FileCategory {
    /// Rust source files
    Rust,
    /// Generated files (from Rust pipeline)
    Generated,
    /// Manual files (need migration)
    Manual,
}

/// Project status statistics
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectStatus {
    /// Total number of tracked files
    pub total_files: usize,
    /// Number of Rust source files
    pub rust_files: usize,
    /// Number of generated files
    pub generated_files: usize,
    /// Number of manual files
    pub manual_files: usize,
    /// Rust-owned coverage percentage
    pub rust_owned_coverage: f64,
    /// Goal coverage percentage
    pub goal_coverage: f64,
    /// Whether the goal is met
    pub goal_met: bool,
    /// File type breakdown
    pub file_type_breakdown: HashMap<String, FileTypeStats>,
    /// Manual files that should be migrated
    pub manual_files_to_migrate: Vec<String>,
}

/// File type statistics
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileTypeStats {
    /// File extension
    pub extension: String,
    /// Total count
    pub total: usize,
    /// Generated count
    pub generated: usize,
    /// Manual count
    pub manual: usize,
    /// Rust count
    pub rust: usize,
}

/// Status command configuration
#[derive(Debug, Clone)]
pub struct StatusConfig {
    /// Goal coverage percentage
    pub goal_coverage: f64,
    /// Whether to show detailed breakdown
    pub detailed: bool,
    /// Whether to show manual files to migrate
    pub show_migration_targets: bool,
    /// Whether to fail if goal not met
    pub strict: bool,
    /// Output format
    pub format: OutputFormat,
}

/// Output format options
#[derive(Debug, Clone)]
pub enum OutputFormat {
    /// Human-readable table
    Table,
    /// JSON output
    Json,
    /// Markdown output
    Markdown,
}

impl Default for StatusConfig {
    fn default() -> Self {
        Self {
            goal_coverage: 80.0,
            detailed: false,
            show_migration_targets: true,
            strict: false,
            format: OutputFormat::Table,
        }
    }
}

/// Status command CLI
#[derive(Parser)]
#[command(name = "status")]
#[command(about = "Track Rust-owned project files and coverage")]
pub struct StatusCli {
    #[command(subcommand)]
    command: StatusCommands,
}

#[derive(Subcommand)]
pub enum StatusCommands {
    /// Generate project status report
    Report {
        /// Goal coverage percentage
        #[arg(long, default_value = "80.0")]
        goal: f64,
        /// Show detailed breakdown
        #[arg(long)]
        detailed: bool,
        /// Show manual files to migrate
        #[arg(long)]
        migration_targets: bool,
        /// Fail if goal not met
        #[arg(long)]
        strict: bool,
        /// Output format (table, json, markdown)
        #[arg(long, default_value = "table")]
        format: String,
    },
    /// Generate status badge for CI
    Badge {
        /// Goal coverage percentage
        #[arg(long, default_value = "80.0")]
        goal: f64,
        /// Output file path
        #[arg(long, default_value = "status-badge.json")]
        output: String,
    },
    /// Track status over time
    Trend {
        /// Output directory for trend data
        #[arg(long, default_value = "status-trends")]
        output_dir: String,
    },
}

/// Run a status command
pub async fn run_status_command(command: StatusCommands) -> Result<()> {
    match command {
        StatusCommands::Report {
            goal,
            detailed,
            migration_targets,
            strict,
            format,
        } => {
            let config = StatusConfig {
                goal_coverage: goal,
                detailed,
                show_migration_targets: migration_targets,
                strict,
                format: parse_output_format(&format)?,
            };
            generate_status_report(config).await
        }
        StatusCommands::Badge { goal, output } => generate_status_badge(goal, &output).await,
        StatusCommands::Trend { output_dir } => track_status_trend(&output_dir).await,
    }
}

/// Generate project status report
async fn generate_status_report(config: StatusConfig) -> Result<()> {
    println!("📊 Hooksmith Project Status Report");
    println!("===================================");

    let status = analyze_project_status(config.goal_coverage).await?;

    match config.format {
        OutputFormat::Table => print_status_table(&status, &config)?,
        OutputFormat::Json => print_status_json(&status)?,
        OutputFormat::Markdown => print_status_markdown(&status, &config)?,
    }

    if config.strict && !status.goal_met {
        anyhow::bail!(
            "Goal not met: {}% coverage (goal: {}%)",
            status.rust_owned_coverage,
            config.goal_coverage
        );
    }

    Ok(())
}

/// Analyze project status
async fn analyze_project_status(goal_coverage: f64) -> Result<ProjectStatus> {
    let tracked_files = get_tracked_files().await?;
    let mut file_statuses = Vec::new();

    for file_path in tracked_files {
        let status = analyze_file_status(&file_path).await?;
        file_statuses.push(status);
    }

    // Count files by category
    let mut rust_files = 0;
    let mut generated_files = 0;
    let mut manual_files = 0;
    let mut file_type_breakdown: HashMap<String, FileTypeStats> = HashMap::new();
    let mut manual_files_to_migrate = Vec::new();

    for status in &file_statuses {
        match status.category {
            FileCategory::Rust => rust_files += 1,
            FileCategory::Generated => generated_files += 1,
            FileCategory::Manual => {
                manual_files += 1;
                if !status.is_rust {
                    manual_files_to_migrate.push(status.path.clone());
                }
            }
        }

        // Update file type breakdown
        let stats = file_type_breakdown
            .entry(status.extension.clone())
            .or_insert(FileTypeStats {
                extension: status.extension.clone(),
                total: 0,
                generated: 0,
                manual: 0,
                rust: 0,
            });

        stats.total += 1;
        match status.category {
            FileCategory::Rust => stats.rust += 1,
            FileCategory::Generated => stats.generated += 1,
            FileCategory::Manual => stats.manual += 1,
        }
    }

    let total_files = file_statuses.len();
    let rust_owned_coverage = if total_files > 0 {
        ((rust_files + generated_files) as f64 / total_files as f64) * 100.0
    } else {
        0.0
    };

    let goal_met = rust_owned_coverage >= goal_coverage;

    Ok(ProjectStatus {
        total_files,
        rust_files,
        generated_files,
        manual_files,
        rust_owned_coverage,
        goal_coverage,
        goal_met,
        file_type_breakdown,
        manual_files_to_migrate,
    })
}

/// Get all tracked files from git
async fn get_tracked_files() -> Result<Vec<String>> {
    let output = Command::new("git")
        .args(["ls-files"])
        .output()
        .context("Failed to run git ls-files")?;

    if !output.status.success() {
        anyhow::bail!("git ls-files failed");
    }

    let files = String::from_utf8_lossy(&output.stdout)
        .lines()
        .map(|s| s.to_string())
        .collect();

    Ok(files)
}

/// Analyze status of a single file
async fn analyze_file_status(file_path: &str) -> Result<FileStatus> {
    let path = Path::new(file_path);
    let extension = path
        .extension()
        .and_then(|ext| ext.to_str())
        .unwrap_or("")
        .to_lowercase();

    let is_rust = extension == "rs";
    let is_generated = check_if_generated(file_path).await?;
    let is_manual = !is_rust && !is_generated;

    let category = if is_rust {
        FileCategory::Rust
    } else if is_generated {
        FileCategory::Generated
    } else {
        FileCategory::Manual
    };

    Ok(FileStatus {
        path: file_path.to_string(),
        extension,
        is_rust,
        is_generated,
        is_manual,
        category,
    })
}

/// Check if a file is marked as generated
async fn check_if_generated(file_path: &str) -> Result<bool> {
    let output = Command::new("git")
        .args(["check-attr", "linguist-generated", file_path])
        .output()
        .context("Failed to check file attributes")?;

    if !output.status.success() {
        return Ok(false);
    }

    let output_str = String::from_utf8_lossy(&output.stdout);
    Ok(output_str.contains("linguist-generated: true"))
}

/// Print status as table
fn print_status_table(status: &ProjectStatus, config: &StatusConfig) -> Result<()> {
    println!("\n📈 Coverage Summary");
    println!("==================");
    println!("{:<30} {:>10} {:>8}", "Metric", "Count", "Percentage");
    println!(
        "{:<30} {:>10} {:>8}",
        "Total tracked files", status.total_files, "100.0%"
    );
    println!(
        "{:<30} {:>10} {:>8.1}%",
        "Rust source files (.rs)",
        status.rust_files,
        if status.total_files > 0 {
            (status.rust_files as f64 / status.total_files as f64) * 100.0
        } else {
            0.0
        }
    );
    println!(
        "{:<30} {:>10} {:>8.1}%",
        "Generated files",
        status.generated_files,
        if status.total_files > 0 {
            (status.generated_files as f64 / status.total_files as f64) * 100.0
        } else {
            0.0
        }
    );
    println!(
        "{:<30} {:>10} {:>8.1}%",
        "Manual files",
        status.manual_files,
        if status.total_files > 0 {
            (status.manual_files as f64 / status.total_files as f64) * 100.0
        } else {
            0.0
        }
    );
    println!(
        "{:<30} {:>10} {:>8.1}%",
        "Rust-owned coverage",
        format!(
            "{}/{}",
            status.rust_files + status.generated_files,
            status.total_files
        ),
        status.rust_owned_coverage
    );
    println!("{:<30} {:>10} {:>8.1}%", "Goal", "", status.goal_coverage);

    if status.goal_met {
        println!(
            "\n✅ Goal met! Rust-owned coverage: {:.1}%",
            status.rust_owned_coverage
        );
    } else {
        println!(
            "\n❌ Goal not met. Rust-owned coverage: {:.1}% (goal: {:.1}%)",
            status.rust_owned_coverage, status.goal_coverage
        );
    }

    if config.detailed {
        print_detailed_breakdown(status)?;
    }

    if config.show_migration_targets && !status.manual_files_to_migrate.is_empty() {
        print_migration_targets(status)?;
    }

    Ok(())
}

/// Print detailed file type breakdown
fn print_detailed_breakdown(status: &ProjectStatus) -> Result<()> {
    println!("\n📋 File Type Breakdown");
    println!("=====================");
    println!(
        "{:<10} {:<8} {:<8} {:<8} {:<8}",
        "Extension", "Total", "Rust", "Generated", "Manual"
    );
    println!(
        "{:<10} {:<8} {:<8} {:<8} {:<8}",
        "---------", "-----", "----", "---------", "------"
    );

    let mut extensions: Vec<_> = status.file_type_breakdown.keys().collect();
    extensions.sort();

    for extension in extensions {
        let stats = &status.file_type_breakdown[extension];
        println!(
            "{:<10} {:<8} {:<8} {:<8} {:<8}",
            stats.extension, stats.total, stats.rust, stats.generated, stats.manual
        );
    }

    Ok(())
}

/// Print migration targets
fn print_migration_targets(status: &ProjectStatus) -> Result<()> {
    println!("\n🎯 Migration Targets");
    println!("===================");
    println!(
        "The following {} manual files should be migrated to generation:",
        status.manual_files_to_migrate.len()
    );

    for file in &status.manual_files_to_migrate {
        println!("  • {}", file);
    }

    Ok(())
}

/// Print status as JSON
fn print_status_json(status: &ProjectStatus) -> Result<()> {
    let json = serde_json::to_string_pretty(status)?;
    println!("{}", json);
    Ok(())
}

/// Print status as Markdown
fn print_status_markdown(status: &ProjectStatus, config: &StatusConfig) -> Result<()> {
    println!("# Hooksmith Project Status Report\n");

    println!("## Coverage Summary\n");
    println!("| Metric | Count | Percentage |");
    println!("|--------|-------|------------|");
    println!("| Total tracked files | {} | 100.0% |", status.total_files);
    println!(
        "| Rust source files (.rs) | {} | {:.1}% |",
        status.rust_files,
        if status.total_files > 0 {
            (status.rust_files as f64 / status.total_files as f64) * 100.0
        } else {
            0.0
        }
    );
    println!(
        "| Generated files | {} | {:.1}% |",
        status.generated_files,
        if status.total_files > 0 {
            (status.generated_files as f64 / status.total_files as f64) * 100.0
        } else {
            0.0
        }
    );
    println!(
        "| Manual files | {} | {:.1}% |",
        status.manual_files,
        if status.total_files > 0 {
            (status.manual_files as f64 / status.total_files as f64) * 100.0
        } else {
            0.0
        }
    );
    println!(
        "| **Rust-owned coverage** | **{}/{}** | **{:.1}%** |",
        status.rust_files + status.generated_files,
        status.total_files,
        status.rust_owned_coverage
    );
    println!("| Goal | | {:.1}% |", status.goal_coverage);

    if status.goal_met {
        println!(
            "\n✅ **Goal met!** Rust-owned coverage: {:.1}%",
            status.rust_owned_coverage
        );
    } else {
        println!(
            "\n❌ **Goal not met.** Rust-owned coverage: {:.1}% (goal: {:.1}%)",
            status.rust_owned_coverage, status.goal_coverage
        );
    }

    if config.detailed {
        print_markdown_breakdown(status)?;
    }

    if config.show_migration_targets && !status.manual_files_to_migrate.is_empty() {
        print_markdown_migration_targets(status)?;
    }

    Ok(())
}

/// Print detailed breakdown in Markdown
fn print_markdown_breakdown(status: &ProjectStatus) -> Result<()> {
    println!("\n## File Type Breakdown\n");
    println!("| Extension | Total | Rust | Generated | Manual |");
    println!("|-----------|-------|------|-----------|--------|");

    let mut extensions: Vec<_> = status.file_type_breakdown.keys().collect();
    extensions.sort();

    for extension in extensions {
        let stats = &status.file_type_breakdown[extension];
        println!(
            "| {} | {} | {} | {} | {} |",
            stats.extension, stats.total, stats.rust, stats.generated, stats.manual
        );
    }

    Ok(())
}

/// Print migration targets in Markdown
fn print_markdown_migration_targets(status: &ProjectStatus) -> Result<()> {
    println!("\n## Migration Targets\n");
    println!(
        "The following {} manual files should be migrated to generation:\n",
        status.manual_files_to_migrate.len()
    );

    for file in &status.manual_files_to_migrate {
        println!("- `{}`", file);
    }

    Ok(())
}

/// Generate status badge for CI
async fn generate_status_badge(goal: f64, output_path: &str) -> Result<()> {
    let status = analyze_project_status(goal).await?;

    let badge_data = serde_json::json!({
        "schemaVersion": 1,
        "label": "rust-owned",
        "message": format!("{:.1}%", status.rust_owned_coverage),
        "color": if status.goal_met { "brightgreen" } else { "red" },
        "namedLogo": "rust"
    });

    // Add codegen marker to JSON content
    let mut json_content = serde_json::to_string_pretty(&badge_data)?;
    add_json_codegen_marker(&mut json_content, output_path);

    std::fs::write(output_path, json_content)?;
    println!("✅ Status badge written to: {}", output_path);

    Ok(())
}

/// Track status over time
async fn track_status_trend(output_dir: &str) -> Result<()> {
    let status = analyze_project_status(80.0).await?;

    // Create output directory if it doesn't exist
    std::fs::create_dir_all(output_dir)?;

    // Generate timestamp
    let timestamp = chrono::Utc::now();
    let date_str = timestamp.format("%Y-%m-%d").to_string();

    // Create trend data
    let trend_data = serde_json::json!({
        "date": date_str,
        "timestamp": timestamp.to_rfc3339(),
        "coverage": status.rust_owned_coverage,
        "total_files": status.total_files,
        "rust_files": status.rust_files,
        "generated_files": status.generated_files,
        "manual_files": status.manual_files
    });

    let output_path = format!("{}/status-{}.json", output_dir, date_str);

    // Add codegen marker to JSON content
    let mut json_content = serde_json::to_string_pretty(&trend_data)?;
    add_json_codegen_marker(&mut json_content, &output_path);

    std::fs::write(&output_path, json_content)?;

    println!("✅ Trend data written to: {}", output_path);

    Ok(())
}

/// Parse output format from string
fn parse_output_format(format: &str) -> Result<OutputFormat> {
    match format.to_lowercase().as_str() {
        "table" => Ok(OutputFormat::Table),
        "json" => Ok(OutputFormat::Json),
        "markdown" => Ok(OutputFormat::Markdown),
        _ => anyhow::bail!("Unknown output format: {}", format),
    }
}

/// Add JSON codegen marker to JSON content
fn add_json_codegen_marker(content: &mut String, file_path: &str) {
    let marker = format!(
        "// This file is auto-generated by `cargo xtask status`\n// Generated file: {}\n// Do not edit this file manually - changes will be overwritten\n\n",
        file_path
    );
    println!("DEBUG: Adding marker to file: {}", file_path);
    println!("DEBUG: Marker: {}", marker);
    content.insert_str(0, &marker);
    println!("DEBUG: Content length after marker: {}", content.len());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_output_format() {
        assert!(matches!(
            parse_output_format("table").unwrap(),
            OutputFormat::Table
        ));
        assert!(matches!(
            parse_output_format("json").unwrap(),
            OutputFormat::Json
        ));
        assert!(matches!(
            parse_output_format("markdown").unwrap(),
            OutputFormat::Markdown
        ));
        assert!(parse_output_format("unknown").is_err());
    }

    #[test]
    fn test_status_config_default() {
        let config = StatusConfig::default();
        assert_eq!(config.goal_coverage, 80.0);
        assert!(!config.detailed);
        assert!(config.show_migration_targets);
        assert!(!config.strict);
        assert!(matches!(config.format, OutputFormat::Table));
    }
}
