//! CLI help documentation generator
//!
//! Extracts CLI help text from the actual application using Clap.

use anyhow::{Context, Result};
use std::process::Command;

/// Generate CLI help documentation
pub fn generate_cli_help() -> Result<String> {
    let mut content = String::new();

    content.push_str("# CLI Help Documentation\n\n");
    content.push_str("This document contains the help output for all CLI commands.\n\n");

    // Get main help
    let main_help = Command::new("cargo")
        .args(["run", "--", "--help"])
        .output()
        .context("Failed to get main CLI help")?;

    content.push_str("## Main Help\n");
    content.push_str("```\n");
    content.push_str(&String::from_utf8_lossy(&main_help.stdout));
    content.push_str("```\n\n");

    // Get help for each subcommand
    let subcommands = vec![
        "test",
        "build", 
        "generate",
        "install",
        "list",
        "wasm",
    ];

    content.push_str("## Command Help\n\n");

    for cmd in subcommands {
        let cmd_help = Command::new("cargo")
            .args(["run", "--", cmd, "--help"])
            .output();

        match cmd_help {
            Ok(output) => {
                content.push_str(&format!("### {} Command\n", cmd));
                content.push_str("```\n");
                content.push_str(&String::from_utf8_lossy(&output.stdout));
                content.push_str("```\n\n");
            }
            Err(_) => {
                // Command might not exist or have help, skip it
                continue;
            }
        }
    }

    // Get xtask help
    let xtask_help = Command::new("cargo")
        .args(["xtask", "--help"])
        .output()
        .context("Failed to get xtask help")?;

    content.push_str("## Xtask Commands\n\n");
    content.push_str("```\n");
    content.push_str(&String::from_utf8_lossy(&xtask_help.stdout));
    content.push_str("```\n\n");

    // Get help for xtask subcommands
    let xtask_subcommands = vec![
        "build",
        "gen-wit",
        "gen-lefthook", 
        "gen-docs",
        "gen-schema-docs",
        "gen-readme",
        "gen-mods",
        "gen-hooks-readme",
        "gen-all",
        "check",
        "validate",
        "contract-validate",
        "check-stable",
        "test-with-release",
        "compare-with-release",
        "setup-git-filters",
    ];

    content.push_str("### Xtask Subcommands\n\n");

    for cmd in xtask_subcommands {
        let cmd_help = Command::new("cargo")
            .args(["xtask", cmd, "--help"])
            .output();

        match cmd_help {
            Ok(output) => {
                content.push_str(&format!("#### {} Command\n", cmd));
                content.push_str("```\n");
                content.push_str(&String::from_utf8_lossy(&output.stdout));
                content.push_str("```\n\n");
            }
            Err(_) => {
                // Command might not exist or have help, skip it
                continue;
            }
        }
    }

    content.push_str("---\n\n");
    content.push_str("*This file is auto-generated by `cargo xtask gen-docs-comprehensive`.*\n");

    Ok(content)
} 
