//! Component documentation generator
//!
//! Generates README files for each component in the components directory.

use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

use crate::docs::source_extraction::ProjectData;

/// Generate component documentation from extracted source data
pub fn generate_component_docs(component_path: &str, project_data: &ProjectData) -> Result<String> {
    let mut content = String::new();

    // Extract component name from path
    let component_name = Path::new(component_path)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("unknown");

    // Find component data from extracted source
    let component_data = project_data
        .components
        .iter()
        .find(|c| c.name == component_name)
        .cloned();

    if let Some(component) = component_data {
        // Use extracted data from source
        content.push_str(&format!("# {}\n\n", component.name));
        content.push_str(&format!("{}\n\n", component.description));

        // Dependencies from actual Cargo.toml
        if !component.dependencies.is_empty() {
            content.push_str("## Dependencies\n\n");
            for dep in &component.dependencies {
                content.push_str(&format!("- {}\n", dep));
            }
            content.push_str("\n");
        }

        // Features from actual Cargo.toml
        if !component.features.is_empty() {
            content.push_str("## Features\n\n");
            for feature in &component.features {
                content.push_str(&format!("- {}\n", feature));
            }
            content.push_str("\n");
        }

        // Usage examples from actual source code
        content.push_str("## Usage\n\n");
        content.push_str("```rust\n");
        content.push_str(&format!(
            "use hooksmith::{};\n\n",
            component.name.replace('-', "_")
        ));
        content.push_str(&format!("// Use {} functionality\n", component.name));
        content.push_str("```\n\n");

        // API reference from actual source files
        if let Some(api_docs) = extract_api_documentation(&component.path)? {
            content.push_str("## API Reference\n\n");
            content.push_str(&api_docs);
            content.push_str("\n");
        }

        // Integration with main project
        content.push_str("## Integration\n\n");
        content.push_str(&format!(
            "This component integrates with the main `{}` project.\n\n",
            project_data.name
        ));

        // Testing information from actual test files
        if component.has_tests {
            content.push_str("## Testing\n\n");
            content.push_str("```bash\n");
            content.push_str(&format!("cd components/{}\n", component.name));
            content.push_str("cargo test\n");
            content.push_str("```\n\n");
        }

        // Development setup from actual project structure
        content.push_str("## Development\n\n");
        content.push_str("### Prerequisites\n\n");
        content.push_str("- Rust (latest stable)\n");
        content.push_str("- Cargo\n\n");

        content.push_str("### Setup\n\n");
        content.push_str("```bash\n");
        content.push_str(&format!("cd components/{}\n", component.name));
        content.push_str("cargo build\n");
        content.push_str("```\n\n");
    } else {
        // Fallback for components not found in extracted data
        content.push_str(&format!("# {}\n\n", component_name));
        content.push_str("Component documentation.\n\n");
        content.push_str("## Dependencies\n\n");
        content.push_str("See Cargo.toml for dependencies.\n\n");
        content.push_str("## Usage\n\n");
        content.push_str("```rust\n");
        content.push_str(&format!(
            "use hooksmith::{};\n",
            component_name.replace('-', "_")
        ));
        content.push_str("```\n\n");
    }

    content.push_str("---\n\n");
    content.push_str("*This file is auto-generated by `cargo xtask gen-docs-comprehensive`. Do not edit manually - changes will be overwritten.*\n");

    Ok(content)
}

/// Extract API documentation from component source files
fn extract_api_documentation(component_path: &Path) -> Result<Option<String>> {
    let lib_path = component_path.join("src").join("lib.rs");
    let main_path = component_path.join("src").join("main.rs");

    let source_file = if lib_path.exists() {
        Some(lib_path)
    } else if main_path.exists() {
        Some(main_path)
    } else {
        None
    };

    if let Some(file_path) = source_file {
        let content = fs::read_to_string(&file_path)
            .context(format!("Failed to read source file: {:?}", file_path))?;

        let mut api_docs = String::new();
        let lines: Vec<&str> = content.lines().collect();

        for (i, line) in lines.iter().enumerate() {
            let trimmed = line.trim();

            // Extract public functions and structs
            if trimmed.starts_with("pub fn ")
                || trimmed.starts_with("pub struct ")
                || trimmed.starts_with("pub enum ")
            {
                // Get documentation comments above the item
                let mut docs = Vec::new();
                let mut j = i;
                while j > 0 {
                    j -= 1;
                    let prev_line = lines[j].trim();
                    if prev_line.starts_with("///") {
                        docs.insert(0, prev_line.trim_start_matches("/// "));
                    } else if prev_line.starts_with("//!") {
                        docs.insert(0, prev_line.trim_start_matches("//! "));
                    } else if !prev_line.is_empty() && !prev_line.starts_with("//") {
                        break;
                    }
                }

                // Add documentation
                if !docs.is_empty() {
                    for doc in &docs {
                        api_docs.push_str(&format!("{}\n", doc));
                    }
                    api_docs.push_str("\n");
                }

                // Add the item signature
                api_docs.push_str(&format!("```rust\n{}\n```\n\n", trimmed));
            }
        }

        if !api_docs.is_empty() {
            Ok(Some(api_docs))
        } else {
            Ok(None)
        }
    } else {
        Ok(None)
    }
}
