//! Examples documentation generator
//!
//! Extracts code examples from the examples directory and creates comprehensive documentation.

use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

/// Example code information
#[derive(Debug)]
struct ExampleInfo {
    name: String,
    description: String,
    code: String,
    dependencies: Vec<String>,
    output: Option<String>,
}

/// Generate examples documentation
pub fn generate_examples_docs() -> Result<String> {
    let mut content = String::new();

    content.push_str("# Code Examples\n\n");
    content.push_str(
        "This document contains code examples demonstrating Hooksmith functionality.\n\n",
    );

    // Find all example files
    let examples = find_examples()?;

    if examples.is_empty() {
        content.push_str("## No Examples Found\n\n");
        content.push_str("No example files were found in the `examples/` directory.\n\n");
        content.push_str("To add examples:\n");
        content.push_str("1. Create files in the `examples/` directory\n");
        content.push_str("2. Add descriptive comments at the top of each file\n");
        content.push_str(
            "3. Run `cargo xtask gen-docs-comprehensive` to regenerate this documentation\n",
        );
    } else {
        content.push_str(&format!("## Found {} Examples\n\n", examples.len()));

        // Generate table of contents
        content.push_str("### Table of Contents\n\n");
        for (i, example) in examples.iter().enumerate() {
            content.push_str(&format!(
                "{}. [{}](#{})\n",
                i + 1,
                example.name,
                example.name.to_lowercase().replace(' ', "-")
            ));
        }
        content.push_str("\n");

        // Generate each example section
        for example in examples {
            content.push_str(&format!("## {}\n\n", example.name));
            content.push_str(&format!("{}\n\n", example.description));

            if !example.dependencies.is_empty() {
                content.push_str("### Dependencies\n\n");
                for dep in &example.dependencies {
                    content.push_str(&format!("- {}\n", dep));
                }
                content.push_str("\n");
            }

            content.push_str("### Code\n\n");
            content.push_str("```rust\n");
            content.push_str(&example.code);
            content.push_str("\n```\n\n");

            if let Some(output) = &example.output {
                content.push_str("### Expected Output\n\n");
                content.push_str("```\n");
                content.push_str(output);
                content.push_str("\n```\n\n");
            }

            content.push_str("---\n\n");
        }
    }

    content.push_str("## Running Examples\n\n");
    content.push_str("To run these examples:\n\n");
    content.push_str("```bash\n");
    content.push_str("# Run a specific example\n");
    content.push_str("cargo run --example <example-name>\n\n");
    content.push_str("# Run all examples\n");
    content.push_str("cargo test --examples\n\n");
    content.push_str("# Build examples without running\n");
    content.push_str("cargo build --examples\n");
    content.push_str("```\n\n");

    content.push_str("---\n\n");
    content.push_str("*This file is auto-generated by `cargo xtask gen-docs-comprehensive`. Do not edit manually - changes will be overwritten.*\n");

    Ok(content)
}

/// Find all example files in the examples directory
fn find_examples() -> Result<Vec<ExampleInfo>> {
    let mut examples = Vec::new();

    let examples_dir = Path::new("examples");
    if !examples_dir.exists() {
        return Ok(examples);
    }

    let entries = fs::read_dir(examples_dir).context("Failed to read examples directory")?;

    for entry in entries {
        let entry = entry.context("Failed to read examples directory entry")?;
        let path = entry.path();

        if path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("rs") {
            let example = parse_example_file(&path)?;
            examples.push(example);
        }
    }

    // Sort examples by name
    examples.sort_by(|a, b| a.name.cmp(&b.name));

    Ok(examples)
}

/// Parse an example file to extract information
fn parse_example_file(path: &Path) -> Result<ExampleInfo> {
    let content =
        fs::read_to_string(path).context(format!("Failed to read example file: {:?}", path))?;

    let filename = path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("unknown");
    let name = filename
        .replace('_', " ")
        .split_whitespace()
        .map(|s| {
            let mut chars = s.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().chain(chars).collect(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ");

    // Extract description from comments
    let description = extract_description_from_comments(&content);

    // Extract dependencies from use statements
    let dependencies = extract_dependencies(&content);

    // Extract code (remove comments and clean up)
    let code = clean_code(&content);

    Ok(ExampleInfo {
        name,
        description,
        code,
        dependencies,
        output: None, // Could be enhanced to run examples and capture output
    })
}

/// Extract description from file comments
fn extract_description_from_comments(content: &str) -> String {
    let lines: Vec<&str> = content.lines().collect();
    let mut description = String::new();

    for line in lines {
        let trimmed = line.trim();
        if trimmed.starts_with("//!") {
            description.push_str(&trimmed[3..].trim());
            description.push(' ');
        } else if trimmed.starts_with("///") {
            description.push_str(&trimmed[3..].trim());
            description.push(' ');
        } else if !trimmed.starts_with("//") && !trimmed.is_empty() {
            break;
        }
    }

    description.trim().to_string()
}

/// Extract dependencies from use statements
fn extract_dependencies(content: &str) -> Vec<String> {
    let mut dependencies = Vec::new();

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("use ") {
            let parts: Vec<&str> = trimmed.split_whitespace().collect();
            if parts.len() >= 2 {
                let dep = parts[1].trim_end_matches(';');
                if !dependencies.contains(&dep.to_string()) {
                    dependencies.push(dep.to_string());
                }
            }
        }
    }

    dependencies
}

/// Clean code by removing comments and formatting
fn clean_code(content: &str) -> String {
    let lines: Vec<&str> = content.lines().collect();
    let mut cleaned_lines = Vec::new();

    for line in lines {
        let trimmed = line.trim();
        if !trimmed.starts_with("//!") && !trimmed.starts_with("///") && !trimmed.is_empty() {
            cleaned_lines.push(line);
        }
    }

    cleaned_lines.join("\n")
}
