#!/usr/bin/env -S rustc --edition=2021 -o /tmp/migrate-structure && /tmp/migrate-structure

// @generated by xtask gen-config
// @checksum: {checksum}

// @generated
// This file is automatically generated. Do not edit manually.
// Generated by: Hooksmith xtask

// Simple Hooksmith directory structure migration
// Usage: rustc --edition=2021 -o /tmp/migrate-structure scripts/migrate_structure_simple.rs && /tmp/migrate-structure [--dry-run] [--force] [--verbose]

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let args: Vec<String> = env::args().collect();
    
    let dry_run = args.iter().any(|arg| arg == "--dry-run");
    let force = args.iter().any(|arg| arg == "--force");
    let verbose = args.iter().any(|arg| arg == "--verbose" || arg == "-v");
    
    if args.iter().any(|arg| arg == "--help" || arg == "-h") {
        println!("Hooksmith Directory Structure Migration");
        println!();
        println!("Usage: {} [--dry-run] [--force] [--verbose]", args[0]);
        println!();
        println!("Options:");
        println!("  --dry-run    Show what would be moved without actually moving");
        println!("  --force      Force migration even if some files don't exist");
        println!("  --verbose    Show detailed output");
        println!("  --help       Show this help message");
        return;
    }
    
    println!("🔄 Starting Hooksmith directory structure migration...");
    if dry_run {
        println!("🔍 DRY RUN MODE - no files will be moved");
    }
    
    // Execute migrations
    if let Err(e) = execute_migrations(dry_run, force, verbose) {
        eprintln!("❌ Migration failed: {}", e);
        std::process::exit(1);
    }
    
    println!("✅ Migration completed!");
    print_new_structure();
    print_next_steps();
}

fn execute_migrations(dry_run: bool, force: bool, verbose: bool) -> Result<(), Box<dyn std::error::Error>> {
    let migrations = vec![
        ("summary documents", vec!["*_SUMMARY.md", "*_COMPLETE.md", "*_IMPLEMENTATION.md"], "docs/summaries"),
        ("design documents", vec!["ARCHITECTURE.md", "PROJECT_STRUCTURE.md", "WORKSPACE_LAYOUT.md", "CONTRACT_WORKFLOW_DESIGN.md", "STATUS_SYSTEM_DESIGN.md", "SOURCE_BASED_DOCS.md", "README_STRUCTURE.md", "STRUCTURE.md"], "docs/design"),
        ("guides", vec!["CONTRIBUTING.md", "QUICKSTART_OPTIMIZED.md", "SECURITY_GUIDE.md", "XTASK_COMMANDS.md", "CARGO_BEST_PRACTICES.md", "CHANGELOG.md"], "docs/guides"),
        ("test/demo files", vec!["test_*.rs", "fix_format.rs", "bootstrap.rs"], "examples"),
        ("generated artifacts", vec!["hooksmith-events.jsonl", "status-badge.json", "status-badge.jsonc"], "gen"),
        ("config files", vec!["lefthook-example.yml", ".envrc", ".editorconfig"], "config"),
        ("crates", vec!["components", "xtask", "lefthook-rs"], "crates"),
        ("diagrams", vec!["diagrams"], "docs"),
    ];
    
    for (name, patterns, target_dir) in migrations {
        execute_migration(name, &patterns, target_dir, dry_run, force, verbose)?;
    }
    
    // Clean up remaining files
    cleanup_remaining_files(dry_run, force, verbose)?;
    
    Ok(())
}

fn execute_migration(name: &str, patterns: &[&str], target_dir: &str, dry_run: bool, force: bool, verbose: bool) -> Result<(), Box<dyn std::error::Error>> {
    println!("📁 Moving {} to {}/", name, target_dir);
    
    // Create target directory if it doesn't exist
    let target_path = Path::new(target_dir);
    if !target_path.exists() {
        if !dry_run {
            fs::create_dir_all(target_path)?;
        }
        if verbose {
            println!("   Created directory: {}", target_dir);
        }
    }
    
    for pattern in patterns {
        if let Some(source_path) = find_file_matching_pattern(pattern)? {
            let filename = source_path.file_name().unwrap().to_string_lossy();
            let target_file = target_path.join(&*filename);
            
            if verbose {
                println!("   {} -> {}/{}", source_path.display(), target_dir, filename);
            }
            
            if !dry_run {
                if let Err(e) = fs::rename(&source_path, &target_file) {
                    if force {
                        eprintln!("   ⚠️  Warning: Failed to move {}: {}", source_path.display(), e);
                    } else {
                        return Err(format!("Failed to move {}: {}", source_path.display(), e).into());
                    }
                }
            }
        } else if verbose {
            println!("   ⚠️  File not found: {}", pattern);
        }
    }
    
    Ok(())
}

fn cleanup_remaining_files(dry_run: bool, force: bool, verbose: bool) -> Result<(), Box<dyn std::error::Error>> {
    println!("🧹 Cleaning up remaining files...");
    
    let current_dir = std::env::current_dir()?;
    
    // Move remaining .md files (except README.md)
    for entry in fs::read_dir(&current_dir)? {
        let entry = entry?;
        let path = entry.path();
        
        if path.is_file() {
            if let Some(extension) = path.extension() {
                if extension == "md" && path.file_name().unwrap() != "README.md" {
                    let target_file = Path::new("docs").join(path.file_name().unwrap());
                    
                    if verbose {
                        println!("   {} -> docs/{}", path.display(), path.file_name().unwrap().to_string_lossy());
                    }
                    
                    if !dry_run {
                        if let Err(e) = fs::rename(&path, &target_file) {
                            if force {
                                eprintln!("   ⚠️  Warning: Failed to move {}: {}", path.display(), e);
                            } else {
                                return Err(format!("Failed to move {}: {}", path.display(), e).into());
                            }
                        }
                    }
                } else if extension == "yml" && path.file_name().unwrap() != "lefthook.yml" {
                    let target_file = Path::new("config").join(path.file_name().unwrap());
                    
                    if verbose {
                        println!("   {} -> config/{}", path.display(), path.file_name().unwrap().to_string_lossy());
                    }
                    
                    if !dry_run {
                        if let Err(e) = fs::rename(&path, &target_file) {
                            if force {
                                eprintln!("   ⚠️  Warning: Failed to move {}: {}", path.display(), e);
                            } else {
                                return Err(format!("Failed to move {}: {}", path.display(), e).into());
                            }
                        }
                    }
                } else if extension == "json" || extension == "jsonc" {
                    let target_file = Path::new("gen").join(path.file_name().unwrap());
                    
                    if verbose {
                        println!("   {} -> gen/{}", path.display(), path.file_name().unwrap().to_string_lossy());
                    }
                    
                    if !dry_run {
                        if let Err(e) = fs::rename(&path, &target_file) {
                            if force {
                                eprintln!("   ⚠️  Warning: Failed to move {}: {}", path.display(), e);
                            } else {
                                return Err(format!("Failed to move {}: {}", path.display(), e).into());
                            }
                        }
                    }
                }
            }
        }
    }
    
    Ok(())
}

fn find_file_matching_pattern(pattern: &str) -> Result<Option<PathBuf>, Box<dyn std::error::Error>> {
    let current_dir = std::env::current_dir()?;
    
    // Handle glob patterns
    if pattern.contains('*') {
        // Simple glob pattern matching
        for entry in fs::read_dir(&current_dir)? {
            let entry = entry?;
            let path = entry.path();
            
            if path.is_file() {
                let filename = path.file_name().unwrap().to_string_lossy();
                if matches_glob_pattern(&filename, pattern) {
                    return Ok(Some(path));
                }
            }
        }
    } else {
        // Exact filename match
        let file_path = current_dir.join(pattern);
        if file_path.exists() {
            return Ok(Some(file_path));
        }
    }
    
    Ok(None)
}

fn matches_glob_pattern(filename: &str, pattern: &str) -> bool {
    // Simple glob pattern matching for common cases
    if pattern.starts_with('*') && pattern.ends_with('*') {
        let inner = &pattern[1..pattern.len()-1];
        filename.contains(inner)
    } else if pattern.starts_with('*') {
        let suffix = &pattern[1..];
        filename.ends_with(suffix)
    } else if pattern.ends_with('*') {
        let prefix = &pattern[..pattern.len()-1];
        filename.starts_with(prefix)
    } else {
        filename == pattern
    }
}

fn print_new_structure() {
    println!();
    println!("📂 New structure:");
    println!("├── Cargo.toml");
    println!("├── Cargo.lock");
    println!("├── README.md");
    println!("├── CODEOWNERS");
    println!("├── lefthook.yml");
    println!("├── rust-toolchain.toml");
    println!("├── rustfmt.toml");
    println!("├── clippy.toml");
    println!("├── deny.toml");
    println!("├── crates/           # components, xtask, lefthook-rs");
    println!("├── config/           # configs & schemas");
    println!("├── docs/             # all docs + summaries + diagrams");
    println!("├── examples/         # example code");
    println!("├── gen/              # generated outputs");
    println!("├── scripts/          # dev scripts");
    println!("├── src/");
    println!("├── tests/            # integration tests");
    println!("└── target/");
}

fn print_next_steps() {
    println!();
    println!("🔍 Next steps:");
    println!("1. Review the new structure");
    println!("2. Update any hardcoded paths in your code");
    println!("3. Update Cargo.toml workspace paths if needed");
    println!("4. Test that everything still builds and works");
} 
