name: standard
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  standard:
    uses: bounded-systems/.github/.github/workflows/repo-standard.yml@953ed46c6560abe5366fbcf1235023dc46192776
    with:
      security: true
      test: true
      runtime: none
      test-command: "cargo fmt --all --check && cargo check --workspace && cargo test --workspace"
